// Tự sinh từ "khao sat tang cuong den.xlsx" ngày 2026-05-27
// KHÔNG sửa tay file này. Khi nguồn cập nhật, chạy lại script sinh.

export const PHUONG_XA = [
  { ten: "Hiệp Bình", quan_cu: "TP Thủ Đức" },
  { ten: "Tam Bình", quan_cu: "TP Thủ Đức" },
  { ten: "Thủ Đức", quan_cu: "TP Thủ Đức" },
  { ten: "Linh Xuân", quan_cu: "TP Thủ Đức" },
  { ten: "Long Bình", quan_cu: "TP Thủ Đức" },
  { ten: "Tăng Nhơn Phú", quan_cu: "TP Thủ Đức" },
  { ten: "Phước Long", quan_cu: "TP Thủ Đức" },
  { ten: "Long Phước", quan_cu: "TP Thủ Đức" },
  { ten: "Long Trường", quan_cu: "TP Thủ Đức" },
  { ten: "An Khánh", quan_cu: "TP Thủ Đức" },
  { ten: "Bình Trưng", quan_cu: "TP Thủ Đức" },
  { ten: "Cát Lái", quan_cu: "TP Thủ Đức" },
  { ten: "Tân Định", quan_cu: "Quận 1" },
  { ten: "Bến Thành", quan_cu: "Quận 1" },
  { ten: "Sài Gòn", quan_cu: "Quận 1" },
  { ten: "Cầu Ông Lãnh", quan_cu: "Quận 1" },
  { ten: "Bàn Cờ", quan_cu: "Quận 3" },
  { ten: "Xuân Hòa", quan_cu: "Quận 3" },
  { ten: "Nhiêu Lộc", quan_cu: "Quận 3" },
  { ten: "Vĩnh Hội", quan_cu: "Quận 4" },
  { ten: "Khánh Hội", quan_cu: "Quận 4" },
  { ten: "Xóm Chiếu", quan_cu: "Quận 4" },
  { ten: "Chợ Quán", quan_cu: "Quận 5" },
  { ten: "An Đông", quan_cu: "Quận 5" },
  { ten: "Chợ Lớn", quan_cu: "Quận 5" },
  { ten: "Bình Tiên", quan_cu: "Quận 6" },
  { ten: "Bình Tây", quan_cu: "Quận 6" },
  { ten: "Bình Phú", quan_cu: "Quận 6" },
  { ten: "Phú Lâm", quan_cu: "Quận 6" },
  { ten: "Tân Mỹ", quan_cu: "Quận 7" },
  { ten: "Tân Hưng", quan_cu: "Quận 7" },
  { ten: "Tân Thuận", quan_cu: "Quận 7" },
  { ten: "Phú Thuận", quan_cu: "Quận 7" },
  { ten: "Chánh Hưng", quan_cu: "Quận 8" },
  { ten: "Bình Đông", quan_cu: "Quận 8" },
  { ten: "Phú Định", quan_cu: "Quận 8" },
  { ten: "Vườn Lài", quan_cu: "Quận 10" },
  { ten: "Diên Hồng", quan_cu: "Quận 10" },
  { ten: "Hòa Hưng", quan_cu: "Quận 10" },
  { ten: "Hòa Bình", quan_cu: "Quận 11" },
  { ten: "Phú Thọ", quan_cu: "Quận 11" },
  { ten: "Bình Thới", quan_cu: "Quận 11" },
  { ten: "Minh Phụng", quan_cu: "Quận 11" },
  { ten: "Đông Hưng Thuận", quan_cu: "Quận 12" },
  { ten: "Trung Mỹ Tây", quan_cu: "Quận 12" },
  { ten: "Tân Thới Hiệp", quan_cu: "Quận 12" },
  { ten: "Thới An", quan_cu: "Quận 12" },
  { ten: "An Phú Đông", quan_cu: "Quận 12" },
  { ten: "Gia Định", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Thạnh", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Lợi Trung", quan_cu: "Quận Bình Thạnh" },
  { ten: "Thạnh Mỹ Tây", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Quới", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Tân", quan_cu: "Quận Bình Tân" },
  { ten: "Bình Hưng Hòa", quan_cu: "Quận Bình Tân" },
  { ten: "Bình Trị Đông", quan_cu: "Quận Bình Tân" },
  { ten: "An Lạc", quan_cu: "Quận Bình Tân" },
  { ten: "Tân Tạo", quan_cu: "Quận Bình Tân" },
  { ten: "Hạnh Thông", quan_cu: "Quận Gò Vấp" },
  { ten: "An Nhơn", quan_cu: "Quận Gò Vấp" },
  { ten: "Gò Vấp", quan_cu: "Quận Gò Vấp" },
  { ten: "Thông Tây Hội", quan_cu: "Quận Gò Vấp" },
  { ten: "An Hội Tây", quan_cu: "Quận Gò Vấp" },
  { ten: "An Hội Đông", quan_cu: "Quận Gò Vấp" },
  { ten: "Đức Nhuận", quan_cu: "Quận Phú Nhuận" },
  { ten: "Cầu Kiệu", quan_cu: "Quận Phú Nhuận" },
  { ten: "Phú Nhuận", quan_cu: "Quận Phú Nhuận" },
  { ten: "Tân Sơn Hòa", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Sơn Nhất", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Hòa", quan_cu: "Quận Tân Bình" },
  { ten: "Bảy Hiền", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Bình", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Sơn", quan_cu: "Quận Tân Bình" },
  { ten: "Tây Thạnh", quan_cu: "Quận Tân Phú" },
  { ten: "Tân Sơn Nhì", quan_cu: "Quận Tân Phú" },
  { ten: "Phú Thọ Hòa", quan_cu: "Quận Tân Phú" },
  { ten: "Phú Thạnh", quan_cu: "Quận Tân Phú" },
  { ten: "Tân Phú", quan_cu: "Quận Tân Phú" },
  { ten: "Vĩnh Lộc", quan_cu: "Huyện Bình Chánh" },
  { ten: "Tân Vĩnh Lộc", quan_cu: "Huyện Bình Chánh" },
  { ten: "Bình Lợi", quan_cu: "Huyện Bình Chánh" },
  { ten: "Tân Nhựt", quan_cu: "Huyện Bình Chánh" },
  { ten: "Bình Chánh", quan_cu: "Huyện Bình Chánh" },
  { ten: "Hưng Long", quan_cu: "Huyện Bình Chánh" },
  { ten: "Bình Hưng", quan_cu: "Huyện Bình Chánh" },
  { ten: "An Nhơn Tây", quan_cu: "Huyện Củ Chi" },
  { ten: "Thái Mỹ", quan_cu: "Huyện Củ Chi" },
  { ten: "Nhuận Đức", quan_cu: "Huyện Củ Chi" },
  { ten: "Tân An Hội", quan_cu: "Huyện Củ Chi" },
  { ten: "Củ Chi", quan_cu: "Huyện Củ Chi" },
  { ten: "Phú Hòa Đông", quan_cu: "Huyện Củ Chi" },
  { ten: "Bình Mỹ", quan_cu: "Huyện Củ Chi" },
  { ten: "Bình Khánh", quan_cu: "Huyện Cần Giờ" },
  { ten: "Cần Giờ", quan_cu: "Huyện Cần Giờ" },
  { ten: "An Thới Đông", quan_cu: "Huyện Cần Giờ" },
  { ten: "Thạnh An", quan_cu: "Huyện Cần Giờ" },
  { ten: "Hóc Môn", quan_cu: "Huyện Hóc Môn" },
  { ten: "Bà Điểm", quan_cu: "Huyện Hóc Môn" },
  { ten: "Xuân Thới Sơn", quan_cu: "Huyện Hóc Môn" },
  { ten: "Đông Thạnh", quan_cu: "Huyện Hóc Môn" },
  { ten: "Nhà Bè", quan_cu: "Huyện Nhà Bè" },
  { ten: "Hiệp Phước", quan_cu: "Huyện Nhà Bè" },

  // Huyện Cần Giuộc, tỉnh Long An (bổ sung thủ công 2026-07-07)
  { ten: "Cần Giuộc", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Long Thượng", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Long Hậu", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Long An", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Long Phụng", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Phước Lý", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Phước Vĩnh Đông", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Phước Vĩnh Tây", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Phước Hậu", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Đông Thạnh", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Thuận Thành", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Tân Kim", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Tân Tập", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Mỹ Lộc", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Trường Bình", quan_cu: "Huyện Cần Giuộc, Long An" },
  { ten: "Long Định", quan_cu: "Huyện Cần Giuộc, Long An" },
];

export const QUAN_LIST = [...new Set(PHUONG_XA.map(p => p.quan_cu))].sort();

// TDK_LIST: 1776 tủ điều khiển — cập nhật từ TDK_ChieuSang_8Quan_phuongmoi.xlsx (2026-08-12)
export const TDK_LIST = [
  "151 Huỳnh Văn Bánh - 1 - PN - 12",
  "Alexandre De Rhodes 1",
  "An Bình - 1",
  "An Bình - 2",
  "An Bình - 3",
  "An Bình - 4",
  "An Bình - 5",
  "An Điềm - 1",
  "An Điềm - 2",
  "An Dương Vương - 1",
  "An Dương Vương - 2",
  "An Dương Vương - 3",
  "An Dương Vương - 4",
  "An Dương Vương - 5",
  "An Dương Vương - 6",
  "An Dương Vương - 7",
  "An Dương Vương - 8",
  "An Dương Vương - 9",
  "Ba Đình - 1",
  "Ba Đình - 2",
  "Ba Đình - 3",
  "Ba Đình - 4",
  "Ba Đình - 6",
  "Ba Đình - 7",
  "Ba Đình - 8",
  "Ba Đình - 9",
  "Ba Đình 481",
  "Ba Tháng Hai-1",
  "Ba Tháng Hai-10",
  "Ba Tháng Hai-11",
  "Ba Tháng Hai-12",
  "Ba Tháng Hai-13",
  "Ba Tháng Hai-14",
  "Ba Tháng Hai-2",
  "Ba Tháng Hai-3",
  "Ba Tháng Hai-4",
  "Ba Tháng Hai-5",
  "Ba Tháng Hai-6",
  "Ba Tháng Hai-7",
  "Ba Tháng Hai-8",
  "Ba Tháng Hai-9",
  "Ba Vì",
  "Bà Huyện Thanh Quan 1",
  "Bà Huyện Thanh Quan 2",
  "Bà Huyện Thanh Quan 3",
  "Bà Huyện Thanh Quan 4",
  "Bà Hạt-1",
  "Bà Hạt-2",
  "Bà Hạt-3",
  "Bà Hạt-4",
  "Bà Lê Chân 1",
  "Bàn Cờ 1",
  "Bàn Cờ 2",
  "Bình Điền Khu 17-1",
  "Bình Điền Khu 17-2",
  "Bình Điền Khu 17-3",
  "Bình Đông - 1",
  "Bình Đông - 11",
  "Bình Đông - 13",
  "Bình Đông - 14",
  "Bình Đông - 15",
  "Bình Đông - 16",
  "Bình Đông - 17",
  "Bình Đông - 18",
  "Bình Đông - 2",
  "Bình Đông - 3",
  "Bình Đông - 4",
  "Bình Đông - 7",
  "Bình Đông - 8",
  "Bình Dương Thị Xã",
  "Bình Lợi-1-BT-13",
  "Bình Lợi-2-BT-13",
  "Bình Quới-1-BT-27",
  "Bình Quới-10-BT-28",
  "Bình Quới-11-BT-28",
  "Bình Quới-2-BT-27",
  "Bình Quới-3-BT-27",
  "Bình Quới-4-BT-28",
  "Bình Quới-5-BT-28",
  "Bình Quới-6-BT-28",
  "Bình Quới-7-BT-28",
  "Bình Quới-8-BT-28",
  "Bình Quới-9-BT-28",
  "Bình Thới 2",
  "Bình Thới 4",
  "Bình Thới 6",
  "Bình Thới 7",
  "Bình Thới Làng",
  "Bông Sao - 1",
  "Bông Sao - 2",
  "Bùi Điền - 1",
  "Bùi Điền - 2",
  "Bùi Đình Túy-1-BT-24",
  "Bùi Đình Túy-2-BT-12",
  "Bùi Đình Túy-3-BT-12",
  "Bùi Đình Túy-4-BT-12",
  "Bùi Huy Bích - 1",
  "Bùi Huy Bích - 2",
  "Bùi Hữu Nghĩa-1-BT-1",
  "Bùi Hữu Nghĩa-2-BT-1",
  "Bùi Minh Trực - 1",
  "Bùi Minh Trực - 2",
  "Bùi Minh Trực - 3",
  "Bùi Minh Trực - 4",
  "Bùi Minh Trực - 5",
  "Bùi Minh Trực - 6",
  "Bùi Minh Trực - 7",
  "Bùi Minh Trực - 8",
  "Bùi Minh Trực - 9",
  "Bùi Thị Xuân 1",
  "Bùi Viện 1",
  "Bùi Viện 2",
  "Bùi Văn Thêm -1- PN - 9",
  "Bạch Đằng-1-BT-2",
  "Bạch Đằng-2-BT-15",
  "Bạch Đằng-3-BT-15",
  "Bạch Đằng-4-BT-24",
  "Bến xe Buýt Công Viên 23/9 (Khu B)-1",
  "Bến xe Buýt Công Viên 23/9 (Khu B)-2",
  "Bến xe Chợ Lớn",
  "Bến Xe Quận 8",
  "Bờ Kè  Nguyễn Sĩ Cố",
  "Bờ Kè Bình Đông 1",
  "Bờ Kè Bình Đông 2",
  "Bờ Kè Bình Đông 3",
  "Bờ Kè Bình Đức",
  "Bờ Kè Bùi Huy Bích",
  "Bờ Kè Hoàng Sĩ Khải",
  "Bờ Kè Mễ Cốc",
  "Bờ Kè Nguyễn Nhược Thị",
  "Bờ Kè Ngô Sĩ Liên",
  "Bờ Kè Phú Định 1",
  "Bờ Kè Phú Định 2",
  "C.Viên Thanh Đa-1-BT-25",
  "Calmette 1",
  "Cao Bá Quát 1",
  "Cao Đạt - 3",
  "Cao Su - 3",
  "Cao Su - 4",
  "Cao Su - 5",
  "Cao Thắng - 1- PN- 17",
  "Cao Thắng 1",
  "Cao Thắng 2",
  "Cao Ốc Thuận Việt",
  "CC 44 Đặng Văn Ngữ - 1 - PN- 10",
  "CC 675 Nguyễn Kiệm - 1- PN - 9",
  "CC Hồ Văn Huê -1- PN - 9",
  "CC Miếu Nổi-1-BT-3",
  "CC Miếu Nổi-2-BT-3",
  "CC NGUYỄN VĂN ĐẬU-1-BT-5",
  "CC Phạm Viết Chánh-1-BT-19",
  "CC Phạm Viết Chánh-2-BT-19",
  "Chiếu Sáng 2",
  "Chu Mạnh Trinh 1",
  "Chu Văn An-1-BT-24",
  "Chu Văn An-2-BT-12",
  "Chu Văn An-3-BT-12",
  "Chu Văn An-4-BT-12",
  "Chu Văn An-5-BT-12",
  "Chu Văn An-6-BT-26",
  "Chung cư 109 Nguyễn Biểu",
  "Chung Cư 319/1",
  "Chung Cư 319/2",
  "Chung cư Bình Đăng",
  "Chung cư Him Lam - Nam Khánh",
  "Chung cư Lạc Long Quân-1",
  "Chung cư Lạc Long Quân-2",
  "Chung cư Lạc Long Quân-3",
  "Chung cư Nguyễn Tri Phương",
  "Chung cư Ngô Gia Tự",
  "Chung Cư Nhiêu Lộc 1",
  "Chung Cư Nhiêu Lộc 2",
  "Chung Cư Nơ Trang Long-1-BT-13",
  "Chung Cư Phường 13 Q3",
  "Chung Cư Phường 9 Q3",
  "Chung Cư Rạch Miễu - 1 - PN - 7",
  "Chung cư Sư Vạn Hạnh",
  "Chung cư Sư Vạn Hạnh Lô L",
  "Chung cư Sư Vạn Hạnh Lô N",
  "Chung cư Sư Vạn Hạnh Lô U",
  "Chung cư Trường Đua A",
  "Chung cư Trường Đua B",
  "Chung cư Trần Văn Kiểu",
  "Chung cư Xóm Cải - 1",
  "Chung cư Xóm Cải - 2",
  "Chung cư Ấn Quan",
  "Chánh Hưng - 3A",
  "Chánh Hưng - 5A",
  "Chân cầu Bông-1-BT-3",
  "Chân cầu Chu Văn An-1-BT-26",
  "Châu Thị Hóa",
  "Châu Văn Liêm - 1",
  "Châu Văn Liêm - 2",
  "Châu Văn Liêm - 3",
  "Chợ Quán",
  "Chợ Thiếc 1",
  "Chợ Thiếc 1 TC",
  "Chợ Thiếc 2",
  "CV Dạ Cầu Bình Lợi-1-BT-13",
  "CV Dạ Cầu Bình Lợi-2-BT-13",
  "CVP15Q8",
  "CX NGUYÊN HỒNG-1-BT-5",
  "Cách Mạng Tháng 8 - 4",
  "Cách Mạng Tháng 8 -1",
  "Cách Mạng Tháng 8 -10",
  "Cách Mạng Tháng 8 -12",
  "Cách Mạng Tháng 8 -16",
  "Cách Mạng Tháng 8 -18",
  "Cách Mạng Tháng 8 -19",
  "Cách Mạng Tháng 8 -2",
  "Cách Mạng Tháng 8 -3",
  "Cách Mạng Tháng 8 -5",
  "Cách Mạng Tháng 8 -6",
  "Cách Mạng Tháng 8 -8",
  "Cách Mạng Tháng 8 -9",
  "Cây Điệp 1",
  "Cô Bắc -1- PN - 1",
  "Cô Bắc 1",
  "Cô Giang - 2 - PN - 1",
  "Cô Giang -1- PN - 2",
  "Cô Giang 1",
  "Cô Giang 2",
  "Công Binh",
  "Công Binh TC",
  "Công trường An Đông - 1",
  "Công Trường An Đông - 2",
  "Công Trường Mê Linh 1",
  "Công Trường Quốc Tế 1",
  "Công Trường Quốc Tế 2",
  "Công Trừng 3",
  "Công Viên 23/9 (Khu A) -1",
  "Công Viên 23/9 (Khu A) -2",
  "Công Viên 23/9 (Khu A) -3",
  "Công Viên 23/9 (Khu B) -1",
  "Công Viên 23/9 (Khu B) -2",
  "Công Viên 23/9 (Khu B) -3",
  "Công Viên 23/9 (Khu B) -4",
  "Công Viên 23/9 (Khu B) -5",
  "Công Viên 30/4 -1",
  "Công Viên 30/4 -2",
  "Công Viên 30/4 -3",
  "Công viên An Bình",
  "Công viên dạ Cầu Bình Triệu-1-BT-26",
  "Công viên Dạ Trạch",
  "Công viên Hòa Bình",
  "Công Viên Lê Văn Tám 1",
  "Công Viên Lê Văn Tám 2",
  "Công Viên Lê Văn Tám 3",
  "Công viên Tao Đàn 1",
  "Công viên Tao Đàn 3",
  "Công viên Tao Đàn 4",
  "Công viên Thanh Đa-1-BT-27",
  "Công viên Thanh Đa-2-BT-27",
  "Công viên Tạ Quang Bửu",
  "Công Viên Âu Lạc",
  "Công Xã Paris 1",
  "Công Xã Paris 2",
  "Cù Lao - 2- PN - 2",
  "Cù Lao -1- PN - 2",
  "Cư xá Chánh Hưng A",
  "Cư xá Đồng Tiến-1",
  "Cư xá Đồng Tiến-2",
  "Cư xá Đồng Tiến-3",
  "Cư xá Đồng Tiến-4",
  "Cư xá Hưng Phú",
  "Cư xá Phan Đăng Lưu-1-BT-3",
  "Cư xá Trịnh Đình Trọng",
  "Cảng Than-1-BT-25",
  "Cầm Bá Thước - 1 - PN - 7",
  "Cầu Ba Son",
  "Cầu Bình Lợi-1-BT-13",
  "Cầu Bình Triệu-1-BT-26",
  "Cầu Bình Triệu-2-BT-26",
  "Cầu Băng Ky-1-BT-13",
  "Cầu Calmette 1",
  "Cầu Chu Văn An-1-BT-12",
  "Cầu Chà Và",
  "Cầu Chánh Hưng - 1",
  "Cầu Chánh Hưng - 2",
  "Cầu Chữ Y",
  "Cầu Kinh Thanh Đa-1-BT-25",
  "Cầu Kiệu -1- PN - 2",
  "Cầu Kiệu 1",
  "Cầu Lê Văn Sỹ 1",
  "Cầu Lê Văn Sỹ 2",
  "Cầu Nguyễn Tri Phương - 1",
  "Cầu Nguyễn Tri Phương - 2",
  "Cầu Sài Gòn-1-BT-25",
  "Cầu Sài Gòn-2-BT-25",
  "Cầu Thủ Thiêm-1-BT-22",
  "Cầu Tạ Quang Bửu",
  "Cống Quỳnh 1",
  "Cống Quỳnh 2",
  "Cửu Long A",
  "Cửu Long-1",
  "Cửu Long-2",
  "Diên Nghệ 1",
  "Duy Dương",
  "Duy Dương 180",
  "Duy Tân - 1- PN - 15",
  "Duy Tân - 2 - PN - 15",
  "Duy Tân - 3 - PN - 15",
  "Đinh Bộ Lĩnh-1-BT-26",
  "Đinh Bộ Lĩnh-2-BT-26",
  "Đinh Bộ Lĩnh-3-BT-26",
  "Đinh Bộ Lĩnh-4-BT-24",
  "Đinh Bộ Lĩnh-5-BT-24",
  "Đinh Bộ Lĩnh-6-BT-24",
  "Đinh Bộ Lĩnh-7-BT-24",
  "Đinh Bộ Lĩnh-8-BT-15",
  "Đinh Công Tráng 1",
  "Đinh Hòa",
  "Đinh Tiên Hoàng 1",
  "Đinh Tiên Hoàng 2",
  "Đinh Tiên Hoàng 3",
  "Đinh Tiên Hoàng 4",
  "Điện Biên 110",
  "Điện Biên Phủ 10",
  "Điện Biên Phủ 11",
  "Điện Biên Phủ 12",
  "Điện Biên Phủ 4",
  "Điện Biên Phủ 5",
  "Điện Biên Phủ 6",
  "Điện Biên Phủ 7",
  "Điện Biên Phủ 8",
  "Điện Biên Phủ 9",
  "Điện Biên Phủ-1",
  "Điện Biên Phủ-13-BT-17",
  "Điện Biên Phủ-14-BT-15",
  "Điện Biên Phủ-15-BT-17",
  "Điện Biên Phủ-16-BT-15",
  "Điện Biên Phủ-17-BT-21",
  "Điện Biên Phủ-18-BT-25",
  "Điện Biên Phủ-19-BT-25",
  "Điện Biên Phủ-2",
  "Điện Biên Phủ-20-BT-25",
  "Điện Biên Phủ-21-BT-25",
  "Điện Biên Phủ-22-BT-25",
  "Điện Biên Phủ-3",
  "Điện Biên Phủ-4",
  "Đoàn Công Bửu 1",
  "Đoàn Thị Điểm - 1- PN - 1",
  "Đoàn Thị Điểm - 2 - PN - 1",
  "Đoàn Thị Điểm - 3 - PN - 1",
  "Đào Cam Mộc",
  "Đào Duy Anh - 1 - PN - 9",
  "Đào Duy Anh - 2 - PN - 9",
  "Đào Duy Từ",
  "Đào Duy Từ - 1 - PN - 17",
  "Đình An Tài",
  "Đông Du 1",
  "Đông Du 2",
  "Đông Hồ",
  "Đường 281 Lý Thường Kiệt-1",
  "Đường 281 Lý Thường Kiệt-2",
  "Đường 281 Lý Thường Kiệt-3",
  "Đường 299 Lý Thường Kiệt",
  "Đường 909 Tạ Quang Bửu",
  "Đường D5-1-BT-25",
  "Đường Lô A",
  "Đường số 1 - Cư xá Đô Thành",
  "Đường số 1 Chung cư Bình Đăng",
  "Đường Số 1 Cư xá Lữ Gia-1",
  "Đường Số 1 Cư xá Lữ Gia-2",
  "Đường số 1 KDC Rạch Hiệp Ân",
  "Đường số 1 Phạm Thế Hiển",
  "Đường số 102 Cao Lỗ",
  "Đường số 12 Cư xá Chu Văn An-1-BT-24",
  "Đường số 15 Khu dân cư Đồng Diều",
  "Đường số 2 - Cư xá Đô Thành",
  "Đường số 2 Chánh Hưng",
  "Đường số 2 Cư xá Bình Thới",
  "Đường số 2 Khu dân cư Chánh Hưng",
  "Đường Số 218 Cao Lỗ",
  "Đường số 270 Cao Lỗ",
  "Đường số 3 - Cư xá Đô Thành",
  "Đường số 3 CC Chu Văn An-1-BT-26",
  "Đường số 3 Cư xá Bình Thới",
  "Đường số 3 Cư xá Chu Văn An-1-BT-24",
  "Đường số 31 Chánh Hưng",
  "Đường Số 320 Khu dân cư Chánh Hưng",
  "Đường số 4 - Cư xá Đô Thành",
  "Đường số 4 Cư xá Chu Văn An-1-BT-26",
  "Đường số 5 Cư xá Bình Thới",
  "Đường số 52 Cư xá Lữ Gia-1",
  "Đường Số 52 Cư xá Lữ Gia-2",
  "Đường số 6 Cư xá Bình Thới-1",
  "Đường số 6 Cư xá Bình Thới-2",
  "Đường số 6 Cư xá Bình Thới-3",
  "Đường số 7 Cư xá Bình Thới",
  "Đường số 751 Tạ Quang Bửu - 1",
  "Đường số 751 Tạ Quang Bửu - 2",
  "Đường số 7A Cư xá Bình Thới",
  "Đường số 9 Cao Lỗ",
  "Đường số 9 Cư xá Bình Thới-1",
  "Đường số 9 Cư xá Bình Thới-2",
  "Đường vào Cảng Phú Định",
  "Đặng Chất",
  "Đặng Thái Thân",
  "Đặng Thùy Trâm-1-BT-13",
  "Đặng Thùy Trâm-2-BT-13",
  "Đặng Văn Ngữ - 1- PN - 10",
  "Đặng Văn Ngữ - 2 - PN - 14",
  "Đặng Văn Ngữ - 3 - PN - 14",
  "Đặng Văn Ngữ - 4 - PN - 14",
  "Đặng Văn Sâm -1- PN - 9",
  "Đề Thám 1",
  "Đồng Khởi 1",
  "Đồng Nai 1",
  "Đỗ Ngọc Quang",
  "Đỗ Ngọc Thạnh - 1",
  "Đỗ Ngọc Thạnh - 2",
  "Đỗ Quang Đẩu 1",
  "Đỗ Thị Lời 1",
  "Đỗ Thị Lời 2",
  "Đội Cung",
  "Dã Tượng",
  "Dương Bá Trạc - 1",
  "Dương Bá Trạc - 2",
  "Dương Bạch Mai",
  "Dương Đình Nghệ-1",
  "Dương Đình Nghệ-2",
  "Dương Đình Nghệ-3",
  "Dương Đình Nghệ-4",
  "Dương Quang Đông - 1",
  "Dương Quang Đông - 2",
  "Dương Quang Trung 1",
  "Dương Quang Trung 2",
  "Dương Tử Giang",
  "Dạ Nam - 1",
  "Dạ Nam - 2",
  "Dọc Đường Ray F10 -2- PN - 10",
  "Dọc Đường Ray F10 -3- PN - 10",
  "Dọc Đường Ray F13 - 4 - PN - 13",
  "Dọc Đường Ray F13- 5 - PN - 13",
  "Dọc Đường Ray F9 -1- PN - 9",
  "Dọc Kênh Thanh Đa-1-BT-25",
  "Dọc Kênh Thanh Đa-2-BT-27",
  "Dọc Kênh Thanh Đa-3-BT-27",
  "EMG - 2",
  "EMG - 4",
  "Gia Phú",
  "Giếng Đại Hành TC",
  "Gò Công - 1",
  "Gò Công - 2",
  "H62 Phan Văn Hân-1-BT-17",
  "Hai Bà Trưng 1",
  "Hai Bà Trưng 2",
  "Hai Bà Trưng 3",
  "Hai Bà Trưng 4",
  "Hai Bà Trưng 5",
  "Hai Bà Trưng 6",
  "Hai Bà Trưng 7",
  "Hoa Cau -1- PN - 7",
  "Hoa Cau -2 - PN - 7",
  "Hoa Hồng - 1- PN - 2",
  "Hoa Phượng - 1 - PN - 2",
  "Hoa Phượng - 2 - PN - 2",
  "Hoa Sứ -1- PN - 2",
  "Hoa Sữa - 1 - PN - 7",
  "Hoa Thị - 1 - PN - 7",
  "Hoài Thanh - 1",
  "Hoài Thanh - 2",
  "Hoài Thanh - 3",
  "Hoài Thanh - 4",
  "Hoàng Diệu - 1- PN - 10",
  "Hoàng Diệu - 2 - PN - 10",
  "Hoàng Đạo Thúy - 1",
  "Hoàng Đạo Thúy - 2",
  "Hoàng Đạo Thúy - 3",
  "Hoàng Dư Khương",
  "Hoàng Hoa Thám-1-BT-6",
  "Hoàng Hoa Thám-2-BT-6",
  "Hoàng Minh Đạo",
  "Hoàng Ngân - 1",
  "Hoàng Ngân - 2",
  "Hoàng Ngân - 3",
  "Hoàng Quân 2",
  "Hoàng Sa 1",
  "Hoàng Sa 2",
  "Hoàng Sa 3",
  "Hoàng Sa 4",
  "Hoàng Sa 5",
  "Hoàng Sa 6",
  "Hoàng Sa 7",
  "Hoàng Sa 8",
  "Hoàng Sa 9",
  "Hoàng Văn Thụ - 1 - PN - 8",
  "Hoàng Văn Thụ - 2 - PN - 9",
  "Hoàng Văn Thụ - 3 - PN - 8",
  "Hoàng Văn Thụ - 4 - PN - 15",
  "Huyền Quang 1",
  "Huyền Trân Công Chúa 1",
  "Huyện Toại",
  "Huỳnh Đình Hai-1-BT-24",
  "Huỳnh Đình Hai-2-BT-24",
  "Huỳnh Khương Ninh 1",
  "Huỳnh Thúc Kháng 1",
  "Huỳnh Thúc Kháng 2",
  "Huỳnh Thúc Kháng 3",
  "Huỳnh Thị Phụng",
  "Huỳnh Tịnh Của 1",
  "Huỳnh Tịnh Của-1-BT-19",
  "Huỳnh Văn Bánh - 10 - PN - 10",
  "Huỳnh Văn Bánh - 11 - PN - 14",
  "Huỳnh Văn Bánh - 12 - PN - 14",
  "Huỳnh Văn Bánh - 13 - PN - 14",
  "Huỳnh Văn Bánh - 3 - PN - 17",
  "Huỳnh Văn Bánh - 4 - PN - 12",
  "Huỳnh Văn Bánh - 6 - PN - 11",
  "Huỳnh Văn Bánh - 7 - PN - 11",
  "Huỳnh Văn Bánh - 8 - PN - 11",
  "Huỳnh Văn Bánh - 9 - PN - 11",
  "Hà Tôn Quyền",
  "Hàm Nghi 1",
  "Hàm Nghi 2",
  "Hàm Nghi 3",
  "Hàm Nghi 4",
  "Hàn Hải Nguyên-1",
  "Hàn Hải Nguyên-2",
  "Hàn Hải Nguyên-3",
  "Hàn Hải Nguyên-5",
  "Hàn Hải Nguyên-6",
  "Hàn Hải Nguyên-7",
  "Hàn Hải Nguyên-8",
  "Hàn Hải Nguyên-9",
  "Hàn Thuyên 1",
  "Hòa Bình - 1",
  "Hòa Bình - 2",
  "Hòa Bình-1",
  "Hòa Bình-2",
  "Hòa Hưng",
  "Hòa Hảo-1",
  "Hòa Hảo-2",
  "Hòa Hảo-3",
  "Hòa Hảo-4",
  "Hòa Hảo-5",
  "Hùng Vương - 3",
  "Hùng Vương - 4",
  "Hùng Vương - 5",
  "Hùng Vương 1",
  "Hùng Vương 2",
  "Hưng Phú - 10",
  "Hưng Phú - 11",
  "Hưng Phú - 2",
  "Hưng Phú - 3",
  "Hưng Phú - 4",
  "Hưng Phú - 5",
  "Hưng Phú - 6",
  "Hưng Phú - 7",
  "Hưng Phú - 8",
  "Hưng Phú - 9",
  "Hưng Phú -1",
  "Hương Lộ - 5",
  "Hải Thượng Lãn Ông - 1",
  "Hải Thượng Lãn Ông - 2",
  "Hải Thượng Lãn Ông - 3",
  "Hải Thượng Lãn Ông - 4",
  "Hải Thượng Lãn Ông - 5",
  "Hải Thượng Lãn Ông - 6",
  "Hải Thượng Lãn Ông - 8",
  "Hải Thượng Lãn Ông - 9",
  "Hải Triều 1",
  "Hầm chui Điện Biên Phủ 1",
  "Hẻm 1 Điện Biên Phủ-1-BT-15",
  "Hẻm 1 Đặng Thùy Trâm-1-BT-13",
  "Hẻm 100 Bình Thới-1",
  "Hẻm 100 Bình Thới-2",
  "Hẻm 102 Bình Thới-1",
  "Hẻm 102 Bình Thới-2",
  "Hẻm 106 Lạc Long Quân",
  "Hẻm 107 Trần Hưng Đạo",
  "Hẻm 108 Đào Duy Anh - 1 - PN - 9",
  "Hẻm 109 Dương Bá Trạc",
  "Hẻm 113 Võ Duy Ninh-1-BT-22",
  "Hẻm 113 Võ Duy Ninh-2-BT-22",
  "Hẻm 117 Nguyễn Hữu Cảnh-1-BT-22",
  "Hẻm 12 Đào Duy Anh - 1 - PN - 9",
  "Hẻm 12 Nguyễn Hữu Cảnh-1-BT-19",
  "Hẻm 120 Thích Quảng Đức - 1- PN- 5",
  "Hẻm 120 Thích Quảng Đức - 2 - PN- 5",
  "Hẻm 121 Hưng Phú",
  "Hẻm 123 Nguyễn Xí-1-BT-26",
  "Hẻm 125 Bùi Đình Túy-1-BT-24",
  "Hẻm 125 Bùi Đình Túy-2-BT-24",
  "Hẻm 127 Âu Cơ-1",
  "Hẻm 127 Âu Cơ-2",
  "Hẻm 127/2 Bình Lợi-1-BT-13",
  "Hẻm 128 Lê Văn Duyệt-1-BT-1",
  "Hẻm 134 Đào Duy Anh - 1 - PN - 9",
  "Hẻm 134 Thành Thái",
  "Hẻm 1352 Ba Tháng Hai",
  "Hẻm 136 Trần Phú",
  "Hẻm 138 Ngô Quyền",
  "Hẻm 14 Hoàng Dư Khương",
  "Hẻm 150 Phú Định",
  "Hẻm 151 Lạc Long Quân",
  "Hẻm 152 Lạc Long Quân-1",
  "Hẻm 152 Lạc Long Quân-2",
  "Hẻm 154 Âu Dương Lân",
  "Hẻm 157 Dương Bá Trạc - 1",
  "Hẻm 157 Dương Bá Trạc - 2",
  "Hẻm 158 Hòa Hưng",
  "Hẻm 158 Nguyễn Văn Đậu-1-BT-7",
  "Hẻm 158 Xô Viết Nghệ Tĩnh-1-BT-17",
  "Hẻm 159 CMT8",
  "Hẻm 16 Nguyễn Văn Thương-1-BT-25",
  "Hẻm 160 Bùi Đình Túy-1-BT-12",
  "Hẻm 161 Lạc Long Quân",
  "Hẻm 162/1 Bình Lợi-1-BT-13",
  "Hẻm 163 Tô Hiến Thành",
  "Hẻm 166 Đào Duy Anh - 1 - PN - 9",
  "Hẻm 166 Thích Quảng Đức-1-PN-4",
  "Hẻm 17 Thanh Đa-1-BT-27",
  "Hẻm 172 An Dương Vương - 1",
  "Hẻm 172 An Dương Vương - 2",
  "Hẻm 172 An Dương Vương - 3",
  "Hẻm 172 An Dương Vương - 4",
  "Hẻm 179 /42 Đặng Thùy Trâm-1-BT-13",
  "Hẻm 18 Bis Nguyễn Thị Minh Khai 1",
  "Hẻm 180 Minh Phụng-1",
  "Hẻm 180 Minh Phụng-2",
  "Hẻm 180 Nguyễn Hữu Cảnh-1-BT-22",
  "Hẻm 180 Xô Viết Nghệ Tĩnh-1-BT-17",
  "Hẻm 181 Bình Thới",
  "Hẻm 184 Lê Văn Sỹ -1- PN - 10",
  "Hẻm 185 Lý Thường Kiệt",
  "Hẻm 189B Cống Quỳnh 1",
  "Hẻm 189C Cống Quỳnh",
  "Hẻm 193 Điện Biên Phủ-1-BT-15",
  "Hẻm 195 Bùi Minh Trực",
  "Hẻm 195 Điện Biên Phủ-1-BT-15",
  "Hẻm 2 Điện Biên Phủ-1-BT-25",
  "Hẻm 20 Mễ Cốc",
  "Hẻm 20/1 Đặng Thuỳ Trâm-1-BT-13",
  "Hẻm 200 Thái Phiên",
  "Hẻm 202 Nguyễn Xí-1-BT-26",
  "Hẻm 207 Ba Tháng Hai",
  "Hẻm 21 Bình Lợi-1-BT-13",
  "Hẻm 21 Võ Văn Tần",
  "Hẻm 211 Hoàng Văn Thụ - 1 - PN - 8",
  "Hẻm 212 B Nguyễn Trãi 1",
  "Hẻm 212 B Nguyễn Trãi 2",
  "Hẻm 215B Nguyễn Trãi",
  "Hẻm 217 Xô Viết Nghệ Tĩnh-1-BT-17",
  "Hẻm 218 An Dương Vương",
  "Hẻm 220 Lê Văn Sỹ",
  "Hẻm 220 Nguyễn Xí-1-BT-26",
  "Hẻm 220 Xô Viết Nghệ Tĩnh-1-BT-21",
  "Hẻm 223 - 225 Nguyễn Đình Chiểu",
  "Hẻm 224 Lý Thường Kiệt",
  "Hẻm 227 Điện Biên Phủ-1-BT-15",
  "Hẻm 23 Lê Văn Duyệt-1-BT-3",
  "Hẻm 23 Nơ Trang Long-1-BT-7",
  "Hẻm 232 Bình Lợi-1-BT-13",
  "Hẻm 232 Lý Thường Kiệt",
  "Hẻm 232 Võ Thị Sáu",
  "Hẻm 234/6 Ung Văn Khiêm-1-BT-25",
  "Hẻm 235 Đặng Thùy Trâm-1-BT-13",
  "Hẻm 236 Thái Phiên",
  "Hẻm 237 Phan Văn Hân-1-BT-17",
  "Hẻm 24 Võ Oanh-1-BT-25",
  "Hẻm 258 Bông Sao",
  "Hẻm 26 Lê Văn Duyệt-1-BT-1",
  "Hẻm 26 Nguyễn Bỉnh Khiêm 1",
  "Hẻm 263 Nguyễn Đình Chiểu",
  "Hẻm 269 Nguyễn Thị Nhỏ",
  "Hẻm 27 Bình Lợi-1-BT-13",
  "Hẻm 27 Điện Biên Phủ-1-BT-15",
  "Hẻm 280 Bùi Hữu Nghĩa-1-BT-2",
  "Hẻm 280 Bùi Hữu Nghĩa-2-BT-2",
  "Hẻm 282 Bùi Hữu Nghĩa-1-BT-2",
  "Hẻm 283 Nguyễn Đình Chiểu",
  "Hẻm 284 Lý Thường Kiệt",
  "Hẻm 285 CMT8",
  "Hẻm 286 Trần Hưng Đạo 1",
  "Hẻm 288D Dương Bá Trạc",
  "Hẻm 289 Bình Đông",
  "Hẻm 290 Nơ Trang Long-1-BT-12",
  "Hẻm 290D Dương Bá Trạc",
  "Hẻm 292/23 Bình Lợi-1-BT-13",
  "Hẻm 292/34 Bình Lợi-1-BT-13",
  "Hẻm 3 Thành Thái",
  "Hẻm 30 Phùng Văn Cung - 1 - PN - 7",
  "Hẻm 306 Nguyễn Thị Minh Khai",
  "Hẻm 32 Ông Ích Khiêm-1",
  "Hẻm 32 Ông Ích Khiêm-2",
  "Hẻm 32/36 Bùi Đình Túy-1-BT-12",
  "Hẻm 323 Minh Phụng",
  "Hẻm 33 Trần Khắc Chân - 1- PN - 15",
  "Hẻm 334 Chu Văn An-1-BT-12",
  "Hẻm 334 Lý Thường Kiệt",
  "Hẻm 334 Phan Văn Trị-1-BT-11",
  "Hẻm 339 Tô Hiến Thành",
  "Hẻm 340 Ung Văn Khiêm-1-BT-25",
  "Hẻm 341 Lạc Long Quân-1",
  "Hẻm 341 Lạc Long Quân-2",
  "Hẻm 341 Lạc Long Quân-3",
  "Hẻm 345 Trần Hưng Đạo",
  "Hẻm 346 Bình Lợi-1-BT-13",
  "Hẻm 349 Lê Đại Hành",
  "Hẻm 349/2 Bình Lợi-1-BT-13",
  "Hẻm 35 Cao Lỗ",
  "Hẻm 351 Lê Đại Hành-1",
  "Hẻm 351 Lê Đại Hành-2",
  "Hẻm 352 Bình Lợi-1-BT-13",
  "Hẻm 354 Lý Thường Kiệt",
  "Hẻm 354 Phan Văn Trị-1-BT-11",
  "Hẻm 356 Bạch Đằng-1-BT-14",
  "Hẻm 359 Nguyễn Xí (ND)-1-BT-13",
  "Hẻm 361 Nguyễn Đình Chiểu",
  "Hẻm 36B Đường 762 Hồng Bàng",
  "Hẻm 37 Trịnh Đình Trọng",
  "Hẻm 372 Điện Biên Phủ-1-BT-17",
  "Hẻm 376A Bình Quới-1-BT-28",
  "Hẻm 377 Lê Đại Hành",
  "Hẻm 378 Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 38 Nguyễn Ngọc Cung",
  "Hẻm 38 Nguyễn Văn Trỗi - 1 - PN - 15",
  "Hẻm 382 Nguyễn Thị Minh Khai",
  "Hẻm 384 Nam Kỳ Khởi Nghĩa",
  "Hẻm 39 Đặng Thuỳ Trâm-1-BT-13",
  "Hẻm 392 Cao Thắng",
  "Hẻm 399 Nguyễn Đình Chiểu",
  "Hẻm 401 Bình Lợi-1-BT-13",
  "Hẻm 405 Xô Viết Nghệ Tĩnh-1-BT-24",
  "Hẻm 418 Minh Phụng-1",
  "Hẻm 418 Minh Phụng-2",
  "Hẻm 418 Trần Phú",
  "Hẻm 419 Cách Mạng Tháng 8",
  "Hẻm 42 Ung Văn Khiêm-1-BT-25",
  "Hẻm 423 Lạc Long Quân-1",
  "Hẻm 423 Lạc Long Quân-2",
  "Hẻm 423 Lạc Long Quân-3",
  "Hẻm 43 Thành Thái",
  "Hẻm 436A Ba Tháng Hai",
  "Hẻm 436B Ba Tháng Hai",
  "Hẻm 440 Nguyễn Kiệm -1- PN - 3",
  "Hẻm 441 Điện Biên Phủ-1-BT-25",
  "Hẻm 441 Điện Biên Phủ-2-BT-25",
  "Hẻm 441 Nguyễn Đình Chiểu",
  "Hẻm 449 Sư Vạn Hạnh",
  "Hẻm 45 Ông Ích Khiêm",
  "Hẻm 451 Tô Hiến Thành-1",
  "Hẻm 451 Tô Hiến Thành-2",
  "Hẻm 453 Bùi Minh Trực",
  "Hẻm 46 Nguyễn Cửu Vân-1-BT-17",
  "Hẻm 463 CMT8 1",
  "Hẻm 47 Bùi Đình Túy-1-BT-24",
  "Hẻm 47 Nguyễn Thị Tần",
  "Hẻm 47 Nguyễn Văn Đậu-1-BT-6",
  "Hẻm 480 Nguyễn Tri Phương",
  "Hẻm 486 Phan Xích Long -1- PN - 3",
  "Hẻm 489 Huỳnh Văn Bánh -1- PN - 13",
  "Hẻm 49 Âu Cơ",
  "Hẻm 495 Tô Hiến Thành",
  "Hẻm 498 Lê Quang Định-1-BT-24",
  "Hẻm 4A Nguyễn Văn Thương-1-BT-25",
  "Hẻm 4A/4 Nguyễn Văn Thương-1-BT-25",
  "Hẻm 4A/6 Nguyễn Văn Thương-1-BT-3",
  "Hẻm 5 Nguyễn Đình Chiểu -1",
  "Hẻm 5 Nơ Trang Long-1-BT-7",
  "Hẻm 5/101 Nơ Trang Long-1-BT-7",
  "Hẻm 500 Lê Hồng Phong-1",
  "Hẻm 500 Lê Hồng Phong-2",
  "Hẻm 500 Lê Hồng Phong-3",
  "Hẻm 500 Lê Hồng Phong-4",
  "Hẻm 506 Ba Tháng Hai",
  "Hẻm 51 Thành Thái",
  "Hẻm 518 Võ Văn Kiệt",
  "Hẻm 525 Huỳnh Văn Bánh -1- PN - 13",
  "Hẻm 527 Dương Bá Trạc",
  "Hẻm 528 Điện Biên Phủ 1",
  "Hẻm 535-Phạm Văn Đồng-1-BT-13",
  "Hẻm 54 Đào Duy Anh - 1 - PN - 9",
  "Hẻm 54 Vũ Huy Tấn-1-BT-3",
  "Hẻm 549 Xô Viết Nghệ Tĩnh-1-BT-26",
  "Hẻm 55 Nguyễn Chế Nghĩa",
  "Hẻm 558 Bình Quới-1-BT-28",
  "Hẻm 568 Lạc Long Quân",
  "Hẻm 57 Điện Biên Phủ-1-BT-15",
  "Hẻm 585 Điện Biên Phủ-1-BT-25",
  "Hẻm 606 Ba Tháng Hai-1",
  "Hẻm 606 Ba Tháng Hai-2",
  "Hẻm 618 Ung Văn Khiêm-1-BT-25",
  "Hẻm 62 Huỳnh Tịnh Của-1-BT-19",
  "Hẻm 625 Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 66 Xô Viết Nghệ Tĩnh-1-BT-17",
  "Hẻm 666 Ba Tháng Hai",
  "Hẻm 68 Đồng Nai-1",
  "Hẻm 68 Đồng Nai-2",
  "Hẻm 702 Điện Biên Phủ",
  "Hẻm 702 Hồng Bàng",
  "Hẻm 71 Điện Biên Phủ-1-BT-15",
  "Hẻm 71 Nguyễn Công Hoan - 1 - PN - 7",
  "Hẻm 72 Bạch Đằng-1-BT-24",
  "Hẻm 73 Nguyễn Văn Thương-1-BT-25",
  "Hẻm 750 Nguyễn Kiệm -1- PN - 4",
  "Hẻm 758 Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 758 Xô Viết Nghệ Tĩnh-2-BT-25",
  "Hẻm 76 Bạch Đằng-1-BT-24",
  "Hẻm 76 Xóm Đất",
  "Hẻm 78 Bình Lợi-1-BT-13",
  "Hẻm 79 Âu Cơ-1",
  "Hẻm 79 Âu Cơ-2",
  "Hẻm 7A+7B Thành Thái-1",
  "Hẻm 7A+7B Thành Thái-2",
  "Hẻm 7A+7B Thành Thái-3",
  "Hẻm 8 Tân Hóa-1",
  "Hẻm 8 Tân Hóa-2",
  "Hẻm 80 Bà Huyện Thanh Quan",
  "Hẻm 801/65 Xô Viết Nghệ Tĩnh-1-BT-26",
  "Hẻm 814 Sư Vạn Hạnh",
  "Hẻm 818 Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 82 Bình Quới-1-BT-27",
  "Hẻm 82 Bùi Hữu Nghĩa-2-BT-1",
  "Hẻm 82 Đinh Bộ Lĩnh-1-BT-26",
  "Hẻm 82 Lê Văn Duyệt-1-BT-1",
  "Hẻm 83 Hòa Hưng",
  "Hẻm 86 Thích Quảng Đức- 1- PN - 4",
  "Hẻm 86 Ông Ích Khiêm",
  "Hẻm 860 Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 860/60N Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 860/60S Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 860/60X Xô Viết Nghệ Tĩnh-1-BT-25",
  "Hẻm 88 Đào Duy Anh - 1 - PN - 9",
  "Hẻm 92 Nguyên Hồng-1-BT-11",
  "Hẻm 92 Xô Viết Nghệ Tĩnh-1-BT-17",
  "Hẻm 94 Hoà Bình-1",
  "Hẻm 94 Hoà Bình-2",
  "Hẻm 95 Bình Lợi-1-BT-13",
  "Hẻm 96 Đặng Thuỳ Trâm-1-BT-13",
  "Hẻm Cao Thắng ND",
  "Hẻm Cư xá Phú Thọ Hoà-1",
  "Hẻm Cư xá Phú Thọ Hoà-2",
  "Hẻm số 2 Cao Thắng",
  "Hồ Biểu Chánh",
  "Hồ Biểu Chánh - 1 - PN - 11",
  "Hồ Biểu Chánh -2- PN - 11",
  "Hồ Biểu Chánh -3- PN - 12",
  "Hồ Bá Kiện-1",
  "Hồ Bá Kiện-2",
  "Hồ Huấn Nghiệp 1",
  "Hồ Hảo Hớn 1",
  "Hồ Thành Biên",
  "Hồ Thị Kỷ-1",
  "Hồ Thị Kỷ-2",
  "Hồ Thị Kỷ-3",
  "Hồ Tùng Mậu 1",
  "Hồ Tùng Mậu 2",
  "Hồ Văn Huê - 1 - PN - 9",
  "Hồ Văn Huê - 2 - PN - 9",
  "Hồ Xuân Hương 1",
  "Hồng Bàng - 1",
  "Hồng Bàng - 10",
  "Hồng Bàng - 11",
  "Hồng Bàng - 2",
  "Hồng Bàng - 3",
  "Hồng Bàng - 4",
  "Hồng Bàng - 5",
  "Hồng Bàng - 6",
  "Hồng Bàng - 7",
  "Hồng Bàng - 8",
  "Hồng Bàng - 9",
  "Hồng Bàng-12",
  "Hồng Bàng-13",
  "Hồng Bàng-14",
  "Hồng Hà - 1 -PN - 9",
  "Hữu Chí - 1",
  "Hữu Chí - 2",
  "KDC Bắc Đinh Bộ Lĩnh-1-BT-13",
  "Khu Chung cư hẻm 830 Sư Vạn Hạnh",
  "Khu Chợ Phú Bình-1",
  "Khu Chợ Phú Bình-2",
  "Khu Chợ Phú Bình-3",
  "Khu Chợ Phú Bình-4",
  "Khu dân cư An Dương Vương - 1",
  "Khu dân cư An Dương Vương - 2",
  "Khu dân cư Ba Tơ - 1",
  "Khu dân cư Ba Tơ - 2",
  "Khu dân cư Ba Tơ - 3",
  "Khu dân cư Bông Sao - 4",
  "Khu dân cư Bùi Minh Trực - 1",
  "Khu dân cư Nhật Minh",
  "Khu dân cư Phú Lợi - 1",
  "Khu dân cư Phú Lợi - 2",
  "Khu dân cư Phú Lợi - 3",
  "Khu dân cư Phú Lợi - 4",
  "Khu dân cư Phú Lợi - 5",
  "Khu dân cư Phú Lợi - 6",
  "Khu dân cư Phú Lợi - 7",
  "Khu dân cư Phường 10 Nguyễn Duy - 1",
  "Khu dân cư Phường 10 Nguyễn Duy - 2",
  "Khu dân cư Thanh Nhựt",
  "Khu dân cư Ứng Thành",
  "Khu nhà ở Bông Sao - 1",
  "Khu nhà ở Bông Sao - 2",
  "Khu nhà ở Bùi Minh Trực - 1",
  "Khu nhà ở Bùi Minh Trực - 2",
  "Khu nhà ở K34 Trần Thiện Chánh",
  "Khu nhà ở Lê Thị Riêng-1",
  "Khu nhà ở Lê Thị Riêng-2",
  "Khu TĐC Cảng Phú Định",
  "Khu Thanh Niên Văn Thánh-1-BT-22",
  "Khu tái định cư Bến Lức",
  "Khuôn Viên Uỷ Ban Nhân Dân TP 1",
  "Khánh Vân 3",
  "Kim Khí - 1",
  "KN 541 Sư Vạn Hạnh",
  "KNO 284 Nguyễn Trọng Tuyển -1- PN - 10",
  "KNO 321 Đào Duy Anh -1- PN - 9",
  "KNO 491 Nơ Trang Long-1-BT-13",
  "KNỞ 10A T.N.Duật",
  "KNỞ P12 Trần Thiện Chánh",
  "Kênh Tân Hóa Lò Gốm",
  "Ký Con 1",
  "Ký Con 2",
  "Ký Hòa",
  "Kỳ Đồng 1",
  "Lam Sơn - 1 - PN - 5",
  "Lãnh Binh Thăng 4 TC 3",
  "Lãnh Binh Thăng-1",
  "Lãnh Binh Thăng-2",
  "Lãnh Binh Thăng-3",
  "Lãnh Binh Thăng-4",
  "Lãnh Binh Thăng-5",
  "Lãnh Binh Thăng-6",
  "Lão Tử",
  "Lê Bôi - 1",
  "Lê Bôi - 2",
  "Lê Bôi - 3",
  "Lê Bôi - 4",
  "Lê Công Kiều 1",
  "Lê Duẩn 1",
  "Lê Duẩn 2",
  "Lê Đại Hành-1",
  "Lê Đại Hành-2",
  "Lê Đại Hành-3",
  "Lê Đại Hành-4",
  "Lê Đại Hành-5",
  "Lê Hồng Phong - 6",
  "Lê Hồng Phong - 7",
  "Lê Hồng Phong - 8",
  "Lê Hồng Phong-1",
  "Lê Hồng Phong-2",
  "Lê Hồng Phong-3",
  "Lê Hồng Phong-4",
  "Lê Hồng Phong-5",
  "Lê Lai 1",
  "Lê Lợi 1",
  "Lê Quang Định-1-BT-14",
  "Lê Quang Định-2-BT-14",
  "Lê Quang Định-3-BT-11",
  "Lê Quang Định-4-BT-11",
  "Lê Quang Định-5-BT-11",
  "Lê Quyên",
  "Lê Quý Đôn -1- PN - 11",
  "Lê Quý Đôn 1",
  "Lê Quý Đôn 2",
  "Lê Thánh Tôn 1",
  "Lê Thánh Tôn 2",
  "Lê Thánh Tôn 3",
  "Lê Thánh Tôn 4",
  "Lê Thánh Tôn 5",
  "Lê Thánh Tôn 6",
  "Lê Thị Bạch Cát-1",
  "Lê Thị Bạch Cát-2",
  "Lê Thị Bạch Cát-3",
  "Lê Thị Riêng 1",
  "Lê Trực-1-BT-7",
  "Lê Trực-2-BT-7",
  "Lê Tự Tài - 1 - PN - 4",
  "Lê Tự Tài - 2 - PN - 4",
  "Lê Tự Tài - 3 - PN - 4",
  "Lê Văn Duyệt-1-BT-3",
  "Lê Văn Duyệt-2-BT-1",
  "Lê Văn Sỹ 1",
  "Lê Văn Sỹ 2",
  "Lê Văn Sỹ 3",
  "Lê Văn Sỹ 4",
  "Lò Siêu 2",
  "Lò Siêu 2 TC",
  "Lò Siêu 45",
  "Lò Siêu TC 3",
  "Lô 1 Cư Xá Thanh Đa-1-BT-27",
  "Lô 2 Cư xá Thanh Đa-1-BT-27",
  "Lô 7 Cư Xá Thanh Đa-1-BT-27",
  "Lô 8 Cư xá Thanh Đa-1-BT-27",
  "Lô 9 Cư Xá Thanh Đa-1-BT-27",
  "Lô A-CC Ngô Tất Tố-2-BT-19",
  "Lô B CC Ngô Tất Tố-1-BT-19",
  "Lô B Cư Xá Thanh Đa-1-BT-27",
  "Lô C Cư Xá Thanh Đa-1-BT-27",
  "Lô C Cư Xá Thanh Đa-2-BT-27",
  "Lô C-CC Ngô Tất Tố-3-BT-19",
  "Lô D Cư Xá Thanh Đa-1-BT-27",
  "Lô D Cư Xá Thanh Đa-2-BT-27",
  "Lô E-F Cư xá Bình Thới",
  "Lô G Cư Xá Thanh Đa-1-BT-27",
  "Lô H Cư Xá Thanh Đa-1-BT-27",
  "Lô J Cư Xá Thanh Đa-1-BT-27",
  "Lô L Cư Xá Thanh Đa-1-BT-27",
  "Lô S Cư Xá Thanh Đa-1-BT-27",
  "Lô S Cư Xá Thanh Đa-2-BT-27",
  "Lý Chính Thắng 1",
  "Lý Chính Thắng 2",
  "Lý Đạo Thành",
  "Lý Nam Đế",
  "Lý Thái Tổ 1",
  "Lý Thái Tổ 2",
  "Lý Thái Tổ 3",
  "Lý Thái Tổ 4",
  "Lý Thái Tổ 5",
  "Lý Thái Tổ 6",
  "Lý Thái Tổ 7",
  "Lý Thường Kiệt-1",
  "Lý Thường Kiệt-2",
  "Lý Thường Kiệt-3",
  "Lý Thường Kiệt-4",
  "Lý Thường Kiệt-5",
  "Lý Thường Kiệt-6",
  "Lý Thường Kiệt-7",
  "Lý Thường Kiệt-8",
  "Lý Tự Trọng 1",
  "Lý Tự Trọng 2",
  "Lý Tự Trọng 3",
  "Lý Văn Phức 1",
  "Lưu Hữu Phước - 1",
  "Lưu Hữu Phước - 2",
  "Lưu Hữu Phước - 3",
  "Lưu Hữu Phước - 4",
  "Lưu Hữu Phước - 5",
  "Lưu Hữu Phước - 6",
  "Lưu Quý Kỳ - 1",
  "Lưu Quý Kỳ - 2",
  "Lương Hữu Khánh 1",
  "Lương Ngọc Quyến-1-BT-13",
  "Lương Ngọc Quyến-2-BT-13",
  "Lương Nhữ Học - 1",
  "Lương Nhữ Học - 2",
  "Lương Văn Can",
  "Lạc Long Quân 312/A1",
  "Lạc Long Quân 312/A2",
  "Lạc Long Quân-1",
  "Lạc Long Quân-10",
  "Lạc Long Quân-11",
  "Lạc Long Quân-12",
  "Lạc Long Quân-13",
  "Lạc Long Quân-2",
  "Lạc Long Quân-3",
  "Lạc Long Quân-4",
  "Lạc Long Quân-5",
  "Lạc Long Quân-6",
  "Lạc Long Quân-7",
  "Lạc Long Quân-8",
  "Lạc Long Quân-9",
  "Lộ 50 Hòa Hưng",
  "Lữ Gia",
  "Lữ Gia 3",
  "Lữ Gia 4",
  "Lữ Gia 6",
  "Lữ Gia 7",
  "Mai Hắc Đế",
  "Mai Thị Lựu 1",
  "Mai Thị Lựu 2",
  "Mai Xuân Thưởng-1-BT-11",
  "Minh Phụng 10",
  "Minh Phụng 10 TC",
  "Minh Phụng 11",
  "Minh Phụng 7",
  "Minh Phụng 8",
  "Minh Phụng 9",
  "Mã Hý - 2",
  "Mê Linh-1-BT-19",
  "Mạc Cửu",
  "Mạc Đỉnh Chi 1",
  "Mạc Thiên Tích",
  "Mạc Thị Bưởi 1",
  "Mạc Thị Bưởi 2",
  "Mạc Vân",
  "Mẫn Đạt",
  "Mẫn Đạt - 5",
  "Mễ Cốc - 1",
  "Mễ Cốc - 2",
  "Mễ Cốc - 3",
  "Mễ Cốc - 4",
  "Mễ Cốc - 5",
  "Nam Đế 2 TC",
  "Nam Kỳ Khởi Nghĩa 1",
  "Nam Kỳ Khởi Nghĩa 10",
  "Nam Kỳ Khởi Nghĩa 2",
  "Nam Kỳ Khởi Nghĩa 3",
  "Nam Kỳ Khởi Nghĩa 4",
  "Nam Kỳ Khởi Nghĩa 5",
  "Nam Kỳ Khởi Nghĩa 6",
  "Nam Kỳ Khởi Nghĩa 7",
  "Nam Kỳ Khởi Nghĩa 8",
  "Nam Kỳ Khởi Nghĩa 9",
  "Nam Quốc Cang 1",
  "Nguyễn An Khương",
  "Nguyễn Biểu",
  "Nguyễn Biểu - 2",
  "Nguyễn Bỉnh Khiêm 1",
  "Nguyễn Bỉnh Khiêm 2",
  "Nguyễn Bỉnh Khiêm 3",
  "Nguyễn Chí Thanh - 10",
  "Nguyễn Chí Thanh - 11",
  "Nguyễn Chí Thanh - 2",
  "Nguyễn Chí Thanh - 3",
  "Nguyễn Chí Thanh - 4",
  "Nguyễn Chí Thanh - 6",
  "Nguyễn Chí Thanh - 8",
  "Nguyễn Chí Thanh 1",
  "Nguyễn Chí Thanh 12",
  "Nguyễn Chí Thanh 9",
  "Nguyễn Chí Thanh Nối Dài-1",
  "Nguyễn Chí Thanh Nối Dài-2",
  "Nguyễn Chí Thanh-5",
  "Nguyễn Chí Thanh-7",
  "Nguyễn Chế Nghĩa",
  "Nguyễn Công Hoan - 1- PN - 7",
  "Nguyễn Công Hoan - 2- PN - 7",
  "Nguyễn Công Hoan-3-BT-3",
  "Nguyễn Công Trứ 1",
  "Nguyễn Công Trứ-1-BT-19",
  "Nguyễn Công Trứ-2-BT-19",
  "Nguyễn Cư Trinh 1",
  "Nguyễn Cư Trinh 2",
  "Nguyễn Cư Trinh 3",
  "Nguyễn Cư Trinh 4",
  "Nguyễn Cảnh Chân 1",
  "Nguyễn Cửu Vân-1-BT-17",
  "Nguyễn Cửu Vân-2-BT-17",
  "Nguyễn Cửu Vân-3-BT-17",
  "Nguyễn Du 1",
  "Nguyễn Du 2",
  "Nguyễn Du 3",
  "Nguyễn Du 4",
  "Nguyễn Duy - 1",
  "Nguyễn Duy - 10",
  "Nguyễn Duy - 2",
  "Nguyễn Duy - 3",
  "Nguyễn Duy - 4",
  "Nguyễn Duy - 5",
  "Nguyễn Duy - 6",
  "Nguyễn Duy - 7",
  "Nguyễn Duy - 8",
  "Nguyễn Duy - 9",
  "Nguyễn Duy Dương - 1",
  "Nguyễn Duy Dương - 2",
  "Nguyễn Duy Dương - 3",
  "Nguyễn Duy-1-BT-3",
  "Nguyễn Đình Chiểu - 1 -PN- 3",
  "Nguyễn Đình Chiểu - 2 - PN- 3",
  "Nguyễn Đình Chiểu 1",
  "Nguyễn Đình Chiểu 2",
  "Nguyễn Đình Chiểu 3",
  "Nguyễn Đình Chiểu 4",
  "Nguyễn Đình Chiểu 5",
  "Nguyễn Đình Chiểu 6",
  "Nguyễn Đình Chính - 1 - PN - 15",
  "Nguyễn Đình Chính - 2 - PN - 15",
  "Nguyễn Đình Chính - 3 - PN - 15",
  "Nguyễn Đình Chính - 4 - PN - 15",
  "Nguyễn Đình Chính - 5 - PN - 8",
  "Nguyễn Đình Chính - 6 - PN - 11",
  "Nguyễn Đình Chính - 7 - PN - 11",
  "Nguyễn Đình Chính - 8 - PN - 11",
  "Nguyễn Gia Trí nối dài-1-BT-25",
  "Nguyễn Gia Trí-1-BT-25",
  "Nguyễn Gia Trí-2-BT-25",
  "Nguyễn Gia Trí-3-BT-25",
  "Nguyễn Giản Thanh 1",
  "Nguyễn Huy Lượng-1-BT-14",
  "Nguyễn Huy Tưởng-1-BT-6",
  "Nguyễn Huy Tự 1",
  "Nguyễn Huệ 1",
  "Nguyễn Hữu Cảnh-1-BT-22",
  "Nguyễn Hữu Cảnh-2-BT-22",
  "Nguyễn Hữu Cảnh-3-BT-22",
  "Nguyễn Hữu Cảnh-4-BT-22",
  "Nguyễn Hữu Cảnh-5-BT-22",
  "Nguyễn Hữu Cầu 1",
  "Nguyễn Khắc Nhu 1",
  "Nguyễn Kim",
  "Nguyễn Kiệm - 1- PN - 3",
  "Nguyễn Kiệm - 2 - PN - 4",
  "Nguyễn Lâm-1",
  "Nguyễn Lâm-1-BT-3",
  "Nguyễn Lâm-2",
  "Nguyễn Lâm-2-BT-3",
  "Nguyễn Ngọc Cung - 1",
  "Nguyễn Ngọc Cung - 2",
  "Nguyễn Ngọc Lộc 1",
  "Nguyễn Nhược Thị",
  "Nguyễn Phi Khanh 1",
  "Nguyễn Phúc Nguyên 1",
  "Nguyễn Phúc Nguyên 2",
  "Nguyễn Quyền",
  "Nguyễn Siêu 1",
  "Nguyễn Sĩ Cố",
  "Nguyễn Thi - 1",
  "Nguyễn Thi - 2",
  "Nguyễn Thiện Thuật 1",
  "Nguyễn Thiện Thuật-1-BT-24",
  "Nguyễn Thành Ý 1",
  "Nguyễn Thái Bình 1",
  "Nguyễn Thái Bình 2",
  "Nguyễn Thái Bình 3",
  "Nguyễn Thái Bình 4",
  "Nguyễn Thái Học 1",
  "Nguyễn Thái Học 2",
  "Nguyễn Thái Học 3",
  "Nguyễn Thái Học 4",
  "Nguyễn Thông 1",
  "Nguyễn Thông 2",
  "Nguyễn Thượng Hiền 1",
  "Nguyễn Thượng Hiền-1-BT-5",
  "Nguyễn Thượng Hiền-2-BT-5",
  "Nguyễn Thượng Hiền-3-BT-5",
  "Nguyễn Thị Diệu 1",
  "Nguyễn Thị Huỳnh -1- PN - 8",
  "Nguyễn Thị Minh Khai 1",
  "Nguyễn Thị Minh Khai 10",
  "Nguyễn Thị Minh Khai 11",
  "Nguyễn Thị Minh Khai 12",
  "Nguyễn Thị Minh Khai 2",
  "Nguyễn Thị Minh Khai 4",
  "Nguyễn Thị Minh Khai 5",
  "Nguyễn Thị Minh Khai 6",
  "Nguyễn Thị Minh Khai 7",
  "Nguyễn Thị Minh Khai 8",
  "Nguyễn Thị Minh Khai 9",
  "Nguyễn Thị Nhỏ",
  "Nguyễn Thị Tần - 1",
  "Nguyễn Thị Tần - 2",
  "Nguyễn Thị Tần - 3",
  "Nguyễn Thị Tần - 4",
  "Nguyễn Tri Phương - 5",
  "Nguyễn Tri Phương - 6",
  "Nguyễn Tri Phương-1",
  "Nguyễn Tri Phương-2",
  "Nguyễn Tri Phương-3",
  "Nguyễn Tri Phương-4",
  "Nguyễn Trung Ngạn 1",
  "Nguyễn Trung Trực 1",
  "Nguyễn Trung Trực 2",
  "Nguyễn Trung Trực 3",
  "Nguyễn Trãi - 10",
  "Nguyễn Trãi - 6",
  "Nguyễn Trãi - 7",
  "Nguyễn Trãi - 8",
  "Nguyễn Trãi - 9",
  "Nguyễn Trãi 1",
  "Nguyễn Trãi 2",
  "Nguyễn Trãi 3",
  "Nguyễn Trãi 4",
  "Nguyễn Trãi 5",
  "Nguyễn Trãi 6",
  "Nguyễn Trọng Tuyển - 2 - PN - 8",
  "Nguyễn Trọng Tuyển - 3 - PN - 8",
  "Nguyễn Trọng Tuyển - 4 - PN - 8",
  "Nguyễn Trọng Tuyển - 5 - PN - 8",
  "Nguyễn Trọng Tuyển - 6 - PN - 8",
  "Nguyễn Trọng Tuyển - 7 - PN - 15",
  "Nguyễn Trọng Tuyển -1- PN - 8",
  "Nguyễn Văn Bình 1",
  "Nguyễn Văn Của",
  "Nguyễn Văn Cừ - 3",
  "Nguyễn Văn Cừ - 4",
  "Nguyễn Văn Cừ - 5",
  "Nguyễn Văn Cừ 1",
  "Nguyễn Văn Cừ 2",
  "Nguyễn Văn Đậu-1-BT-11",
  "Nguyễn Văn Đậu-2-BT-6",
  "Nguyễn Văn Giai 1",
  "Nguyễn Văn Lạc-1-BT-19",
  "Nguyễn Văn Lạc-2-BT-17",
  "Nguyễn Văn Mai 1",
  "Nguyễn Văn Nguyễn 1",
  "Nguyễn Văn Nguyễn 2",
  "Nguyễn Văn Nguyễn 3",
  "Nguyễn Văn Phú 1",
  "Nguyễn Văn Thương-1-BT-25",
  "Nguyễn Văn Thương-2-BT-25",
  "Nguyễn Văn Thương-3-BT-25",
  "Nguyễn Văn Thủ 1",
  "Nguyễn Văn Thủ 2",
  "Nguyễn Văn Thủ 3",
  "Nguyễn Văn Tráng 1",
  "Nguyễn Văn Trỗi - 1-PN - 17",
  "Nguyễn Văn Trỗi - 2 - PN - 17",
  "Nguyễn Văn Trỗi - 3 - PN - 15",
  "Nguyễn Văn Trỗi - 4 - PN - 8",
  "Nguyễn Văn Trỗi - 5 - PN - 10",
  "Nguyễn Văn Trỗi - 6 - PN - 12",
  "Nguyễn Xuân Ôn-1-BT-19",
  "Nguyễn Xí-1-BT-13",
  "Nguyễn Xí-2-BT-26",
  "Nguyễn Xí-3-BT-26",
  "Nguyễn Xí-4-BT-13",
  "Nguyễn Xí-5-BT-13",
  "Nguyễn Án",
  "Ngô Đức Kế 1",
  "Ngô Đức Kế 2",
  "Ngô Đức Kế-1-BT-12",
  "Ngô Đức Kế-2-BT-12",
  "Ngô Gia Tự - 4",
  "Ngô Gia Tự 1",
  "Ngô Gia Tự 2",
  "Ngô Gia Tự 3",
  "Ngô Quyền - 1",
  "Ngô Quyền - 2",
  "Ngô Quyền-3",
  "Ngô Quyền-4",
  "Ngô Quyền-5",
  "Ngô Quyền-6",
  "Ngô Thời Nhiệm -1- PN - 17",
  "Ngô Thời Nhiệm 1",
  "Ngô Tất Tố-1-BT-19",
  "Ngô Tất Tố-2-BT-19",
  "Ngô Tất Tố-3-BT-22",
  "Ngô Văn Năm 1",
  "Nhiêu Tâm - 24",
  "Nhiêu Tâm - 4",
  "Nhiêu Tứ - 1 - PN - 7",
  "Nhà thi đấu TT Rạch Miễu - 1-PN-2",
  "Nhân Tôn-1",
  "Nhân Tôn-2",
  "Nhật Tiến",
  "Nhật Tảo-1",
  "Nhật Tảo-2",
  "Nơ Trang Long-1-BT-13",
  "Nơ Trang Long-2-BT-13",
  "Nơ Trang Long-3-BT-13",
  "Nơ Trang Long-4-BT-12",
  "Pasteur 1",
  "Pasteur 2",
  "Pasteur 3",
  "Pasteur 4",
  "Pasteur 5",
  "Pasteur 6",
  "Pasteur 7",
  "Pasteur 8",
  "Phan Bội Châu 1",
  "Phan Bội Châu-1-BT-14",
  "Phan Chu Trinh 1",
  "Phan Chu Trinh-1-BT-2",
  "Phan Châu Trinh-1-BT-12",
  "Phan Châu Trinh-2-BT-13",
  "Phan Đình Phùng - 1 - PN - 1",
  "Phan Đình Phùng -2 - PN - 15",
  "Phan Đăng Lưu - 1 - PN - 2",
  "Phan Đăng Lưu - 2 - PN - 5",
  "Phan Đăng Lưu-3-BT-3",
  "Phan Đăng Lưu-4-BT-6",
  "Phan Liêm 1",
  "Phan Phú Tiên - 1",
  "Phan Phú Tiên - 2",
  "Phan Tây Hồ - 1 - PN- 7",
  "Phan Văn Hân-1-BT-17",
  "Phan Văn Hân-2-BT-17",
  "Phan Văn Trị-1-BT-12",
  "Phan Văn Trị-2-BT-12",
  "Phan Văn Trị-3-BT-11",
  "Phan Văn Trị-4-BT-11",
  "Phan Văn Trị-5-BT-11",
  "Phan Xích Long",
  "Phan Xích Long - 1- PN - 1",
  "Phan Xích Long - 2 - PN - 1",
  "Phan Xích Long - 3 - PN - 7",
  "Phan Xích Long - 4 - PN - 2",
  "Phan Xích Long - 5 - PN - 3",
  "Phó Cơ Điều",
  "Phó Đức Chính 1",
  "Phó Đức Chính 2",
  "Phó Đức Chính-1-BT-1",
  "Phù Đổng Thiên Vương",
  "Phùng Bích TC",
  "Phùng Hưng",
  "Phùng Khắc Khoan 1",
  "Phùng Khắc Khoan 2",
  "Phùng Văn Cung - 1- PN - 4",
  "Phùng Văn Cung - 2- PN - 4",
  "Phùng Văn Cung - 3 - PN - 2",
  "Phùng Văn Cung - 4 - PN - 2",
  "Phú Định - 1",
  "Phú Định - 2",
  "Phú Định - 3",
  "Phú Định - 4",
  "Phú Định - 5",
  "Phú Định - 6",
  "Phú Định - 7",
  "Phú Giáo",
  "Phú Hữu - 1",
  "Phú Hữu - 2",
  "Phú Mỹ nối dài-1-BT-22",
  "Phú Thọ 1",
  "Phú Thọ 2A",
  "Phú Thọ 3",
  "Phước Hưng",
  "Phước Thiện - 3",
  "Phạm Đức Sơn - 1",
  "Phạm Đức Sơn - 2",
  "Phạm Đức Sơn - 3",
  "Phạm Hùng - 1",
  "Phạm Hùng - 2",
  "Phạm Ngũ Lão 1",
  "Phạm Ngũ Lão 2",
  "Phạm Ngũ Lão 3",
  "Phạm Ngọc Thạch 1",
  "Phạm Ngọc Thạch 2",
  "Phạm Nhữ Tăng",
  "Phạm Thế Hiển - 1",
  "Phạm Thế Hiển - 10",
  "Phạm Thế Hiển - 11",
  "Phạm Thế Hiển - 12",
  "Phạm Thế Hiển - 13",
  "Phạm Thế Hiển - 14",
  "Phạm Thế Hiển - 15",
  "Phạm Thế Hiển - 16",
  "Phạm Thế Hiển - 17",
  "Phạm Thế Hiển - 18",
  "Phạm Thế Hiển - 19",
  "Phạm Thế Hiển - 2",
  "Phạm Thế Hiển - 20",
  "Phạm Thế Hiển - 21",
  "Phạm Thế Hiển - 22",
  "Phạm Thế Hiển - 23",
  "Phạm Thế Hiển - 24",
  "Phạm Thế Hiển - 25",
  "Phạm Thế Hiển - 26",
  "Phạm Thế Hiển - 27",
  "Phạm Thế Hiển - 28",
  "Phạm Thế Hiển - 29",
  "Phạm Thế Hiển - 3",
  "Phạm Thế Hiển - 30",
  "Phạm Thế Hiển - 31",
  "Phạm Thế Hiển - 32",
  "Phạm Thế Hiển - 33",
  "Phạm Thế Hiển - 34",
  "Phạm Thế Hiển - 35",
  "Phạm Thế Hiển - 4",
  "Phạm Thế Hiển - 5",
  "Phạm Thế Hiển - 6",
  "Phạm Thế Hiển - 7",
  "Phạm Thế Hiển - 8",
  "Phạm Thế Hiển - 9",
  "Phạm Viết Chánh-1-BT-19",
  "Phạm Viết Chánh-2-BT-19",
  "Phạm Văn Đồng-1-BT-13",
  "Phạm Văn Đồng-2-BT-13",
  "Phạm Văn Đồng-3-BT-11",
  "Phồn Vinh - 3",
  "Quan Âm TC",
  "Quân Sự",
  "Quản Trọng Linh - 1",
  "Quản Trọng Linh - 2",
  "Quốc Lộ 13-1-BT-26",
  "Quốc Lộ 13-2-BT-26",
  "Quốc Lộ 50-1",
  "Quốc Lộ 50-2",
  "Rạch Bà Tàng - 1",
  "Rạch Bà Tàng - 2",
  "Rạch Cát",
  "Rạch Ụ Cây - 1",
  "Rạch Ụ Cây - 2",
  "Sân Thể Thao Phú Thọ",
  "Sư Thiện Chiếu 1",
  "Sư Vạn Hạnh - 4",
  "Sư Vạn Hạnh 1",
  "Sư Vạn Hạnh 2",
  "Sư Vạn Hạnh 3",
  "Sư Vạn Hạnh ND 1",
  "Sương Nguyệt Ánh 1",
  "Sỹ Quan 3",
  "Tam Đảo",
  "TĐK Hầm 2-1-BT-15",
  "Thanh Đa-1-BT-27",
  "Thanh Đa-2-BT-27",
  "Thi Sách 1",
  "Thành Thái ND-1",
  "Thành Thái ND-2",
  "Thành Thái-1",
  "Thành Thái-2",
  "Thái Phiên-1",
  "Thái Phiên-2",
  "Thái Phiên-3",
  "Thái Phiên-4",
  "Thái Văn Lung 1",
  "Thích Quảng Đức - 1- PN - 5",
  "Thích Quảng Đức - 2 - PN - 4",
  "Thất Hiệp 1/1",
  "Thời Trung",
  "Thủ Khoa Huân 1",
  "Tiểu Đảo Nguyễn Công Hoan -1- PN - 2",
  "Tiểu La-3",
  "Tiểu La-4",
  "Trương Đình Hội - 1",
  "Trương Đình Hội - 2",
  "Trương Định 1",
  "Trương Định 2",
  "Trương Định 3",
  "Trương Định 4",
  "Trương Định 5",
  "Trương Quyền 1",
  "Trương Quốc Dung - 1 - PN - 10",
  "Trương Quốc Dung - 2 - PN",
  "Trường Sa - 11 - PN- 14",
  "Trường Sa - 5 - PN- 2",
  "Trường Sa - 6 - PN- 2",
  "Trường Sa - 7 - PN- 2",
  "Trường Sa 10",
  "Trường Sa 8",
  "Trường Sa 9",
  "Trường Sa-1-BT-19",
  "Trường Sa-2-BT-17",
  "Trường Sa-3-BT-17",
  "Trường Sa-4-BT-15",
  "Trạm Cầu Bông 1",
  "Trần Bình Trọng - 3",
  "Trần Bình Trọng - 4",
  "Trần Bình Trọng - 5",
  "Trần Bình Trọng-1",
  "Trần Bình Trọng-1-BT-5",
  "Trần Bình Trọng-2",
  "Trần Bình Trọng-2-GV-1",
  "Trần Cao Vân - 1 - PN - 12",
  "Trần Cao Vân 1",
  "Trần Chánh Chiếu",
  "Trần Đình Xu 1",
  "Trần Huy Liệu - 1- PN - 8",
  "Trần Huy Liệu - 2- PN - 8",
  "Trần Huy Liệu - 3- PN - 8",
  "Trần Huy Liệu - 4 - PN - 15",
  "Trần Huy Liệu - 7 - PN - 12",
  "Trần Hưng Đạo - 11",
  "Trần Hưng Đạo - 12",
  "Trần Hưng Đạo - 13",
  "Trần Hưng Đạo - 14",
  "Trần Hưng Đạo - 15",
  "Trần Hưng Đạo - 16",
  "Trần Hưng Đạo - 17",
  "Trần Hưng Đạo - 18",
  "Trần Hưng Đạo - 19",
  "Trần Hưng Đạo - 20",
  "Trần Hưng Đạo - 21",
  "Trần Hưng Đạo - 22",
  "Trần Hưng Đạo - 23",
  "Trần Hưng Đạo - 24",
  "Trần Hưng Đạo - 25",
  "Trần Hưng Đạo - 26",
  "Trần Hưng Đạo - 27",
  "Trần Hưng Đạo - 28",
  "Trần Hưng Đạo - 29",
  "Trần Hưng Đạo - 30",
  "Trần Hưng Đạo - 31",
  "Trần Hưng Đạo - 32",
  "Trần Hưng Đạo - 33",
  "Trần Hưng Đạo - 34",
  "Trần Hưng Đạo 1",
  "Trần Hưng Đạo 10",
  "Trần Hưng Đạo 2",
  "Trần Hưng Đạo 3",
  "Trần Hưng Đạo 4",
  "Trần Hưng Đạo 5",
  "Trần Hưng Đạo 6",
  "Trần Hưng Đạo 7",
  "Trần Hưng Đạo 8",
  "Trần Hưng Đạo 9",
  "Trần Hữu Trang - 2 - PN - 11",
  "Trần Hữu Trang - 3 - PN - 11",
  "Trần Hữu Trang-1- PN - 10",
  "Trần Khánh Dư 1",
  "Trần Khánh Dư 2",
  "Trần Khắc Chân - 2 - PN - 9",
  "Trần Khắc Chân 1",
  "Trần Khắc Chân 2",
  "Trần Kế Xương -1- PN - 7",
  "Trần Minh Quyền",
  "Trần Nguyên Hãn",
  "Trần Nhật Duật 1",
  "Trần Nhật Duật 2",
  "Trần Phú",
  "Trần Phú - 1",
  "Trần Phú - 2",
  "Trần Phú - 3",
  "Trần Phú - 4",
  "Trần Phú - 5",
  "Trần Phú - 6",
  "Trần Phú - 7",
  "Trần Phú - 8",
  "Trần Quang Diệu 1",
  "Trần Quang Diệu 2",
  "Trần Quang Khải 1",
  "Trần Quang Khải 2",
  "Trần Quang Khải 3",
  "Trần Quang Khải 4",
  "Trần Quý 1",
  "Trần Quý 1 TC",
  "Trần Quý Cáp-1-BT-11",
  "Trần Quý Khoách 1",
  "Trần Quốc Thảo 1",
  "Trần Quốc Thảo 2",
  "Trần Quốc Thảo 3",
  "Trần Quốc Thảo 4",
  "Trần Quốc Toản 1",
  "Trần Quốc Toản 2",
  "Trần Thiện Chánh-1",
  "Trần Thiện Chánh-2",
  "Trần Thị Ngôi",
  "Trần Văn Đang 1",
  "Trần Văn Đang 2",
  "Trần Văn Đang 3",
  "Trần Văn Đang 4",
  "Trần Văn Khê-1-BT-17",
  "Trần Văn Kỷ-1-BT-14",
  "Trịnh Đình Trọng-1",
  "Trịnh Đình Trọng-2",
  "Trịnh Hoài Đức-1-BT-1",
  "Trịnh Quang Nghị - 1",
  "Trịnh Quang Nghị - 2",
  "Trịnh Quang Nghị - 3",
  "Trịnh Quang Nghị - 4",
  "Trịnh Quang Nghị - 5",
  "Trịnh Văn Cấn 1",
  "Tuy Lý Vương",
  "Tuệ Tĩnh",
  "Tuệ Tĩnh 204",
  "Tám Danh - 1",
  "Tám Danh - 2",
  "Tám Danh - 3",
  "Tân Cảng-1-BT-15",
  "Tân Hưng - 1",
  "Tân Hưng - 2",
  "Tân Hưng - 3",
  "Tân Khai-1",
  "Tân Khai-2",
  "Tân Khai-3",
  "Tân Phước-1",
  "Tân Phước-2",
  "Tân Thành",
  "Tân Thành Nối Dài-1",
  "Tân Thành Nối Dài-2",
  "Tô Hiến Thành-1",
  "Tô Hiến Thành-2",
  "Tô Hiến Thành-3",
  "Tô Hiến Thành-4",
  "Tôn Đức Thắng 1",
  "Tôn Đức Thắng 2",
  "Tôn Đức Thắng 3",
  "Tôn Đức Thắng 4",
  "Tôn Đức Thắng 5",
  "Tôn Đức Thắng 6",
  "Tôn Đức Thắng 7",
  "Tôn Thất Đạm 1",
  "Tôn Thất Đạm 2",
  "Tôn Thất Hiệp-1",
  "Tôn Thất Hiệp-2",
  "Tôn Thất Hiệp-3",
  "Tôn Thất Thiệp 1",
  "Tôn Thất Tùng 1",
  "Tùng Thiện Vương - 1",
  "Tùng Thiện Vương - 2",
  "Tùng Thiện Vương - 3",
  "Tùng Thiện Vương - 4",
  "Tùng Thiện Vương - 5",
  "Tùng Thiện Vương - 6",
  "Tùng Thiện Vương - 7",
  "Tùng Thiện Vương - 8",
  "Tú Xương 1",
  "Tú Xương 2",
  "Tăng Bạt Hổ",
  "Tăng Bạt Hổ-1-BT-11",
  "Tạ Quang Bửu - 1",
  "Tạ Quang Bửu - 1/1",
  "Tạ Quang Bửu - 1/2A",
  "Tạ Quang Bửu - 2",
  "Tạ Quang Bửu - 3",
  "Tạ Quang Bửu - 5",
  "Tạ Quang Bửu - 6",
  "Tạ Quang Bửu - 7",
  "Tạ Quang Bửu - 8",
  "Tạ Uyên - 1",
  "Tạ Uyên - 2",
  "Tản Đà - 1",
  "Tản Đà - 2",
  "Tầm Vu-1-BT-25",
  "Tống Văn Trân",
  "Tổng Lung",
  "Ung Văn Khiêm-1-BT-25",
  "Ung Văn Khiêm-2-BT-25",
  "Ung Văn Khiêm-3-BT-25",
  "Ung Văn Khiêm-4-BT-25",
  "Việt Phát - 2",
  "Vòng Xoay Dân Chủ 1",
  "Vòng Xoay Hàng Xanh-1-BT-17",
  "Vòng Xoay Hàng Xanh-2-BT-21",
  "Vòng Xoay Hàng Xanh-3-BT-25",
  "Vòng Xoay Hàng Xanh-4-BT-25",
  "Vòng Xoay Hàng Xanh-5-BT-15",
  "Vòng xoay Lạc Long Quân - Hoà Bình",
  "Vòng Xoay Ngã - 6",
  "Võ Duy Ninh-1-BT-22",
  "Võ Oanh-1-BT-25",
  "Võ Thị Sáu 1",
  "Võ Thị Sáu 2",
  "Võ Trường Toản-1-BT-2",
  "Võ Văn Kiệt - 12",
  "Võ Văn Kiệt - 3",
  "Võ Văn Kiệt - 4",
  "Võ Văn Kiệt - 5",
  "Võ Văn Kiệt - 6",
  "Võ Văn Kiệt - 7",
  "Võ Văn Kiệt - 8",
  "Võ Văn Kiệt 1",
  "Võ Văn Kiệt 2",
  "Võ Văn Tần 1",
  "Võ Văn Tần 2",
  "Văn Đừng - 22",
  "Vĩnh Nam",
  "Vĩnh Viễn-1",
  "Vĩnh Viễn-10",
  "Vĩnh Viễn-2",
  "Vĩnh Viễn-3",
  "Vĩnh Viễn-4",
  "Vĩnh Viễn-6",
  "Vĩnh Viễn-7",
  "Vĩnh Viễn-8",
  "Vĩnh Viễn-9",
  "Vũ Huy Tấn-1-BT-3",
  "Vũ Ngọc Phan-1-BT-13",
  "Vũ Tùng-1-BT-1",
  "Vũ Tùng-2-BT-2",
  "Vũ Tùng-3-BT-2",
  "Vườn Chuối 1",
  "Vạn Kiếp-1-BT-3",
  "Vạn Kiếp-2-BT-3",
  "Vạn Tượng - 1",
  "Vạn Tượng - 2",
  "Xây Dựng Mới 7",
  "Xóm Chỉ",
  "Xóm Củi - 1",
  "Xóm Đất 1",
  "Xóm Đất 2",
  "Xóm Đất 3",
  "Xóm Đất 4",
  "Xóm Vôi - 1",
  "Xóm Vôi - 2",
  "Xô Viết Nghệ Tĩnh-1-BT-17",
  "Xô Viết Nghệ Tĩnh-2-BT-17",
  "Xô Viết Nghệ Tĩnh-3-BT-25",
  "Xô Viết Nghệ Tĩnh-4-BT-25",
  "Xô Viết Nghệ Tĩnh-5-BT-25",
  "Yersin 1",
  "Yên Đổ-1-BT-2",
  "Yết Kiêu",
  "Âu Cơ-1",
  "Âu Cơ-2",
  "Âu Cơ-3",
  "Âu Cơ-4",
  "Âu Dương Lân - 1",
  "Âu Dương Lân - 2",
  "Âu Dương Lân - 3",
  "Âu Dương Lân - 4",
  "Âu Dương Lân - 5",
  "Âu Dương Lân - 6",
  "Âu Dương Lân - 7",
  "Ông Tích 1",
  "Ông Tích 2",
  "Ông Ích Khiêm 2",
  "Ông Ích Khiêm 3",
  "Ông Ích Khiêm 4",
  "Ưu Long",
  "Ấn Quan 3",
  "Ấn Quan 4",
];

// Mapping phường mới (sau sáp nhập 2025) → danh sách TĐK thuộc phường đó
// Dùng để lọc gợi ý TĐK khi Người khảo sát đã chọn Phường trong form
export const TDK_BY_PHUONG = {
  "An Đông": ["An Bình - 1", "An Bình - 2", "An Bình - 3", "An Bình - 4", "An Bình - 5", "An Dương Vương - 7", "An Dương Vương - 8", "An Dương Vương - 9", "Chung cư Sư Vạn Hạnh", "Chung cư Xóm Cải - 1", "Chung cư Xóm Cải - 2", "Chợ Quán", "Công trường An Đông - 1", "Công Trường An Đông - 2", "Công viên An Bình", "Công viên Dạ Trạch", "Công viên Hòa Bình", "Cầu Nguyễn Tri Phương - 1", "Cầu Nguyễn Tri Phương - 2", "Hòa Bình - 1", "Hòa Bình - 2", "Hùng Vương - 3", "Hùng Vương - 4", "Hùng Vương - 5", "Hẻm 107 Trần Hưng Đạo", "Hẻm 418 Trần Phú", "Mạc Thiên Tích", "Mẫn Đạt - 5", "Nguyễn Chí Thanh - 2", "Nguyễn Chí Thanh - 3", "Nguyễn Duy Dương - 1", "Nguyễn Duy Dương - 2", "Nguyễn Duy Dương - 3", "Nguyễn Tri Phương - 5", "Nguyễn Tri Phương - 6", "Nguyễn Trãi - 7", "Nguyễn Trãi - 8", "Ngô Gia Tự - 4", "Nhiêu Tâm - 24", "Nhiêu Tâm - 4", "Phước Hưng", "Phước Thiện - 3", "Sư Vạn Hạnh - 4", "Thời Trung", "Trần Hưng Đạo - 18", "Trần Hưng Đạo - 19", "Trần Hưng Đạo - 20", "Trần Hưng Đạo - 21", "Trần Hưng Đạo - 22", "Trần Hưng Đạo - 23", "Trần Hưng Đạo - 24", "Trần Hưng Đạo - 25", "Trần Hưng Đạo - 26", "Trần Hưng Đạo - 27", "Trần Phú - 1", "Trần Phú - 2", "Trần Phú - 3", "Trần Phú - 4", "Trần Phú - 5", "Trần Phú - 6", "Vòng Xoay Ngã - 6", "Võ Văn Kiệt - 4", "Võ Văn Kiệt - 5", "Võ Văn Kiệt - 6", "Võ Văn Kiệt - 7", "Văn Đừng - 22", "Yết Kiêu"],
  "Bàn Cờ": ["Bàn Cờ 1", "Bàn Cờ 2", "Cao Thắng 1", "Cao Thắng 2", "Cách Mạng Tháng 8 -5", "Cách Mạng Tháng 8 -9", "Đường số 1 - Cư xá Đô Thành", "Đường số 2 - Cư xá Đô Thành", "Đường số 3 - Cư xá Đô Thành", "Đường số 4 - Cư xá Đô Thành", "Hẻm 223 - 225 Nguyễn Đình Chiểu", "Hẻm 263 Nguyễn Đình Chiểu", "Hẻm 283 Nguyễn Đình Chiểu", "Hẻm 361 Nguyễn Đình Chiểu", "Hẻm 382 Nguyễn Thị Minh Khai", "Hẻm 399 Nguyễn Đình Chiểu", "Hẻm 441 Nguyễn Đình Chiểu", "Hẻm số 2 Cao Thắng", "Lý Thái Tổ 1", "Lý Thái Tổ 2", "Lý Thái Tổ 3", "Lý Thái Tổ 4", "Nguyễn Đình Chiểu 6", "Nguyễn Thiện Thuật 1", "Nguyễn Thượng Hiền 1", "Võ Văn Tần 2", "Vườn Chuối 1"],
  "Bình Đông": ["Bình Điền Khu 17-1", "Bình Điền Khu 17-2", "Bình Điền Khu 17-3", "Bông Sao - 1", "Bông Sao - 2", "Bùi Minh Trực - 1", "Bùi Minh Trực - 2", "Bùi Minh Trực - 3", "Bùi Minh Trực - 4", "Bùi Minh Trực - 5", "Bùi Minh Trực - 6", "Bùi Minh Trực - 7", "Bùi Minh Trực - 8", "Bùi Minh Trực - 9", "Bến Xe Quận 8", "Chung cư Bình Đăng", "Cầu Tạ Quang Bửu", "Đình An Tài", "Đường 909 Tạ Quang Bửu", "Đường Lô A", "Đường số 1 Chung cư Bình Đăng", "Hoàng Đạo Thúy - 1", "Hoàng Đạo Thúy - 2", "Hoàng Đạo Thúy - 3", "Hoàng Minh Đạo", "Hẻm 195 Bùi Minh Trực", "Hẻm 258 Bông Sao", "Hẻm 453 Bùi Minh Trực", "Khu dân cư Ba Tơ - 1", "Khu dân cư Ba Tơ - 2", "Khu dân cư Ba Tơ - 3", "Khu dân cư Bông Sao - 4", "Khu dân cư Bùi Minh Trực - 1", "Khu dân cư Phú Lợi - 1", "Khu dân cư Phú Lợi - 2", "Khu dân cư Phú Lợi - 3", "Khu dân cư Phú Lợi - 4", "Khu dân cư Phú Lợi - 5", "Khu dân cư Phú Lợi - 6", "Khu dân cư Phú Lợi - 7", "Khu dân cư Ứng Thành", "Khu nhà ở Bông Sao - 1", "Khu nhà ở Bông Sao - 2", "Khu nhà ở Bùi Minh Trực - 1", "Khu nhà ở Bùi Minh Trực - 2", "Khu tái định cư Bến Lức", "Lê Bôi - 1", "Lê Bôi - 2", "Lê Bôi - 3", "Lê Bôi - 4", "Nhật Tiến", "Phạm Thế Hiển - 15", "Phạm Thế Hiển - 16", "Phạm Thế Hiển - 17", "Phạm Thế Hiển - 18", "Phạm Thế Hiển - 19", "Phạm Thế Hiển - 20", "Phạm Thế Hiển - 21", "Phạm Thế Hiển - 22", "Phạm Thế Hiển - 23", "Phạm Thế Hiển - 24", "Phạm Thế Hiển - 25", "Phạm Thế Hiển - 26", "Phạm Thế Hiển - 27", "Phạm Thế Hiển - 28", "Phạm Thế Hiển - 29", "Phạm Thế Hiển - 30", "Phạm Thế Hiển - 31", "Phạm Thế Hiển - 32", "Phạm Thế Hiển - 33", "Phạm Thế Hiển - 34", "Phạm Thế Hiển - 35", "Quản Trọng Linh - 1", "Quản Trọng Linh - 2", "Quốc Lộ 50-1", "Quốc Lộ 50-2", "Rạch Bà Tàng - 1", "Rạch Bà Tàng - 2", "Trịnh Quang Nghị - 1", "Trịnh Quang Nghị - 2", "Trịnh Quang Nghị - 3", "Trịnh Quang Nghị - 4", "Trịnh Quang Nghị - 5", "Tạ Quang Bửu - 6", "Tạ Quang Bửu - 7", "Tạ Quang Bửu - 8"],
  "Bình Lợi Trung": ["Bình Lợi-1-BT-13", "Bình Lợi-2-BT-13", "CC NGUYỄN VĂN ĐẬU-1-BT-5", "Chung Cư Nơ Trang Long-1-BT-13", "CV Dạ Cầu Bình Lợi-1-BT-13", "CV Dạ Cầu Bình Lợi-2-BT-13", "CX NGUYÊN HỒNG-1-BT-5", "Cầu Bình Lợi-1-BT-13", "Đặng Thùy Trâm-1-BT-13", "Đặng Thùy Trâm-2-BT-13", "Hẻm 1 Đặng Thùy Trâm-1-BT-13", "Hẻm 127/2 Bình Lợi-1-BT-13", "Hẻm 162/1 Bình Lợi-1-BT-13", "Hẻm 179 /42 Đặng Thùy Trâm-1-BT-13", "Hẻm 20/1 Đặng Thuỳ Trâm-1-BT-13", "Hẻm 21 Bình Lợi-1-BT-13", "Hẻm 232 Bình Lợi-1-BT-13", "Hẻm 235 Đặng Thùy Trâm-1-BT-13", "Hẻm 27 Bình Lợi-1-BT-13", "Hẻm 292/23 Bình Lợi-1-BT-13", "Hẻm 292/34 Bình Lợi-1-BT-13", "Hẻm 334 Phan Văn Trị-1-BT-11", "Hẻm 346 Bình Lợi-1-BT-13", "Hẻm 349/2 Bình Lợi-1-BT-13", "Hẻm 352 Bình Lợi-1-BT-13", "Hẻm 354 Phan Văn Trị-1-BT-11", "Hẻm 359 Nguyễn Xí (ND)-1-BT-13", "Hẻm 39 Đặng Thuỳ Trâm-1-BT-13", "Hẻm 401 Bình Lợi-1-BT-13", "Hẻm 47 Nguyễn Văn Đậu-1-BT-6", "Hẻm 498 Lê Quang Định-1-BT-24", "Hẻm 535-Phạm Văn Đồng-1-BT-13", "Hẻm 78 Bình Lợi-1-BT-13", "Hẻm 92 Nguyên Hồng-1-BT-11", "Hẻm 95 Bình Lợi-1-BT-13", "Hẻm 96 Đặng Thuỳ Trâm-1-BT-13", "KNO 491 Nơ Trang Long-1-BT-13", "Lê Quang Định-4-BT-11", "Lê Quang Định-5-BT-11", "Lương Ngọc Quyến-1-BT-13", "Lương Ngọc Quyến-2-BT-13", "Mai Xuân Thưởng-1-BT-11", "Nguyễn Thượng Hiền-1-BT-5", "Nguyễn Thượng Hiền-2-BT-5", "Nguyễn Thượng Hiền-3-BT-5", "Nguyễn Văn Đậu-1-BT-11", "Nguyễn Xí-1-BT-13", "Nguyễn Xí-4-BT-13", "Nguyễn Xí-5-BT-13", "Nơ Trang Long-1-BT-13", "Nơ Trang Long-2-BT-13", "Phan Châu Trinh-2-BT-13", "Phan Văn Trị-4-BT-11", "Phan Văn Trị-5-BT-11", "Phạm Văn Đồng-1-BT-13", "Phạm Văn Đồng-2-BT-13", "Phạm Văn Đồng-3-BT-11", "Trần Bình Trọng-1-BT-5", "Tăng Bạt Hổ-1-BT-11", "Vũ Ngọc Phan-1-BT-13"],
  "Bình Phú": ["An Dương Vương - 5", "An Dương Vương - 6", "An Dương Vương - 7", "Hẻm 218 An Dương Vương", "Khu dân cư Thanh Nhựt", "Võ Văn Kiệt - 12"],
  "Bình Quới": ["Bình Quới-1-BT-27", "Bình Quới-10-BT-28", "Bình Quới-11-BT-28", "Bình Quới-2-BT-27", "Bình Quới-3-BT-27", "Bình Quới-4-BT-28", "Bình Quới-5-BT-28", "Bình Quới-6-BT-28", "Bình Quới-7-BT-28", "Bình Quới-8-BT-28", "Bình Quới-9-BT-28", "Công viên Thanh Đa-1-BT-27", "Công viên Thanh Đa-2-BT-27", "Dọc Kênh Thanh Đa-2-BT-27", "Dọc Kênh Thanh Đa-3-BT-27", "Hẻm 17 Thanh Đa-1-BT-27", "Hẻm 376A Bình Quới-1-BT-28", "Hẻm 558 Bình Quới-1-BT-28", "Hẻm 82 Bình Quới-1-BT-27", "Lô 1 Cư Xá Thanh Đa-1-BT-27", "Lô 2 Cư xá Thanh Đa-1-BT-27", "Lô 7 Cư Xá Thanh Đa-1-BT-27", "Lô 8 Cư xá Thanh Đa-1-BT-27", "Lô 9 Cư Xá Thanh Đa-1-BT-27", "Lô B Cư Xá Thanh Đa-1-BT-27", "Lô C Cư Xá Thanh Đa-1-BT-27", "Lô C Cư Xá Thanh Đa-2-BT-27", "Lô D Cư Xá Thanh Đa-1-BT-27", "Lô D Cư Xá Thanh Đa-2-BT-27", "Lô G Cư Xá Thanh Đa-1-BT-27", "Lô H Cư Xá Thanh Đa-1-BT-27", "Lô J Cư Xá Thanh Đa-1-BT-27", "Lô L Cư Xá Thanh Đa-1-BT-27", "Lô S Cư Xá Thanh Đa-1-BT-27", "Lô S Cư Xá Thanh Đa-2-BT-27", "Thanh Đa-1-BT-27", "Thanh Đa-2-BT-27", "Trần Văn Kỷ-1-BT-14"],
  "Bình Thạnh": ["Bùi Đình Túy-1-BT-24", "Bùi Đình Túy-2-BT-12", "Bùi Đình Túy-3-BT-12", "Bùi Đình Túy-4-BT-12", "Bạch Đằng-4-BT-24", "C.Viên Thanh Đa-1-BT-25", "Chu Văn An-1-BT-24", "Chu Văn An-2-BT-12", "Chu Văn An-3-BT-12", "Chu Văn An-4-BT-12", "Chu Văn An-5-BT-12", "Chu Văn An-6-BT-26", "Chân cầu Chu Văn An-1-BT-26", "Công viên dạ Cầu Bình Triệu-1-BT-26", "Cầu Bình Triệu-1-BT-26", "Cầu Bình Triệu-2-BT-26", "Cầu Băng Ky-1-BT-13", "Cầu Chu Văn An-1-BT-12", "Đinh Bộ Lĩnh-1-BT-26", "Đinh Bộ Lĩnh-2-BT-26", "Đinh Bộ Lĩnh-3-BT-26", "Đinh Bộ Lĩnh-4-BT-24", "Đinh Bộ Lĩnh-5-BT-24", "Đinh Bộ Lĩnh-6-BT-24", "Đinh Bộ Lĩnh-7-BT-24", "Đường số 12 Cư xá Chu Văn An-1-BT-24", "Đường số 3 CC Chu Văn An-1-BT-26", "Đường số 3 Cư xá Chu Văn An-1-BT-24", "Đường số 4 Cư xá Chu Văn An-1-BT-26", "Huỳnh Đình Hai-1-BT-24", "Huỳnh Đình Hai-2-BT-24", "Hẻm 123 Nguyễn Xí-1-BT-26", "Hẻm 125 Bùi Đình Túy-1-BT-24", "Hẻm 125 Bùi Đình Túy-2-BT-24", "Hẻm 160 Bùi Đình Túy-1-BT-12", "Hẻm 202 Nguyễn Xí-1-BT-26", "Hẻm 220 Nguyễn Xí-1-BT-26", "Hẻm 290 Nơ Trang Long-1-BT-12", "Hẻm 32/36 Bùi Đình Túy-1-BT-12", "Hẻm 334 Chu Văn An-1-BT-12", "Hẻm 356 Bạch Đằng-1-BT-14", "Hẻm 47 Bùi Đình Túy-1-BT-24", "Hẻm 625 Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 72 Bạch Đằng-1-BT-24", "Hẻm 76 Bạch Đằng-1-BT-24", "Hẻm 801/65 Xô Viết Nghệ Tĩnh-1-BT-26", "Hẻm 82 Đinh Bộ Lĩnh-1-BT-26", "KDC Bắc Đinh Bộ Lĩnh-1-BT-13", "Lê Quang Định-1-BT-14", "Lê Quang Định-2-BT-14", "Lê Quang Định-3-BT-11", "Nguyễn Huy Lượng-1-BT-14", "Nguyễn Thiện Thuật-1-BT-24", "Nguyễn Xí-2-BT-26", "Nguyễn Xí-3-BT-26", "Ngô Đức Kế-1-BT-12", "Ngô Đức Kế-2-BT-12", "Nơ Trang Long-3-BT-13", "Phan Bội Châu-1-BT-14", "Phan Châu Trinh-1-BT-12", "Phan Văn Trị-1-BT-12", "Phan Văn Trị-2-BT-12", "Phan Văn Trị-3-BT-11", "Quốc Lộ 13-1-BT-26", "Quốc Lộ 13-2-BT-26", "Trần Quý Cáp-1-BT-11", "Tầm Vu-1-BT-25"],
  "Bình Thới": ["Bình Thới 6", "Bình Thới 7", "Bình Thới Làng", "Đường số 2 Cư xá Bình Thới", "Đường số 3 Cư xá Bình Thới", "Đường số 5 Cư xá Bình Thới", "Đường số 6 Cư xá Bình Thới-1", "Đường số 6 Cư xá Bình Thới-2", "Đường số 7 Cư xá Bình Thới", "Đường số 7A Cư xá Bình Thới", "Đường số 9 Cư xá Bình Thới-1", "Đường số 9 Cư xá Bình Thới-2", "Dương Đình Nghệ-1", "Dương Đình Nghệ-2", "Dương Đình Nghệ-3", "Dương Đình Nghệ-4", "Hẻm 106 Lạc Long Quân", "Hẻm 152 Lạc Long Quân-1", "Hẻm 152 Lạc Long Quân-2", "Hẻm 161 Lạc Long Quân", "Hẻm 180 Minh Phụng-1", "Hẻm 180 Minh Phụng-2", "Hẻm 181 Bình Thới", "Hẻm 200 Thái Phiên", "Hẻm 236 Thái Phiên", "Hẻm 418 Minh Phụng-1", "Hẻm 418 Minh Phụng-2", "Hẻm 45 Ông Ích Khiêm", "Hẻm 76 Xóm Đất", "Kênh Tân Hóa Lò Gốm", "Lô E-F Cư xá Bình Thới", "Lạc Long Quân-1", "Lạc Long Quân-5", "Lạc Long Quân-6", "Lạc Long Quân-7", "Lạc Long Quân-8", "Lạc Long Quân-9", "Minh Phụng 10", "Minh Phụng 10 TC", "Minh Phụng 11", "Minh Phụng 8", "Minh Phụng 9", "Thái Phiên-1", "Thái Phiên-2", "Thái Phiên-3", "Thái Phiên-4", "Xóm Đất 1", "Xóm Đất 2", "Xóm Đất 3", "Xóm Đất 4"],
  "Bến Thành": ["Bùi Thị Xuân 1", "Bùi Viện 1", "Bùi Viện 2", "Bến xe Buýt Công Viên 23/9 (Khu B)-1", "Bến xe Buýt Công Viên 23/9 (Khu B)-2", "Calmette 1", "Cách Mạng Tháng 8 - 4", "Cách Mạng Tháng 8 -1", "Cách Mạng Tháng 8 -2", "Cách Mạng Tháng 8 -3", "Công Viên 23/9 (Khu A) -1", "Công Viên 23/9 (Khu A) -2", "Công Viên 23/9 (Khu A) -3", "Công Viên 23/9 (Khu B) -1", "Công Viên 23/9 (Khu B) -2", "Công Viên 23/9 (Khu B) -3", "Công Viên 23/9 (Khu B) -4", "Công Viên 23/9 (Khu B) -5", "Công viên Tao Đàn 1", "Công viên Tao Đàn 3", "Công viên Tao Đàn 4", "Cầu Calmette 1", "Cống Quỳnh 1", "Đỗ Quang Đẩu 1", "Huyền Trân Công Chúa 1", "Huỳnh Thúc Kháng 1", "Hàm Nghi 1", "Hàm Nghi 2", "Hàm Nghi 4", "Hẻm 306 Nguyễn Thị Minh Khai", "Ký Con 1", "Ký Con 2", "Lê Công Kiều 1", "Lê Lai 1", "Lê Lợi 1", "Lê Thánh Tôn 1", "Lê Thị Riêng 1", "Lý Tự Trọng 1", "Lý Tự Trọng 2", "Lương Hữu Khánh 1", "Nam Kỳ Khởi Nghĩa 8", "Nam Quốc Cang 1", "Nguyễn Công Trứ 1", "Nguyễn Cư Trinh 4", "Nguyễn Du 2", "Nguyễn Du 3", "Nguyễn Du 4", "Nguyễn Thái Bình 1", "Nguyễn Thái Bình 2", "Nguyễn Thái Bình 3", "Nguyễn Thái Bình 4", "Nguyễn Thái Học 1", "Nguyễn Thái Học 2", "Nguyễn Thái Học 3", "Nguyễn Thị Minh Khai 2", "Nguyễn Thị Minh Khai 4", "Nguyễn Thị Minh Khai 5", "Nguyễn Trung Trực 1", "Nguyễn Trung Trực 2", "Nguyễn Trung Trực 3", "Nguyễn Trãi 1", "Nguyễn Trãi 2", "Nguyễn Trãi 3", "Nguyễn Văn Tráng 1", "Phan Bội Châu 1", "Phan Chu Trinh 1", "Phó Đức Chính 1", "Phó Đức Chính 2", "Phạm Ngũ Lão 1", "Phạm Ngũ Lão 2", "Phạm Ngũ Lão 3", "Sương Nguyệt Ánh 1", "Thủ Khoa Huân 1", "Trương Định 1", "Trương Định 2", "Trần Hưng Đạo 1", "Trần Hưng Đạo 6", "Trần Hưng Đạo 7", "Trịnh Văn Cấn 1", "Tôn Thất Tùng 1", "Võ Văn Kiệt 1", "Yersin 1"],
  "Chánh Hưng": ["Ba Đình - 1", "Ba Đình - 2", "Ba Đình - 3", "Ba Đình - 4", "Ba Đình - 6", "Ba Đình - 7", "Ba Đình - 8", "Ba Đình - 9", "Ba Đình 481", "Bùi Điền - 1", "Bùi Điền - 2", "Chung cư Him Lam - Nam Khánh", "Chánh Hưng - 3A", "Chánh Hưng - 5A", "Châu Thị Hóa", "Công viên Tạ Quang Bửu", "Cư xá Chánh Hưng A", "Cư xá Hưng Phú", "Cầu Chánh Hưng - 1", "Cầu Chánh Hưng - 2", "Đào Cam Mộc", "Đông Hồ", "Đường số 1 KDC Rạch Hiệp Ân", "Đường số 102 Cao Lỗ", "Đường số 2 Chánh Hưng", "Đường số 2 Khu dân cư Chánh Hưng", "Đường Số 218 Cao Lỗ", "Đường số 270 Cao Lỗ", "Đường số 31 Chánh Hưng", "Đường Số 320 Khu dân cư Chánh Hưng", "Đường số 751 Tạ Quang Bửu - 1", "Đường số 751 Tạ Quang Bửu - 2", "Đường số 9 Cao Lỗ", "Đặng Chất", "Đỗ Ngọc Quang", "Dã Tượng", "Dương Bá Trạc - 1", "Dương Bá Trạc - 2", "Dương Bạch Mai", "Dương Quang Đông - 1", "Dương Quang Đông - 2", "Dạ Nam - 1", "Dạ Nam - 2", "Huỳnh Thị Phụng", "Hưng Phú - 10", "Hưng Phú - 11", "Hưng Phú - 2", "Hưng Phú - 3", "Hưng Phú - 4", "Hưng Phú - 5", "Hưng Phú - 6", "Hưng Phú - 7", "Hưng Phú - 8", "Hưng Phú - 9", "Hưng Phú -1", "Hẻm 109 Dương Bá Trạc", "Hẻm 121 Hưng Phú", "Hẻm 154 Âu Dương Lân", "Hẻm 157 Dương Bá Trạc - 1", "Hẻm 157 Dương Bá Trạc - 2", "Hẻm 288D Dương Bá Trạc", "Hẻm 290D Dương Bá Trạc", "Hẻm 35 Cao Lỗ", "Hẻm 47 Nguyễn Thị Tần", "Hẻm 527 Dương Bá Trạc", "Hồ Biểu Chánh", "Hồ Thành Biên", "Khu dân cư Phường 10 Nguyễn Duy - 1", "Khu dân cư Phường 10 Nguyễn Duy - 2", "Lê Quyên", "Lưu Quý Kỳ - 1", "Lưu Quý Kỳ - 2", "Nguyễn Duy - 1", "Nguyễn Duy - 2", "Nguyễn Duy - 3", "Nguyễn Duy - 4", "Nguyễn Duy - 5", "Nguyễn Duy - 6", "Nguyễn Thị Tần - 1", "Nguyễn Thị Tần - 2", "Nguyễn Thị Tần - 3", "Nguyễn Thị Tần - 4", "Phạm Hùng - 1", "Phạm Hùng - 2", "Phạm Nhữ Tăng", "Phạm Thế Hiển - 1", "Phạm Thế Hiển - 10", "Phạm Thế Hiển - 11", "Phạm Thế Hiển - 12", "Phạm Thế Hiển - 13", "Phạm Thế Hiển - 14", "Phạm Thế Hiển - 2", "Phạm Thế Hiển - 3", "Phạm Thế Hiển - 4", "Phạm Thế Hiển - 5", "Phạm Thế Hiển - 6", "Phạm Thế Hiển - 7", "Phạm Thế Hiển - 8", "Phạm Thế Hiển - 9", "Phồn Vinh - 3", "Rạch Ụ Cây - 2", "Trần Thị Ngôi", "Tám Danh - 1", "Tám Danh - 2", "Tám Danh - 3", "Tạ Quang Bửu - 1", "Tạ Quang Bửu - 1/1", "Tạ Quang Bửu - 1/2A", "Tạ Quang Bửu - 2", "Tạ Quang Bửu - 3", "Tạ Quang Bửu - 5", "Âu Dương Lân - 1", "Âu Dương Lân - 2", "Âu Dương Lân - 3", "Âu Dương Lân - 4", "Âu Dương Lân - 5", "Âu Dương Lân - 6", "Âu Dương Lân - 7"],
  "Chợ Lớn": ["An Điềm - 1", "An Điềm - 2", "Bến xe Chợ Lớn", "Châu Văn Liêm - 1", "Châu Văn Liêm - 2", "Châu Văn Liêm - 3", "Cầu Chà Và", "Đặng Thái Thân", "Đỗ Ngọc Thạnh - 1", "Đỗ Ngọc Thạnh - 2", "Dương Tử Giang", "Gia Phú", "Gò Công - 1", "Gò Công - 2", "Hà Tôn Quyền", "Hải Thượng Lãn Ông - 1", "Hải Thượng Lãn Ông - 2", "Hải Thượng Lãn Ông - 3", "Hải Thượng Lãn Ông - 4", "Hải Thượng Lãn Ông - 5", "Hải Thượng Lãn Ông - 6", "Hải Thượng Lãn Ông - 8", "Hải Thượng Lãn Ông - 9", "Hồng Bàng - 1", "Hồng Bàng - 10", "Hồng Bàng - 11", "Hồng Bàng - 2", "Hồng Bàng - 3", "Hồng Bàng - 4", "Hồng Bàng - 5", "Hồng Bàng - 6", "Hồng Bàng - 7", "Hồng Bàng - 8", "Hồng Bàng - 9", "Hữu Chí - 1", "Hữu Chí - 2", "Ký Hòa", "Lão Tử", "Lương Nhữ Học - 1", "Lương Nhữ Học - 2", "Mạc Cửu", "Nguyễn An Khương", "Nguyễn Chí Thanh - 10", "Nguyễn Chí Thanh - 4", "Nguyễn Chí Thanh - 6", "Nguyễn Kim", "Nguyễn Thi - 1", "Nguyễn Thi - 2", "Nguyễn Trãi - 10", "Nguyễn Trãi - 9", "Nguyễn Án", "Ngô Quyền - 1", "Ngô Quyền - 2", "Phan Phú Tiên - 1", "Phan Phú Tiên - 2", "Phó Cơ Điều", "Phù Đổng Thiên Vương", "Phùng Hưng", "Phú Giáo", "Phú Hữu - 1", "Phú Hữu - 2", "Trần Chánh Chiếu", "Trần Hưng Đạo - 28", "Trần Hưng Đạo - 29", "Trần Hưng Đạo - 30", "Trần Hưng Đạo - 31", "Trần Hưng Đạo - 32", "Trần Hưng Đạo - 33", "Trần Hưng Đạo - 34", "Tân Hưng - 1", "Tân Hưng - 2", "Tân Hưng - 3", "Tân Thành", "Tăng Bạt Hổ", "Tạ Uyên - 1", "Tạ Uyên - 2", "Tản Đà - 1", "Tản Đà - 2", "Võ Văn Kiệt - 8", "Vạn Tượng - 1", "Vạn Tượng - 2", "Xóm Chỉ", "Xóm Vôi - 1", "Xóm Vôi - 2"],
  "Chợ Quán": ["An Dương Vương - 2", "An Dương Vương - 3", "An Dương Vương - 4", "An Dương Vương - 5", "An Dương Vương - 6", "Cao Đạt - 3", "Cao Su - 3", "Cao Su - 4", "Cao Su - 5", "Chung cư 109 Nguyễn Biểu", "Công Viên Âu Lạc", "Cầu Chữ Y", "EMG - 2", "EMG - 4", "Hẻm 136 Trần Phú", "Kim Khí - 1", "Lê Hồng Phong - 6", "Lê Hồng Phong - 7", "Lê Hồng Phong - 8", "Mẫn Đạt", "Nguyễn Biểu", "Nguyễn Biểu - 2", "Nguyễn Trãi - 6", "Nguyễn Văn Cừ - 3", "Nguyễn Văn Cừ - 4", "Nguyễn Văn Cừ 1", "Trần Bình Trọng - 3", "Trần Bình Trọng - 4", "Trần Bình Trọng - 5", "Trần Hưng Đạo - 11", "Trần Hưng Đạo - 12", "Trần Hưng Đạo - 13", "Trần Hưng Đạo - 14", "Trần Hưng Đạo - 15", "Trần Hưng Đạo - 16", "Trần Hưng Đạo - 17", "Trần Phú", "Trần Phú - 7", "Trần Phú - 8", "Võ Văn Kiệt - 3"],
  "Cầu Kiệu": ["Chung Cư Rạch Miễu - 1 - PN - 7", "Cô Bắc -1- PN - 1", "Cô Giang - 2 - PN - 1", "Cô Giang -1- PN - 2", "Cù Lao - 2- PN - 2", "Cù Lao -1- PN - 2", "Cầm Bá Thước - 1 - PN - 7", "Cầu Kiệu -1- PN - 2", "Duy Tân - 2 - PN - 15", "Duy Tân - 3 - PN - 15", "Đoàn Thị Điểm - 1- PN - 1", "Đoàn Thị Điểm - 2 - PN - 1", "Đoàn Thị Điểm - 3 - PN - 1", "Hoa Cau -1- PN - 7", "Hoa Cau -2 - PN - 7", "Hoa Hồng - 1- PN - 2", "Hoa Phượng - 1 - PN - 2", "Hoa Phượng - 2 - PN - 2", "Hoa Sứ -1- PN - 2", "Hoa Sữa - 1 - PN - 7", "Hoa Thị - 1 - PN - 7", "Hoàng Văn Thụ - 4 - PN - 15", "Hẻm 30 Phùng Văn Cung - 1 - PN - 7", "Hẻm 33 Trần Khắc Chân - 1- PN - 15", "Hẻm 38 Nguyễn Văn Trỗi - 1 - PN - 15", "Hẻm 71 Nguyễn Công Hoan - 1 - PN - 7", "Nguyễn Công Hoan - 1- PN - 7", "Nguyễn Công Hoan - 2- PN - 7", "Nguyễn Đình Chính - 1 - PN - 15", "Nguyễn Đình Chính - 2 - PN - 15", "Nguyễn Đình Chính - 3 - PN - 15", "Nguyễn Đình Chính - 4 - PN - 15", "Nguyễn Lâm-2-BT-3", "Nguyễn Trọng Tuyển - 5 - PN - 8", "Nguyễn Trọng Tuyển - 7 - PN - 15", "Nguyễn Văn Trỗi - 3 - PN - 15", "Nhiêu Tứ - 1 - PN - 7", "Nhà thi đấu TT Rạch Miễu - 1-PN-2", "Phan Đình Phùng -2 - PN - 15", "Phan Đăng Lưu - 2 - PN - 5", "Phan Tây Hồ - 1 - PN- 7", "Phan Xích Long - 1- PN - 1", "Phan Xích Long - 2 - PN - 1", "Phan Xích Long - 3 - PN - 7", "Phan Xích Long - 4 - PN - 2", "Phùng Văn Cung - 3 - PN - 2", "Phùng Văn Cung - 4 - PN - 2", "Tiểu Đảo Nguyễn Công Hoan -1- PN - 2", "Trường Sa - 5 - PN- 2", "Trường Sa - 6 - PN- 2", "Trần Huy Liệu - 1- PN - 8", "Trần Huy Liệu - 3- PN - 8", "Trần Kế Xương -1- PN - 7"],
  "Cầu Ông Lãnh": ["Cô Bắc 1", "Cô Giang 1", "Cô Giang 2", "Cống Quỳnh 2", "Đề Thám 1", "Hẻm 189B Cống Quỳnh 1", "Hẻm 189C Cống Quỳnh", "Hẻm 212 B Nguyễn Trãi 1", "Hẻm 212 B Nguyễn Trãi 2", "Hẻm 215B Nguyễn Trãi", "Hẻm 286 Trần Hưng Đạo 1", "Hẻm 345 Trần Hưng Đạo", "Hẻm 518 Võ Văn Kiệt", "Hồ Hảo Hớn 1", "Nguyễn Cư Trinh 1", "Nguyễn Cư Trinh 2", "Nguyễn Cư Trinh 3", "Nguyễn Cảnh Chân 1", "Nguyễn Khắc Nhu 1", "Nguyễn Thái Học 4", "Nguyễn Thị Minh Khai 1", "Nguyễn Trãi 4", "Nguyễn Trãi 5", "Nguyễn Trãi 6", "Nguyễn Văn Cừ - 5", "Nguyễn Văn Cừ 2", "Trần Đình Xu 1", "Trần Hưng Đạo 10", "Trần Hưng Đạo 2", "Trần Hưng Đạo 3", "Trần Hưng Đạo 4", "Trần Hưng Đạo 5", "Trần Hưng Đạo 8", "Trần Hưng Đạo 9", "Võ Văn Kiệt 2"],
  "Diên Hồng": ["Ba Tháng Hai-6", "Ba Tháng Hai-7", "Ba Tháng Hai-8", "Bà Hạt-3", "Bà Hạt-4", "Chung cư Nguyễn Tri Phương", "Chung cư Trần Văn Kiểu", "Cư xá Đồng Tiến-1", "Cư xá Đồng Tiến-2", "Cư xá Đồng Tiến-3", "Cư xá Đồng Tiến-4", "Đào Duy Từ", "Hòa Hảo-4", "Hòa Hảo-5", "Hẻm 138 Ngô Quyền", "Hẻm 224 Lý Thường Kiệt", "Hẻm 232 Lý Thường Kiệt", "Hẻm 284 Lý Thường Kiệt", "Hẻm 3 Thành Thái", "Hẻm 334 Lý Thường Kiệt", "Hẻm 354 Lý Thường Kiệt", "Hẻm 43 Thành Thái", "Hẻm 451 Tô Hiến Thành-1", "Hẻm 451 Tô Hiến Thành-2", "Hẻm 495 Tô Hiến Thành", "Hẻm 506 Ba Tháng Hai", "Hẻm 51 Thành Thái", "Hẻm 606 Ba Tháng Hai-1", "Hẻm 606 Ba Tháng Hai-2", "Hẻm 666 Ba Tháng Hai", "Hẻm 7A+7B Thành Thái-1", "Hẻm 7A+7B Thành Thái-2", "Hẻm 7A+7B Thành Thái-3", "Lý Thường Kiệt-2", "Lý Thường Kiệt-4", "Lý Thường Kiệt-5", "Nguyễn Chí Thanh-5", "Nguyễn Lâm-1", "Nguyễn Lâm-2", "Nguyễn Ngọc Lộc 1", "Nguyễn Tri Phương-2", "Nguyễn Tri Phương-4", "Ngô Quyền-3", "Ngô Quyền-4", "Ngô Quyền-5", "Ngô Quyền-6", "Nhật Tảo-1", "Nhật Tảo-2", "Thành Thái ND-1", "Tiểu La-3", "Tiểu La-4", "Tân Phước-1", "Tân Phước-2", "Tô Hiến Thành-3", "Tô Hiến Thành-4", "Vĩnh Viễn-6", "Vĩnh Viễn-7", "Vĩnh Viễn-8", "Vĩnh Viễn-9"],
  "Đức Nhuận": ["Bùi Văn Thêm -1- PN - 9", "CC 675 Nguyễn Kiệm - 1- PN - 9", "CC Hồ Văn Huê -1- PN - 9", "Đào Duy Anh - 1 - PN - 9", "Đào Duy Anh - 2 - PN - 9", "Đặng Văn Sâm -1- PN - 9", "Dọc Đường Ray F9 -1- PN - 9", "Hoàng Văn Thụ - 1 - PN - 8", "Hoàng Văn Thụ - 3 - PN - 8", "Hẻm 108 Đào Duy Anh - 1 - PN - 9", "Hẻm 12 Đào Duy Anh - 1 - PN - 9", "Hẻm 120 Thích Quảng Đức - 1- PN- 5", "Hẻm 120 Thích Quảng Đức - 2 - PN- 5", "Hẻm 134 Đào Duy Anh - 1 - PN - 9", "Hẻm 166 Đào Duy Anh - 1 - PN - 9", "Hẻm 166 Thích Quảng Đức-1-PN-4", "Hẻm 440 Nguyễn Kiệm -1- PN - 3", "Hẻm 486 Phan Xích Long -1- PN - 3", "Hẻm 54 Đào Duy Anh - 1 - PN - 9", "Hẻm 750 Nguyễn Kiệm -1- PN - 4", "Hẻm 86 Thích Quảng Đức- 1- PN - 4", "Hẻm 88 Đào Duy Anh - 1 - PN - 9", "Hồ Văn Huê - 1 - PN - 9", "Hồ Văn Huê - 2 - PN - 9", "Hồng Hà - 1 -PN - 9", "KNO 321 Đào Duy Anh -1- PN - 9", "Lê Tự Tài - 1 - PN - 4", "Lê Tự Tài - 2 - PN - 4", "Lê Tự Tài - 3 - PN - 4", "Nguyễn Đình Chiểu - 1 -PN- 3", "Nguyễn Đình Chiểu - 2 - PN- 3", "Nguyễn Kiệm - 1- PN - 3", "Nguyễn Kiệm - 2 - PN - 4", "Phan Đăng Lưu - 1 - PN - 2", "Phan Xích Long - 5 - PN - 3", "Phùng Văn Cung - 1- PN - 4", "Phùng Văn Cung - 2- PN - 4", "Thích Quảng Đức - 1- PN - 5", "Thích Quảng Đức - 2 - PN - 4", "Trần Khắc Chân - 2 - PN - 9"],
  "Gia Định": ["Bùi Hữu Nghĩa-1-BT-1", "Bùi Hữu Nghĩa-2-BT-1", "Bạch Đằng-1-BT-2", "Bạch Đằng-2-BT-15", "Bạch Đằng-3-BT-15", "CC Miếu Nổi-1-BT-3", "CC Miếu Nổi-2-BT-3", "Chân cầu Bông-1-BT-3", "Cư xá Phan Đăng Lưu-1-BT-3", "Đinh Bộ Lĩnh-8-BT-15", "Điện Biên Phủ-13-BT-17", "Điện Biên Phủ-14-BT-15", "Điện Biên Phủ-15-BT-17", "Điện Biên Phủ-16-BT-15", "H62 Phan Văn Hân-1-BT-17", "Hoàng Hoa Thám-1-BT-6", "Hoàng Hoa Thám-2-BT-6", "Hẻm 1 Điện Biên Phủ-1-BT-15", "Hẻm 128 Lê Văn Duyệt-1-BT-1", "Hẻm 158 Nguyễn Văn Đậu-1-BT-7", "Hẻm 193 Điện Biên Phủ-1-BT-15", "Hẻm 195 Điện Biên Phủ-1-BT-15", "Hẻm 217 Xô Viết Nghệ Tĩnh-1-BT-17", "Hẻm 227 Điện Biên Phủ-1-BT-15", "Hẻm 23 Lê Văn Duyệt-1-BT-3", "Hẻm 23 Nơ Trang Long-1-BT-7", "Hẻm 237 Phan Văn Hân-1-BT-17", "Hẻm 26 Lê Văn Duyệt-1-BT-1", "Hẻm 27 Điện Biên Phủ-1-BT-15", "Hẻm 280 Bùi Hữu Nghĩa-1-BT-2", "Hẻm 280 Bùi Hữu Nghĩa-2-BT-2", "Hẻm 282 Bùi Hữu Nghĩa-1-BT-2", "Hẻm 372 Điện Biên Phủ-1-BT-17", "Hẻm 46 Nguyễn Cửu Vân-1-BT-17", "Hẻm 5 Nơ Trang Long-1-BT-7", "Hẻm 5/101 Nơ Trang Long-1-BT-7", "Hẻm 54 Vũ Huy Tấn-1-BT-3", "Hẻm 57 Điện Biên Phủ-1-BT-15", "Hẻm 71 Điện Biên Phủ-1-BT-15", "Hẻm 82 Bùi Hữu Nghĩa-2-BT-1", "Hẻm 82 Lê Văn Duyệt-1-BT-1", "Lam Sơn - 1 - PN - 5", "Lê Trực-1-BT-7", "Lê Trực-2-BT-7", "Lê Văn Duyệt-1-BT-3", "Lê Văn Duyệt-2-BT-1", "Nguyễn Công Hoan-3-BT-3", "Nguyễn Cửu Vân-1-BT-17", "Nguyễn Cửu Vân-2-BT-17", "Nguyễn Cửu Vân-3-BT-17", "Nguyễn Duy-1-BT-3", "Nguyễn Huy Tưởng-1-BT-6", "Nguyễn Lâm-1-BT-3", "Nguyễn Văn Đậu-2-BT-6", "Nơ Trang Long-4-BT-12", "Phan Chu Trinh-1-BT-2", "Phan Đăng Lưu-3-BT-3", "Phan Đăng Lưu-4-BT-6", "Phan Văn Hân-1-BT-17", "Phan Văn Hân-2-BT-17", "Phó Đức Chính-1-BT-1", "TĐK Hầm 2-1-BT-15", "Trường Sa-3-BT-17", "Trường Sa-4-BT-15", "Trần Văn Khê-1-BT-17", "Trịnh Hoài Đức-1-BT-1", "Vòng Xoay Hàng Xanh-1-BT-17", "Vòng Xoay Hàng Xanh-4-BT-25", "Vòng Xoay Hàng Xanh-5-BT-15", "Võ Trường Toản-1-BT-2", "Vũ Huy Tấn-1-BT-3", "Vũ Tùng-1-BT-1", "Vũ Tùng-2-BT-2", "Vũ Tùng-3-BT-2", "Vạn Kiếp-1-BT-3", "Vạn Kiếp-2-BT-3", "Yên Đổ-1-BT-2"],
  "Hòa Bình": ["Bình Dương Thị Xã", "Bình Thới 2", "Chung cư Lạc Long Quân-1", "Chung cư Lạc Long Quân-2", "Chung cư Lạc Long Quân-3", "Cư xá Trịnh Đình Trọng", "Hòa Bình-1", "Hòa Bình-2", "Hẻm 100 Bình Thới-1", "Hẻm 100 Bình Thới-2", "Hẻm 102 Bình Thới-1", "Hẻm 102 Bình Thới-2", "Hẻm 127 Âu Cơ-1", "Hẻm 127 Âu Cơ-2", "Hẻm 32 Ông Ích Khiêm-1", "Hẻm 32 Ông Ích Khiêm-2", "Hẻm 341 Lạc Long Quân-1", "Hẻm 341 Lạc Long Quân-2", "Hẻm 341 Lạc Long Quân-3", "Hẻm 37 Trịnh Đình Trọng", "Hẻm 423 Lạc Long Quân-1", "Hẻm 423 Lạc Long Quân-2", "Hẻm 423 Lạc Long Quân-3", "Hẻm 49 Âu Cơ", "Hẻm 568 Lạc Long Quân", "Hẻm 79 Âu Cơ-1", "Hẻm 79 Âu Cơ-2", "Hẻm 86 Ông Ích Khiêm", "Hẻm 94 Hoà Bình-1", "Hẻm 94 Hoà Bình-2", "Hẻm Cư xá Phú Thọ Hoà-1", "Hẻm Cư xá Phú Thọ Hoà-2", "Khu Chợ Phú Bình-1", "Khu Chợ Phú Bình-2", "Khu Chợ Phú Bình-3", "Khu Chợ Phú Bình-4", "Lạc Long Quân 312/A1", "Lạc Long Quân 312/A2", "Lạc Long Quân-10", "Lạc Long Quân-11", "Lạc Long Quân-12", "Lạc Long Quân-13", "Nguyễn Văn Phú 1", "Trịnh Đình Trọng-2", "Tống Văn Trân", "Vòng xoay Lạc Long Quân - Hoà Bình", "Âu Cơ-1", "Âu Cơ-2", "Âu Cơ-3", "Âu Cơ-4", "Ông Ích Khiêm 2", "Ông Ích Khiêm 3", "Ông Ích Khiêm 4"],
  "Hòa Hưng": ["Ba Tháng Hai-4", "Ba Tháng Hai-5", "Ba Vì", "Cao Thắng 1", "Công Binh", "Công Binh TC", "Cửu Long-1", "Cửu Long-2", "Đồng Nai 1", "Dương Quang Trung 1", "Dương Quang Trung 2", "Hoàng Dư Khương", "Hòa Hưng", "Hẻm 134 Thành Thái", "Hẻm 14 Hoàng Dư Khương", "Hẻm 158 Hòa Hưng", "Hẻm 163 Tô Hiến Thành", "Hẻm 285 CMT8", "Hẻm 339 Tô Hiến Thành", "Hẻm 392 Cao Thắng", "Hẻm 419 Cách Mạng Tháng 8", "Hẻm 436A Ba Tháng Hai", "Hẻm 436B Ba Tháng Hai", "Hẻm 449 Sư Vạn Hạnh", "Hẻm 463 CMT8 1", "Hẻm 68 Đồng Nai-1", "Hẻm 68 Đồng Nai-2", "Hẻm 814 Sư Vạn Hạnh", "Hẻm 83 Hòa Hưng", "Hẻm Cao Thắng ND", "Hồ Bá Kiện-1", "Hồ Bá Kiện-2", "Khu Chung cư hẻm 830 Sư Vạn Hạnh", "Khu nhà ở K34 Trần Thiện Chánh", "Khu nhà ở Lê Thị Riêng-1", "Khu nhà ở Lê Thị Riêng-2", "KN 541 Sư Vạn Hạnh", "KNỞ P12 Trần Thiện Chánh", "Lê Hồng Phong-1", "Lộ 50 Hòa Hưng", "Nguyễn Giản Thanh 1", "Sư Vạn Hạnh ND 1", "Sỹ Quan 3", "Tam Đảo", "Thành Thái ND-2", "Thành Thái-1", "Thành Thái-2", "Trần Thiện Chánh-1", "Trần Thiện Chánh-2", "Tô Hiến Thành-1", "Tô Hiến Thành-2"],
  "Hạnh Thông": ["Trần Bình Trọng-2-GV-1"],
  "Minh Phụng": ["Ba Tháng Hai-11", "Ba Tháng Hai-12", "Ba Tháng Hai-13", "Ba Tháng Hai-14", "Ba Tháng Hai-9", "Chợ Thiếc 1", "Chợ Thiếc 1 TC", "Chợ Thiếc 2", "Công Trừng 3", "Diên Nghệ 1", "Hoàng Quân 2", "Hàn Hải Nguyên-1", "Hàn Hải Nguyên-2", "Hàn Hải Nguyên-3", "Hàn Hải Nguyên-5", "Hàn Hải Nguyên-6", "Hàn Hải Nguyên-7", "Hàn Hải Nguyên-8", "Hàn Hải Nguyên-9", "Hẻm 1352 Ba Tháng Hai", "Hẻm 151 Lạc Long Quân", "Hẻm 185 Lý Thường Kiệt", "Hẻm 269 Nguyễn Thị Nhỏ", "Hẻm 323 Minh Phụng", "Hẻm 36B Đường 762 Hồng Bàng", "Hẻm 702 Hồng Bàng", "Hẻm 8 Tân Hóa-1", "Hẻm 8 Tân Hóa-2", "Hồng Bàng-12", "Hồng Bàng-13", "Hồng Bàng-14", "Khánh Vân 3", "Lê Đại Hành-1", "Lê Đại Hành-2", "Lò Siêu 45", "Lý Nam Đế", "Lý Thường Kiệt-1", "Lạc Long Quân-2", "Lạc Long Quân-3", "Lạc Long Quân-4", "Minh Phụng 7", "Nam Đế 2 TC", "Nguyễn Chí Thanh - 11", "Nguyễn Chí Thanh - 8", "Nguyễn Chí Thanh 12", "Nguyễn Chí Thanh 9", "Nguyễn Chí Thanh Nối Dài-1", "Nguyễn Chí Thanh Nối Dài-2", "Nguyễn Chí Thanh-7", "Nguyễn Thị Nhỏ", "Phan Xích Long", "Phùng Bích TC", "Phú Thọ 1", "Phú Thọ 2A", "Phú Thọ 3", "Quan Âm TC", "Trần Quý 1", "Trần Quý 1 TC", "Tân Khai-1", "Tân Khai-2", "Tân Khai-3", "Tân Thành Nối Dài-1", "Tân Thành Nối Dài-2", "Vĩnh Viễn-10", "Ông Tích 1", "Ông Tích 2"],
  "Nhiêu Lộc": ["Bà Huyện Thanh Quan 1", "Chung Cư Phường 13 Q3", "Chung Cư Phường 9 Q3", "Cách Mạng Tháng 8 -12", "Cách Mạng Tháng 8 -16", "Cách Mạng Tháng 8 -18", "Cách Mạng Tháng 8 -19", "Cầu Lê Văn Sỹ 2", "Đỗ Thị Lời 1", "Đỗ Thị Lời 2", "Hoàng Sa 8", "Hoàng Sa 9", "Hẻm 159 CMT8", "Hẻm 220 Lê Văn Sỹ", "Hẻm 80 Bà Huyện Thanh Quan", "Kỳ Đồng 1", "Lê Văn Sỹ 1", "Lê Văn Sỹ 2", "Lê Văn Sỹ 3", "Lê Văn Sỹ 4", "Nguyễn Phúc Nguyên 1", "Nguyễn Phúc Nguyên 2", "Nguyễn Thông 1", "Trương Định 5", "Trường Sa 10", "Trường Sa 8", "Trường Sa 9", "Trần Quang Diệu 1", "Trần Quang Diệu 2", "Trần Văn Đang 1", "Trần Văn Đang 2", "Trần Văn Đang 3", "Trần Văn Đang 4", "Vòng Xoay Dân Chủ 1"],
  "Phú Định": ["An Dương Vương - 1", "An Dương Vương - 2", "An Dương Vương - 3", "Bình Đông - 1", "Bình Đông - 11", "Bình Đông - 13", "Bình Đông - 14", "Bình Đông - 15", "Bình Đông - 16", "Bình Đông - 17", "Bình Đông - 18", "Bình Đông - 2", "Bình Đông - 3", "Bình Đông - 4", "Bình Đông - 7", "Bình Đông - 8", "Bùi Huy Bích - 1", "Bùi Huy Bích - 2", "Bờ Kè  Nguyễn Sĩ Cố", "Bờ Kè Bình Đông 1", "Bờ Kè Bình Đông 2", "Bờ Kè Bình Đông 3", "Bờ Kè Bình Đức", "Bờ Kè Bùi Huy Bích", "Bờ Kè Hoàng Sĩ Khải", "Bờ Kè Mễ Cốc", "Bờ Kè Nguyễn Nhược Thị", "Bờ Kè Ngô Sĩ Liên", "Bờ Kè Phú Định 1", "Bờ Kè Phú Định 2", "CVP15Q8", "Đinh Hòa", "Đường số 1 Phạm Thế Hiển", "Đường vào Cảng Phú Định", "Hoài Thanh - 1", "Hoài Thanh - 2", "Hoài Thanh - 3", "Hoài Thanh - 4", "Hoàng Ngân - 1", "Hoàng Ngân - 2", "Hoàng Ngân - 3", "Hương Lộ - 5", "Hẻm 150 Phú Định", "Hẻm 172 An Dương Vương - 1", "Hẻm 172 An Dương Vương - 2", "Hẻm 172 An Dương Vương - 3", "Hẻm 172 An Dương Vương - 4", "Hẻm 20 Mễ Cốc", "Hẻm 289 Bình Đông", "Hẻm 38 Nguyễn Ngọc Cung", "Hẻm 55 Nguyễn Chế Nghĩa", "Khu dân cư An Dương Vương - 1", "Khu dân cư An Dương Vương - 2", "Khu dân cư Nhật Minh", "Khu TĐC Cảng Phú Định", "Lý Đạo Thành", "Lưu Hữu Phước - 1", "Lưu Hữu Phước - 2", "Lưu Hữu Phước - 3", "Lưu Hữu Phước - 4", "Lưu Hữu Phước - 5", "Lưu Hữu Phước - 6", "Lương Văn Can", "Mai Hắc Đế", "Mã Hý - 2", "Mạc Vân", "Mễ Cốc - 1", "Mễ Cốc - 2", "Mễ Cốc - 3", "Mễ Cốc - 4", "Mễ Cốc - 5", "Nguyễn Chế Nghĩa", "Nguyễn Duy - 10", "Nguyễn Duy - 7", "Nguyễn Duy - 8", "Nguyễn Duy - 9", "Nguyễn Ngọc Cung - 1", "Nguyễn Ngọc Cung - 2", "Nguyễn Nhược Thị", "Nguyễn Quyền", "Nguyễn Sĩ Cố", "Nguyễn Văn Của", "Phú Định - 1", "Phú Định - 2", "Phú Định - 3", "Phú Định - 4", "Phú Định - 5", "Phú Định - 6", "Phú Định - 7", "Phạm Đức Sơn - 1", "Phạm Đức Sơn - 2", "Phạm Đức Sơn - 3", "Rạch Cát", "Rạch Ụ Cây - 1", "Trương Đình Hội - 1", "Trương Đình Hội - 2", "Trần Nguyên Hãn", "Tuy Lý Vương", "Tùng Thiện Vương - 1", "Tùng Thiện Vương - 2", "Tùng Thiện Vương - 3", "Tùng Thiện Vương - 4", "Tùng Thiện Vương - 5", "Tùng Thiện Vương - 6", "Tùng Thiện Vương - 7", "Tùng Thiện Vương - 8", "Việt Phát - 2", "Vĩnh Nam", "Xóm Củi - 1", "Ưu Long"],
  "Phú Nhuận": ["151 Huỳnh Văn Bánh - 1 - PN - 12", "Cao Thắng - 1- PN- 17", "CC 44 Đặng Văn Ngữ - 1 - PN- 10", "Duy Tân - 1- PN - 15", "Đào Duy Từ - 1 - PN - 17", "Đặng Văn Ngữ - 1- PN - 10", "Đặng Văn Ngữ - 2 - PN - 14", "Đặng Văn Ngữ - 3 - PN - 14", "Đặng Văn Ngữ - 4 - PN - 14", "Dọc Đường Ray F10 -2- PN - 10", "Dọc Đường Ray F10 -3- PN - 10", "Dọc Đường Ray F13 - 4 - PN - 13", "Dọc Đường Ray F13- 5 - PN - 13", "Hoàng Diệu - 1- PN - 10", "Hoàng Diệu - 2 - PN - 10", "Hoàng Văn Thụ - 2 - PN - 9", "Huỳnh Văn Bánh - 10 - PN - 10", "Huỳnh Văn Bánh - 11 - PN - 14", "Huỳnh Văn Bánh - 12 - PN - 14", "Huỳnh Văn Bánh - 13 - PN - 14", "Huỳnh Văn Bánh - 3 - PN - 17", "Huỳnh Văn Bánh - 4 - PN - 12", "Huỳnh Văn Bánh - 6 - PN - 11", "Huỳnh Văn Bánh - 7 - PN - 11", "Huỳnh Văn Bánh - 8 - PN - 11", "Huỳnh Văn Bánh - 9 - PN - 11", "Hẻm 184 Lê Văn Sỹ -1- PN - 10", "Hẻm 211 Hoàng Văn Thụ - 1 - PN - 8", "Hẻm 489 Huỳnh Văn Bánh -1- PN - 13", "Hẻm 525 Huỳnh Văn Bánh -1- PN - 13", "Hồ Biểu Chánh - 1 - PN - 11", "Hồ Biểu Chánh -2- PN - 11", "Hồ Biểu Chánh -3- PN - 12", "Lê Quý Đôn -1- PN - 11", "Nguyễn Đình Chính - 5 - PN - 8", "Nguyễn Đình Chính - 6 - PN - 11", "Nguyễn Đình Chính - 7 - PN - 11", "Nguyễn Đình Chính - 8 - PN - 11", "Nguyễn Thị Huỳnh -1- PN - 8", "Nguyễn Trọng Tuyển - 2 - PN - 8", "Nguyễn Trọng Tuyển - 3 - PN - 8", "Nguyễn Trọng Tuyển - 4 - PN - 8", "Nguyễn Trọng Tuyển - 6 - PN - 8", "Nguyễn Trọng Tuyển -1- PN - 8", "Nguyễn Văn Trỗi - 1-PN - 17", "Nguyễn Văn Trỗi - 2 - PN - 17", "Nguyễn Văn Trỗi - 4 - PN - 8", "Nguyễn Văn Trỗi - 5 - PN - 10", "Nguyễn Văn Trỗi - 6 - PN - 12", "Ngô Thời Nhiệm -1- PN - 17", "Phan Đình Phùng - 1 - PN - 1", "Trương Quốc Dung - 1 - PN - 10", "Trương Quốc Dung - 2 - PN", "Trường Sa - 11 - PN- 14", "Trường Sa - 7 - PN- 2", "Trần Cao Vân - 1 - PN - 12", "Trần Huy Liệu - 2- PN - 8", "Trần Huy Liệu - 4 - PN - 15", "Trần Huy Liệu - 7 - PN - 12", "Trần Hữu Trang - 2 - PN - 11", "Trần Hữu Trang - 3 - PN - 11", "Trần Hữu Trang-1- PN - 10"],
  "Phú Thọ": ["Ba Tháng Hai-10", "Bình Thới 4", "Cao Ốc Thuận Việt", "Chung Cư 319/1", "Chung Cư 319/2", "Chung cư Trường Đua A", "Chung cư Trường Đua B", "Đường 281 Lý Thường Kiệt-1", "Đường 281 Lý Thường Kiệt-2", "Đường 281 Lý Thường Kiệt-3", "Đường 299 Lý Thường Kiệt", "Đường Số 1 Cư xá Lữ Gia-1", "Đường Số 1 Cư xá Lữ Gia-2", "Đường số 52 Cư xá Lữ Gia-1", "Đường Số 52 Cư xá Lữ Gia-2", "Đường số 6 Cư xá Bình Thới-3", "Đội Cung", "Giếng Đại Hành TC", "Huyện Toại", "Hẻm 349 Lê Đại Hành", "Hẻm 351 Lê Đại Hành-1", "Hẻm 351 Lê Đại Hành-2", "Hẻm 377 Lê Đại Hành", "Lãnh Binh Thăng 4 TC 3", "Lãnh Binh Thăng-1", "Lãnh Binh Thăng-2", "Lãnh Binh Thăng-3", "Lãnh Binh Thăng-4", "Lãnh Binh Thăng-5", "Lãnh Binh Thăng-6", "Lê Đại Hành-3", "Lê Đại Hành-4", "Lê Đại Hành-5", "Lê Thị Bạch Cát-1", "Lê Thị Bạch Cát-2", "Lê Thị Bạch Cát-3", "Lò Siêu 2", "Lò Siêu 2 TC", "Lò Siêu TC 3", "Lý Thường Kiệt-3", "Lý Thường Kiệt-6", "Lý Thường Kiệt-7", "Lý Thường Kiệt-8", "Lữ Gia", "Lữ Gia 3", "Lữ Gia 4", "Lữ Gia 6", "Lữ Gia 7", "Quân Sự", "Sân Thể Thao Phú Thọ", "Thất Hiệp 1/1", "Tuệ Tĩnh", "Tuệ Tĩnh 204", "Tôn Thất Hiệp-1", "Tôn Thất Hiệp-2", "Tôn Thất Hiệp-3", "Tổng Lung"],
  "Sài Gòn": ["Alexandre De Rhodes 1", "Cao Bá Quát 1", "Chu Mạnh Trinh 1", "Chung Cư Nhiêu Lộc 1", "Chung Cư Nhiêu Lộc 2", "Công Trường Mê Linh 1", "Công Viên 30/4 -1", "Công Viên 30/4 -2", "Công Viên 30/4 -3", "Công Xã Paris 1", "Công Xã Paris 2", "Cầu Ba Son", "Đinh Tiên Hoàng 1", "Đinh Tiên Hoàng 2", "Đông Du 1", "Đông Du 2", "Đồng Khởi 1", "Hai Bà Trưng 1", "Hai Bà Trưng 2", "Hai Bà Trưng 3", "Hoàng Sa 1", "Huỳnh Thúc Kháng 2", "Huỳnh Thúc Kháng 3", "Hàm Nghi 3", "Hàn Thuyên 1", "Hải Triều 1", "Hẻm 18 Bis Nguyễn Thị Minh Khai 1", "Hẻm 5 Nguyễn Đình Chiểu -1", "Hồ Huấn Nghiệp 1", "Hồ Tùng Mậu 1", "Hồ Tùng Mậu 2", "Khuôn Viên Uỷ Ban Nhân Dân TP 1", "Lê Duẩn 1", "Lê Duẩn 2", "Lê Thánh Tôn 2", "Lê Thánh Tôn 3", "Lê Thánh Tôn 4", "Lê Thánh Tôn 5", "Lê Thánh Tôn 6", "Lý Tự Trọng 3", "Mạc Đỉnh Chi 1", "Mạc Thị Bưởi 1", "Mạc Thị Bưởi 2", "Nam Kỳ Khởi Nghĩa 10", "Nam Kỳ Khởi Nghĩa 7", "Nam Kỳ Khởi Nghĩa 9", "Nguyễn Bỉnh Khiêm 1", "Nguyễn Bỉnh Khiêm 2", "Nguyễn Bỉnh Khiêm 3", "Nguyễn Du 1", "Nguyễn Đình Chiểu 2", "Nguyễn Huệ 1", "Nguyễn Siêu 1", "Nguyễn Thị Minh Khai 10", "Nguyễn Thị Minh Khai 11", "Nguyễn Thị Minh Khai 12", "Nguyễn Thị Minh Khai 8", "Nguyễn Thị Minh Khai 9", "Nguyễn Trung Ngạn 1", "Nguyễn Văn Bình 1", "Ngô Đức Kế 1", "Ngô Đức Kế 2", "Ngô Văn Năm 1", "Pasteur 1", "Pasteur 2", "Pasteur 3", "Pasteur 4", "Pasteur 5", "Phùng Khắc Khoan 1", "Thi Sách 1", "Thái Văn Lung 1", "Tôn Đức Thắng 1", "Tôn Đức Thắng 2", "Tôn Đức Thắng 3", "Tôn Đức Thắng 4", "Tôn Đức Thắng 5", "Tôn Đức Thắng 6", "Tôn Đức Thắng 7", "Tôn Thất Đạm 1", "Tôn Thất Đạm 2", "Tôn Thất Thiệp 1"],
  "Thạnh Mỹ Tây": ["CC Phạm Viết Chánh-1-BT-19", "CC Phạm Viết Chánh-2-BT-19", "Chiếu Sáng 2", "Cảng Than-1-BT-25", "Cầu Kinh Thanh Đa-1-BT-25", "Cầu Sài Gòn-1-BT-25", "Cầu Sài Gòn-2-BT-25", "Cầu Thủ Thiêm-1-BT-22", "Cửu Long A", "Điện Biên Phủ-17-BT-21", "Điện Biên Phủ-18-BT-25", "Điện Biên Phủ-19-BT-25", "Điện Biên Phủ-20-BT-25", "Điện Biên Phủ-21-BT-25", "Điện Biên Phủ-22-BT-25", "Đường D5-1-BT-25", "Dọc Kênh Thanh Đa-1-BT-25", "Huỳnh Tịnh Của-1-BT-19", "Hẻm 113 Võ Duy Ninh-1-BT-22", "Hẻm 113 Võ Duy Ninh-2-BT-22", "Hẻm 117 Nguyễn Hữu Cảnh-1-BT-22", "Hẻm 12 Nguyễn Hữu Cảnh-1-BT-19", "Hẻm 158 Xô Viết Nghệ Tĩnh-1-BT-17", "Hẻm 16 Nguyễn Văn Thương-1-BT-25", "Hẻm 180 Nguyễn Hữu Cảnh-1-BT-22", "Hẻm 180 Xô Viết Nghệ Tĩnh-1-BT-17", "Hẻm 2 Điện Biên Phủ-1-BT-25", "Hẻm 220 Xô Viết Nghệ Tĩnh-1-BT-21", "Hẻm 234/6 Ung Văn Khiêm-1-BT-25", "Hẻm 24 Võ Oanh-1-BT-25", "Hẻm 340 Ung Văn Khiêm-1-BT-25", "Hẻm 378 Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 405 Xô Viết Nghệ Tĩnh-1-BT-24", "Hẻm 42 Ung Văn Khiêm-1-BT-25", "Hẻm 441 Điện Biên Phủ-1-BT-25", "Hẻm 441 Điện Biên Phủ-2-BT-25", "Hẻm 4A Nguyễn Văn Thương-1-BT-25", "Hẻm 4A/4 Nguyễn Văn Thương-1-BT-25", "Hẻm 4A/6 Nguyễn Văn Thương-1-BT-3", "Hẻm 549 Xô Viết Nghệ Tĩnh-1-BT-26", "Hẻm 585 Điện Biên Phủ-1-BT-25", "Hẻm 618 Ung Văn Khiêm-1-BT-25", "Hẻm 62 Huỳnh Tịnh Của-1-BT-19", "Hẻm 66 Xô Viết Nghệ Tĩnh-1-BT-17", "Hẻm 73 Nguyễn Văn Thương-1-BT-25", "Hẻm 758 Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 758 Xô Viết Nghệ Tĩnh-2-BT-25", "Hẻm 818 Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 860 Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 860/60N Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 860/60S Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 860/60X Xô Viết Nghệ Tĩnh-1-BT-25", "Hẻm 92 Xô Viết Nghệ Tĩnh-1-BT-17", "Khu Thanh Niên Văn Thánh-1-BT-22", "Lô A-CC Ngô Tất Tố-2-BT-19", "Lô B CC Ngô Tất Tố-1-BT-19", "Lô C-CC Ngô Tất Tố-3-BT-19", "Mê Linh-1-BT-19", "Nguyễn Công Trứ-1-BT-19", "Nguyễn Công Trứ-2-BT-19", "Nguyễn Gia Trí nối dài-1-BT-25", "Nguyễn Gia Trí-1-BT-25", "Nguyễn Gia Trí-2-BT-25", "Nguyễn Gia Trí-3-BT-25", "Nguyễn Hữu Cảnh-1-BT-22", "Nguyễn Hữu Cảnh-2-BT-22", "Nguyễn Hữu Cảnh-3-BT-22", "Nguyễn Hữu Cảnh-4-BT-22", "Nguyễn Hữu Cảnh-5-BT-22", "Nguyễn Văn Lạc-1-BT-19", "Nguyễn Văn Lạc-2-BT-17", "Nguyễn Văn Thương-1-BT-25", "Nguyễn Văn Thương-2-BT-25", "Nguyễn Văn Thương-3-BT-25", "Nguyễn Xuân Ôn-1-BT-19", "Ngô Tất Tố-1-BT-19", "Ngô Tất Tố-2-BT-19", "Ngô Tất Tố-3-BT-22", "Phú Mỹ nối dài-1-BT-22", "Phạm Viết Chánh-1-BT-19", "Phạm Viết Chánh-2-BT-19", "Trường Sa-1-BT-19", "Trường Sa-2-BT-17", "Tân Cảng-1-BT-15", "Ung Văn Khiêm-1-BT-25", "Ung Văn Khiêm-2-BT-25", "Ung Văn Khiêm-3-BT-25", "Ung Văn Khiêm-4-BT-25", "Vòng Xoay Hàng Xanh-2-BT-21", "Vòng Xoay Hàng Xanh-3-BT-25", "Võ Duy Ninh-1-BT-22", "Võ Oanh-1-BT-25", "Xây Dựng Mới 7", "Xô Viết Nghệ Tĩnh-1-BT-17", "Xô Viết Nghệ Tĩnh-2-BT-17", "Xô Viết Nghệ Tĩnh-3-BT-25", "Xô Viết Nghệ Tĩnh-4-BT-25", "Xô Viết Nghệ Tĩnh-5-BT-25"],
  "Tân Định": ["Bà Lê Chân 1", "Cây Điệp 1", "Công Viên Lê Văn Tám 1", "Công Viên Lê Văn Tám 2", "Công Viên Lê Văn Tám 3", "Đinh Công Tráng 1", "Đinh Tiên Hoàng 3", "Đinh Tiên Hoàng 4", "Điện Biên 110", "Điện Biên Phủ 10", "Điện Biên Phủ 11", "Điện Biên Phủ 12", "Điện Biên Phủ 8", "Điện Biên Phủ 9", "Hai Bà Trưng 5", "Hai Bà Trưng 6", "Hai Bà Trưng 7", "Hoàng Sa 2", "Hoàng Sa 3", "Hoàng Sa 4", "Hoàng Sa 5", "Huyền Quang 1", "Huỳnh Khương Ninh 1", "Hầm chui Điện Biên Phủ 1", "Hẻm 26 Nguyễn Bỉnh Khiêm 1", "KNỞ 10A T.N.Duật", "Lý Văn Phức 1", "Mai Thị Lựu 1", "Mai Thị Lựu 2", "Nguyễn Đình Chiểu 1", "Nguyễn Huy Tự 1", "Nguyễn Hữu Cầu 1", "Nguyễn Phi Khanh 1", "Nguyễn Thành Ý 1", "Nguyễn Văn Giai 1", "Nguyễn Văn Nguyễn 1", "Nguyễn Văn Nguyễn 2", "Nguyễn Văn Nguyễn 3", "Nguyễn Văn Thủ 1", "Nguyễn Văn Thủ 2", "Nguyễn Văn Thủ 3", "Phan Liêm 1", "Phùng Khắc Khoan 2", "Trạm Cầu Bông 1", "Trần Khánh Dư 1", "Trần Khánh Dư 2", "Trần Khắc Chân 1", "Trần Khắc Chân 2", "Trần Nhật Duật 1", "Trần Nhật Duật 2", "Trần Quang Khải 1", "Trần Quang Khải 2", "Trần Quang Khải 3", "Trần Quang Khải 4", "Trần Quý Khoách 1", "Võ Thị Sáu 1"],
  "Tân Phú": ["Trịnh Đình Trọng-1"],
  "Tân Sơn Hòa": ["KNO 284 Nguyễn Trọng Tuyển -1- PN - 10"],
  "Vườn Lài": ["Ba Tháng Hai-1", "Ba Tháng Hai-2", "Ba Tháng Hai-3", "Bà Hạt-1", "Bà Hạt-2", "Chung cư Ngô Gia Tự", "Chung cư Sư Vạn Hạnh Lô L", "Chung cư Sư Vạn Hạnh Lô N", "Chung cư Sư Vạn Hạnh Lô U", "Chung cư Ấn Quan", "Duy Dương", "Duy Dương 180", "Điện Biên Phủ-1", "Điện Biên Phủ-2", "Điện Biên Phủ-3", "Điện Biên Phủ-4", "Hòa Hảo-1", "Hòa Hảo-2", "Hòa Hảo-3", "Hùng Vương 1", "Hùng Vương 2", "Hẻm 207 Ba Tháng Hai", "Hẻm 480 Nguyễn Tri Phương", "Hẻm 500 Lê Hồng Phong-1", "Hẻm 500 Lê Hồng Phong-2", "Hẻm 500 Lê Hồng Phong-3", "Hẻm 500 Lê Hồng Phong-4", "Hẻm 528 Điện Biên Phủ 1", "Hẻm 702 Điện Biên Phủ", "Hồ Thị Kỷ-1", "Hồ Thị Kỷ-2", "Hồ Thị Kỷ-3", "Lê Hồng Phong-2", "Lê Hồng Phong-3", "Lê Hồng Phong-4", "Lê Hồng Phong-5", "Lý Thái Tổ 3", "Lý Thái Tổ 5", "Lý Thái Tổ 6", "Lý Thái Tổ 7", "Nguyễn Chí Thanh 1", "Nguyễn Tri Phương-1", "Nguyễn Tri Phương-3", "Ngô Gia Tự 1", "Ngô Gia Tự 2", "Ngô Gia Tự 3", "Nhân Tôn-1", "Nhân Tôn-2", "Sư Vạn Hạnh 1", "Sư Vạn Hạnh 2", "Sư Vạn Hạnh 3", "Trần Bình Trọng-1", "Trần Bình Trọng-2", "Trần Minh Quyền", "Vĩnh Viễn-1", "Vĩnh Viễn-2", "Vĩnh Viễn-3", "Vĩnh Viễn-4", "Ấn Quan 3", "Ấn Quan 4"],
  "Xuân Hòa": ["Bà Huyện Thanh Quan 2", "Bà Huyện Thanh Quan 3", "Bà Huyện Thanh Quan 4", "Cách Mạng Tháng 8 -10", "Cách Mạng Tháng 8 -6", "Cách Mạng Tháng 8 -8", "Công Trường Quốc Tế 1", "Công Trường Quốc Tế 2", "Cầu Kiệu 1", "Cầu Lê Văn Sỹ 1", "Điện Biên Phủ 4", "Điện Biên Phủ 5", "Điện Biên Phủ 6", "Điện Biên Phủ 7", "Đoàn Công Bửu 1", "Hai Bà Trưng 4", "Hoàng Sa 6", "Hoàng Sa 7", "Huỳnh Tịnh Của 1", "Hẻm 21 Võ Văn Tần", "Hẻm 232 Võ Thị Sáu", "Hẻm 384 Nam Kỳ Khởi Nghĩa", "Hồ Xuân Hương 1", "Lê Quý Đôn 1", "Lê Quý Đôn 2", "Lý Chính Thắng 1", "Lý Chính Thắng 2", "Nam Kỳ Khởi Nghĩa 1", "Nam Kỳ Khởi Nghĩa 2", "Nam Kỳ Khởi Nghĩa 3", "Nam Kỳ Khởi Nghĩa 4", "Nam Kỳ Khởi Nghĩa 5", "Nam Kỳ Khởi Nghĩa 6", "Nguyễn Đình Chiểu 3", "Nguyễn Đình Chiểu 4", "Nguyễn Đình Chiểu 5", "Nguyễn Thông 2", "Nguyễn Thị Diệu 1", "Nguyễn Thị Minh Khai 6", "Nguyễn Thị Minh Khai 7", "Nguyễn Văn Mai 1", "Ngô Thời Nhiệm 1", "Pasteur 5", "Pasteur 6", "Pasteur 7", "Pasteur 8", "Phạm Ngọc Thạch 1", "Phạm Ngọc Thạch 2", "Sư Thiện Chiếu 1", "Trương Định 3", "Trương Định 4", "Trương Quyền 1", "Trần Cao Vân 1", "Trần Quốc Thảo 1", "Trần Quốc Thảo 2", "Trần Quốc Thảo 3", "Trần Quốc Thảo 4", "Trần Quốc Toản 1", "Trần Quốc Toản 2", "Tú Xương 1", "Tú Xương 2", "Võ Thị Sáu 2", "Võ Văn Tần 1"],
  "Xã Bình Hưng": ["Đường số 15 Khu dân cư Đồng Diều"],
};

// Tổng: 1776 TĐK / 33 phường thuộc 8 quận/huyện trung tâm TP.HCM
