// Tự sinh từ "khao sat tang cuong den.xlsx" ngày 2026-05-27
// KHÔNG sửa tay file này. Khi nguồn cập nhật, chạy lại script sinh.

export const PHUONG_XA = [
  { ten: "Hiệp Bình", quan_cu: "TP Thủ Đức" },
  { ten: "Tam Bình", quan_cu: "TP Thủ Đức" },
  { ten: "Thủ Đức", quan_cu: "TP Thủ Đức" },
  { ten: "Linh Xuân", quan_cu: "TP Thủ Đức" },
  { ten: "Long Bình", quan_cu: "TP Thủ Đức" },
  { ten: "Tăng Nhơn Phú", quan_cu: "TP Thủ Đức" },
  { ten: "Phước Long", quan_cu: "TP Thủ Đức" },
  { ten: "Long Phước", quan_cu: "TP Thủ Đức" },
  { ten: "Long Trường", quan_cu: "TP Thủ Đức" },
  { ten: "An Khánh", quan_cu: "TP Thủ Đức" },
  { ten: "Bình Trưng", quan_cu: "TP Thủ Đức" },
  { ten: "Cát Lái", quan_cu: "TP Thủ Đức" },
  { ten: "Tân Định", quan_cu: "Quận 1" },
  { ten: "Bến Thành", quan_cu: "Quận 1" },
  { ten: "Sài Gòn", quan_cu: "Quận 1" },
  { ten: "Cầu Ông Lãnh", quan_cu: "Quận 1" },
  { ten: "Bàn Cờ", quan_cu: "Quận 3" },
  { ten: "Xuân Hòa", quan_cu: "Quận 3" },
  { ten: "Nhiêu Lộc", quan_cu: "Quận 3" },
  { ten: "Vĩnh Hội", quan_cu: "Quận 4" },
  { ten: "Khánh Hội", quan_cu: "Quận 4" },
  { ten: "Xóm Chiếu", quan_cu: "Quận 4" },
  { ten: "Chợ Quán", quan_cu: "Quận 5" },
  { ten: "An Đông", quan_cu: "Quận 5" },
  { ten: "Chợ Lớn", quan_cu: "Quận 5" },
  { ten: "Bình Tiên", quan_cu: "Quận 6" },
  { ten: "Bình Tây", quan_cu: "Quận 6" },
  { ten: "Bình Phú", quan_cu: "Quận 6" },
  { ten: "Phú Lâm", quan_cu: "Quận 6" },
  { ten: "Tân Mỹ", quan_cu: "Quận 7" },
  { ten: "Tân Hưng", quan_cu: "Quận 7" },
  { ten: "Tân Thuận", quan_cu: "Quận 7" },
  { ten: "Phú Thuận", quan_cu: "Quận 7" },
  { ten: "Chánh Hưng", quan_cu: "Quận 8" },
  { ten: "Bình Đông", quan_cu: "Quận 8" },
  { ten: "Phú Định", quan_cu: "Quận 8" },
  { ten: "Vườn Lài", quan_cu: "Quận 10" },
  { ten: "Diên Hồng", quan_cu: "Quận 10" },
  { ten: "Hòa Hưng", quan_cu: "Quận 10" },
  { ten: "Hòa Bình", quan_cu: "Quận 11" },
  { ten: "Phú Thọ", quan_cu: "Quận 11" },
  { ten: "Bình Thới", quan_cu: "Quận 11" },
  { ten: "Minh Phụng", quan_cu: "Quận 11" },
  { ten: "Đông Hưng Thuận", quan_cu: "Quận 12" },
  { ten: "Trung Mỹ Tây", quan_cu: "Quận 12" },
  { ten: "Tân Thới Hiệp", quan_cu: "Quận 12" },
  { ten: "Thới An", quan_cu: "Quận 12" },
  { ten: "An Phú Đông", quan_cu: "Quận 12" },
  { ten: "Gia Định", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Thạnh", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Lợi Trung", quan_cu: "Quận Bình Thạnh" },
  { ten: "Thạnh Mỹ Tây", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Quới", quan_cu: "Quận Bình Thạnh" },
  { ten: "Bình Tân", quan_cu: "Quận Bình Tân" },
  { ten: "Bình Hưng Hòa", quan_cu: "Quận Bình Tân" },
  { ten: "Bình Trị Đông", quan_cu: "Quận Bình Tân" },
  { ten: "An Lạc", quan_cu: "Quận Bình Tân" },
  { ten: "Tân Tạo", quan_cu: "Quận Bình Tân" },
  { ten: "Hạnh Thông", quan_cu: "Quận Gò Vấp" },
  { ten: "An Nhơn", quan_cu: "Quận Gò Vấp" },
  { ten: "Gò Vấp", quan_cu: "Quận Gò Vấp" },
  { ten: "Thông Tây Hội", quan_cu: "Quận Gò Vấp" },
  { ten: "An Hội Tây", quan_cu: "Quận Gò Vấp" },
  { ten: "An Hội Đông", quan_cu: "Quận Gò Vấp" },
  { ten: "Đức Nhuận", quan_cu: "Quận Phú Nhuận" },
  { ten: "Cầu Kiệu", quan_cu: "Quận Phú Nhuận" },
  { ten: "Phú Nhuận", quan_cu: "Quận Phú Nhuận" },
  { ten: "Tân Sơn Hòa", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Sơn Nhất", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Hòa", quan_cu: "Quận Tân Bình" },
  { ten: "Bảy Hiền", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Bình", quan_cu: "Quận Tân Bình" },
  { ten: "Tân Sơn", quan_cu: "Quận Tân Bình" },
  { ten: "Tây Thạnh", quan_cu: "Quận Tân Phú" },
  { ten: "Tân Sơn Nhì", quan_cu: "Quận Tân Phú" },
  { ten: "Phú Thọ Hòa", quan_cu: "Quận Tân Phú" },
  { ten: "Phú Thạnh", quan_cu: "Quận Tân Phú" },
  { ten: "Tân Phú", quan_cu: "Quận Tân Phú" },
  { ten: "Vĩnh Lộc", quan_cu: "Huyện Bình Chánh" },
  { ten: "Tân Vĩnh Lộc", quan_cu: "Huyện Bình Chánh" },
  { ten: "Bình Lợi", quan_cu: "Huyện Bình Chánh" },
  { ten: "Tân Nhựt", quan_cu: "Huyện Bình Chánh" },
  { ten: "Bình Chánh", quan_cu: "Huyện Bình Chánh" },
  { ten: "Hưng Long", quan_cu: "Huyện Bình Chánh" },
  { ten: "Bình Hưng", quan_cu: "Huyện Bình Chánh" },
  { ten: "An Nhơn Tây", quan_cu: "Huyện Củ Chi" },
  { ten: "Thái Mỹ", quan_cu: "Huyện Củ Chi" },
  { ten: "Nhuận Đức", quan_cu: "Huyện Củ Chi" },
  { ten: "Tân An Hội", quan_cu: "Huyện Củ Chi" },
  { ten: "Củ Chi", quan_cu: "Huyện Củ Chi" },
  { ten: "Phú Hòa Đông", quan_cu: "Huyện Củ Chi" },
  { ten: "Bình Mỹ", quan_cu: "Huyện Củ Chi" },
  { ten: "Bình Khánh", quan_cu: "Huyện Cần Giờ" },
  { ten: "Cần Giờ", quan_cu: "Huyện Cần Giờ" },
  { ten: "An Thới Đông", quan_cu: "Huyện Cần Giờ" },
  { ten: "Thạnh An", quan_cu: "Huyện Cần Giờ" },
  { ten: "Hóc Môn", quan_cu: "Huyện Hóc Môn" },
  { ten: "Bà Điểm", quan_cu: "Huyện Hóc Môn" },
  { ten: "Xuân Thới Sơn", quan_cu: "Huyện Hóc Môn" },
  { ten: "Đông Thạnh", quan_cu: "Huyện Hóc Môn" },
  { ten: "Nhà Bè", quan_cu: "Huyện Nhà Bè" },
  { ten: "Hiệp Phước", quan_cu: "Huyện Nhà Bè" },
];

export const QUAN_LIST = [...new Set(PHUONG_XA.map(p => p.quan_cu))].sort();

export const TDK_LIST = [
  "An Bình - 1",
  "An Bình - 2",
  "An Bình - 3",
  "An Bình - 4",
  "An Bình - 5",
  "An Dương Vương - 1",
  "An Dương Vương - 2",
  "An Dương Vương - 3",
  "An Dương Vương - 4",
  "An Dương Vương - 5",
  "An Dương Vương - 6",
  "An Dương Vương - 7",
  "An Dương Vương - 8",
  "An Dương Vương - 9",
  "An Điềm - 1",
  "An Điềm - 2",
  "Ba Tháng Hai-1",
  "Ba Tháng Hai-10",
  "Ba Tháng Hai-11",
  "Ba Tháng Hai-12",
  "Ba Tháng Hai-13",
  "Ba Tháng Hai-14",
  "Ba Tháng Hai-2",
  "Ba Tháng Hai-3",
  "Ba Tháng Hai-4",
  "Ba Tháng Hai-5",
  "Ba Tháng Hai-6",
  "Ba Tháng Hai-7",
  "Ba Tháng Hai-8",
  "Ba Tháng Hai-9",
  "Ba Vì",
  "Ba Đình - 1",
  "Ba Đình - 2",
  "Ba Đình - 3",
  "Ba Đình - 4",
  "Ba Đình - 6",
  "Ba Đình - 7",
  "Ba Đình - 8",
  "Ba Đình - 9",
  "Ba Đình 481",
  "Bà Hạt-1",
  "Bà Hạt-2",
  "Bà Hạt-3",
  "Bà Hạt-4",
  "Bình Dương Thị Xã",
  "Bình Thới 2",
  "Bình Thới 4",
  "Bình Thới 6",
  "Bình Thới 7",
  "Bình Thới Làng",
  "Bình Điền Khu 17-1",
  "Bình Điền Khu 17-2",
  "Bình Điền Khu 17-3",
  "Bình Đông - 1",
  "Bình Đông - 11",
  "Bình Đông - 13",
  "Bình Đông - 14",
  "Bình Đông - 15",
  "Bình Đông - 16",
  "Bình Đông - 17",
  "Bình Đông - 18",
  "Bình Đông - 2",
  "Bình Đông - 3",
  "Bình Đông - 4",
  "Bình Đông - 7",
  "Bình Đông - 8",
  "Bông Sao - 1",
  "Bông Sao - 2",
  "Bùi Huy Bích - 1",
  "Bùi Huy Bích - 2",
  "Bùi Minh Trực - 1",
  "Bùi Minh Trực - 2",
  "Bùi Minh Trực - 3",
  "Bùi Minh Trực - 4",
  "Bùi Minh Trực - 5",
  "Bùi Minh Trực - 6",
  "Bùi Minh Trực - 7",
  "Bùi Minh Trực - 8",
  "Bùi Minh Trực - 9",
  "Bùi Điền - 1",
  "Bùi Điền - 2",
  "Bến Xe Quận 8",
  "Bến xe Chợ Lớn",
  "Bờ Kè  Nguyễn Sĩ Cố",
  "Bờ Kè Bình Đông 1",
  "Bờ Kè Bình Đông 2",
  "Bờ Kè Bình Đông 3",
  "Bờ Kè Bình Đức",
  "Bờ Kè Bùi Huy Bích",
  "Bờ Kè Hoàng Sĩ Khải",
  "Bờ Kè Mễ Cốc",
  "Bờ Kè Nguyễn Nhược Thị",
  "Bờ Kè Ngô Sĩ Liên",
  "Bờ Kè Phú Định 1",
  "Bờ Kè Phú Định 2",
  "CVP15Q8",
  "Cao Su - 3",
  "Cao Su - 4",
  "Cao Su - 5",
  "Cao Thắng 1",
  "Cao Đạt - 3",
  "Cao Ốc Thuận Việt",
  "Chung Cư 319/1",
  "Chung Cư 319/2",
  "Chung cư 109 Nguyễn Biểu",
  "Chung cư Bình Đăng",
  "Chung cư Him Lam - Nam Khánh",
  "Chung cư Lạc Long Quân-1",
  "Chung cư Lạc Long Quân-2",
  "Chung cư Lạc Long Quân-3",
  "Chung cư Nguyễn Tri Phương",
  "Chung cư Ngô Gia Tự",
  "Chung cư Sư Vạn Hạnh",
  "Chung cư Sư Vạn Hạnh Lô L",
  "Chung cư Sư Vạn Hạnh Lô N",
  "Chung cư Sư Vạn Hạnh Lô U",
  "Chung cư Trường Đua A",
  "Chung cư Trường Đua B",
  "Chung cư Trần Văn Kiểu",
  "Chung cư Xóm Cải - 1",
  "Chung cư Xóm Cải - 2",
  "Chung cư Ấn Quan",
  "Chánh Hưng - 3A",
  "Chánh Hưng - 5A",
  "Châu Thị Hóa",
  "Châu Văn Liêm - 1",
  "Châu Văn Liêm - 2",
  "Châu Văn Liêm - 3",
  "Chợ Quán",
  "Chợ Thiếc 1",
  "Chợ Thiếc 1 TC",
  "Chợ Thiếc 2",
  "Công Binh",
  "Công Binh TC",
  "Công Trường An Đông - 2",
  "Công Trừng 3",
  "Công Viên Âu Lạc",
  "Công trường An Đông - 1",
  "Công viên An Bình",
  "Công viên Dạ Trạch",
  "Công viên Hòa Bình",
  "Công viên Tạ Quang Bửu",
  "Cư xá Chánh Hưng A",
  "Cư xá Hưng Phú",
  "Cư xá Trịnh Đình Trọng",
  "Cư xá Đồng Tiến-1",
  "Cư xá Đồng Tiến-2",
  "Cư xá Đồng Tiến-3",
  "Cư xá Đồng Tiến-4",
  "Cầu Chà Và",
  "Cầu Chánh Hưng - 1",
  "Cầu Chánh Hưng - 2",
  "Cầu Chữ Y",
  "Cầu Nguyễn Tri Phương - 1",
  "Cầu Nguyễn Tri Phương - 2",
  "Cầu Tạ Quang Bửu",
  "Cửu Long-1",
  "Cửu Long-2",
  "Diên Nghệ 1",
  "Duy Dương",
  "Duy Dương 180",
  "Dã Tượng",
  "Dương Bá Trạc - 1",
  "Dương Bá Trạc - 2",
  "Dương Bạch Mai",
  "Dương Quang Trung 1",
  "Dương Quang Trung 2",
  "Dương Quang Đông - 1",
  "Dương Quang Đông - 2",
  "Dương Tử Giang",
  "Dương Đình Nghệ-1",
  "Dương Đình Nghệ-2",
  "Dương Đình Nghệ-3",
  "Dương Đình Nghệ-4",
  "Dạ Nam - 1",
  "Dạ Nam - 2",
  "EMG - 2",
  "EMG - 4",
  "Gia Phú",
  "Giếng Đại Hành TC",
  "Gò Công - 1",
  "Gò Công - 2",
  "Hoài Thanh - 1",
  "Hoài Thanh - 2",
  "Hoài Thanh - 3",
  "Hoài Thanh - 4",
  "Hoàng Dư Khương",
  "Hoàng Minh Đạo",
  "Hoàng Ngân - 1",
  "Hoàng Ngân - 2",
  "Hoàng Ngân - 3",
  "Hoàng Quân 2",
  "Hoàng Đạo Thúy - 1",
  "Hoàng Đạo Thúy - 2",
  "Hoàng Đạo Thúy - 3",
  "Huyện Toại",
  "Huỳnh Thị Phụng",
  "Hà Tôn Quyền",
  "Hàn Hải Nguyên-1",
  "Hàn Hải Nguyên-2",
  "Hàn Hải Nguyên-3",
  "Hàn Hải Nguyên-5",
  "Hàn Hải Nguyên-6",
  "Hàn Hải Nguyên-7",
  "Hàn Hải Nguyên-8",
  "Hàn Hải Nguyên-9",
  "Hòa Bình - 1",
  "Hòa Bình - 2",
  "Hòa Bình-1",
  "Hòa Bình-2",
  "Hòa Hưng",
  "Hòa Hảo-1",
  "Hòa Hảo-2",
  "Hòa Hảo-3",
  "Hòa Hảo-4",
  "Hòa Hảo-5",
  "Hùng Vương - 3",
  "Hùng Vương - 4",
  "Hùng Vương - 5",
  "Hùng Vương 1",
  "Hùng Vương 2",
  "Hưng Phú - 10",
  "Hưng Phú - 11",
  "Hưng Phú - 2",
  "Hưng Phú - 3",
  "Hưng Phú - 4",
  "Hưng Phú - 5",
  "Hưng Phú - 6",
  "Hưng Phú - 7",
  "Hưng Phú - 8",
  "Hưng Phú - 9",
  "Hưng Phú -1",
  "Hương Lộ - 5",
  "Hải Thượng Lãn Ông - 1",
  "Hải Thượng Lãn Ông - 2",
  "Hải Thượng Lãn Ông - 3",
  "Hải Thượng Lãn Ông - 4",
  "Hải Thượng Lãn Ông - 5",
  "Hải Thượng Lãn Ông - 6",
  "Hải Thượng Lãn Ông - 8",
  "Hải Thượng Lãn Ông - 9",
  "Hẻm 100 Bình Thới-1",
  "Hẻm 100 Bình Thới-2",
  "Hẻm 102 Bình Thới-1",
  "Hẻm 102 Bình Thới-2",
  "Hẻm 106 Lạc Long Quân",
  "Hẻm 107 Trần Hưng Đạo",
  "Hẻm 109 Dương Bá Trạc",
  "Hẻm 121 Hưng Phú",
  "Hẻm 127 Âu Cơ-1",
  "Hẻm 127 Âu Cơ-2",
  "Hẻm 134 Thành Thái",
  "Hẻm 1352 Ba Tháng Hai",
  "Hẻm 136 Trần Phú",
  "Hẻm 138 Ngô Quyền",
  "Hẻm 14 Hoàng Dư Khương",
  "Hẻm 150 Phú Định",
  "Hẻm 151 Lạc Long Quân",
  "Hẻm 152 Lạc Long Quân-1",
  "Hẻm 152 Lạc Long Quân-2",
  "Hẻm 154 Âu Dương Lân",
  "Hẻm 157 Dương Bá Trạc - 1",
  "Hẻm 157 Dương Bá Trạc - 2",
  "Hẻm 158 Hòa Hưng",
  "Hẻm 161 Lạc Long Quân",
  "Hẻm 163 Tô Hiến Thành",
  "Hẻm 172 An Dương Vương - 1",
  "Hẻm 172 An Dương Vương - 2",
  "Hẻm 172 An Dương Vương - 3",
  "Hẻm 172 An Dương Vương - 4",
  "Hẻm 180 Minh Phụng-1",
  "Hẻm 180 Minh Phụng-2",
  "Hẻm 181 Bình Thới",
  "Hẻm 185 Lý Thường Kiệt",
  "Hẻm 195 Bùi Minh Trực",
  "Hẻm 20 Mễ Cốc",
  "Hẻm 200 Thái Phiên",
  "Hẻm 207 Ba Tháng Hai",
  "Hẻm 218 An Dương Vương",
  "Hẻm 224 Lý Thường Kiệt",
  "Hẻm 232 Lý Thường Kiệt",
  "Hẻm 236 Thái Phiên",
  "Hẻm 258 Bông Sao",
  "Hẻm 269 Nguyễn Thị Nhỏ",
  "Hẻm 284 Lý Thường Kiệt",
  "Hẻm 285 CMT8",
  "Hẻm 288D Dương Bá Trạc",
  "Hẻm 289 Bình Đông",
  "Hẻm 290D Dương Bá Trạc",
  "Hẻm 3 Thành Thái",
  "Hẻm 32 Ông Ích Khiêm-1",
  "Hẻm 32 Ông Ích Khiêm-2",
  "Hẻm 323 Minh Phụng",
  "Hẻm 334 Lý Thường Kiệt",
  "Hẻm 339 Tô Hiến Thành",
  "Hẻm 341 Lạc Long Quân-1",
  "Hẻm 341 Lạc Long Quân-2",
  "Hẻm 341 Lạc Long Quân-3",
  "Hẻm 349 Lê Đại Hành",
  "Hẻm 35 Cao Lỗ",
  "Hẻm 351 Lê Đại Hành-1",
  "Hẻm 351 Lê Đại Hành-2",
  "Hẻm 354 Lý Thường Kiệt",
  "Hẻm 36B Đường 762 Hồng Bàng",
  "Hẻm 37 Trịnh Đình Trọng",
  "Hẻm 377 Lê Đại Hành",
  "Hẻm 38 Nguyễn Ngọc Cung",
  "Hẻm 392 Cao Thắng",
  "Hẻm 418 Minh Phụng-1",
  "Hẻm 418 Minh Phụng-2",
  "Hẻm 418 Trần Phú",
  "Hẻm 419 Cách Mạng Tháng 8",
  "Hẻm 423 Lạc Long Quân-1",
  "Hẻm 423 Lạc Long Quân-2",
  "Hẻm 423 Lạc Long Quân-3",
  "Hẻm 43 Thành Thái",
  "Hẻm 436A Ba Tháng Hai",
  "Hẻm 436B Ba Tháng Hai",
  "Hẻm 449 Sư Vạn Hạnh",
  "Hẻm 45 Ông Ích Khiêm",
  "Hẻm 451 Tô Hiến Thành-1",
  "Hẻm 451 Tô Hiến Thành-2",
  "Hẻm 453 Bùi Minh Trực",
  "Hẻm 463 CMT8 1",
  "Hẻm 47 Nguyễn Thị Tần",
  "Hẻm 480 Nguyễn Tri Phương",
  "Hẻm 49 Âu Cơ",
  "Hẻm 495 Tô Hiến Thành",
  "Hẻm 500 Lê Hồng Phong-1",
  "Hẻm 500 Lê Hồng Phong-2",
  "Hẻm 500 Lê Hồng Phong-3",
  "Hẻm 500 Lê Hồng Phong-4",
  "Hẻm 506 Ba Tháng Hai",
  "Hẻm 51 Thành Thái",
  "Hẻm 527 Dương Bá Trạc",
  "Hẻm 528 Điện Biên Phủ 1",
  "Hẻm 55 Nguyễn Chế Nghĩa",
  "Hẻm 568 Lạc Long Quân",
  "Hẻm 606 Ba Tháng Hai-1",
  "Hẻm 606 Ba Tháng Hai-2",
  "Hẻm 666 Ba Tháng Hai",
  "Hẻm 68 Đồng Nai-1",
  "Hẻm 68 Đồng Nai-2",
  "Hẻm 702 Hồng Bàng",
  "Hẻm 702 Điện Biên Phủ",
  "Hẻm 76 Xóm Đất",
  "Hẻm 79 Âu Cơ-1",
  "Hẻm 79 Âu Cơ-2",
  "Hẻm 7A+7B Thành Thái-1",
  "Hẻm 7A+7B Thành Thái-2",
  "Hẻm 7A+7B Thành Thái-3",
  "Hẻm 8 Tân Hóa-1",
  "Hẻm 8 Tân Hóa-2",
  "Hẻm 814 Sư Vạn Hạnh",
  "Hẻm 83 Hòa Hưng",
  "Hẻm 86 Ông Ích Khiêm",
  "Hẻm 94 Hoà Bình-1",
  "Hẻm 94 Hoà Bình-2",
  "Hẻm Cao Thắng ND",
  "Hẻm Cư xá Phú Thọ Hoà-1",
  "Hẻm Cư xá Phú Thọ Hoà-2",
  "Hồ Biểu Chánh",
  "Hồ Bá Kiện-1",
  "Hồ Bá Kiện-2",
  "Hồ Thành Biên",
  "Hồ Thị Kỷ-1",
  "Hồ Thị Kỷ-2",
  "Hồ Thị Kỷ-3",
  "Hồng Bàng - 1",
  "Hồng Bàng - 10",
  "Hồng Bàng - 11",
  "Hồng Bàng - 2",
  "Hồng Bàng - 3",
  "Hồng Bàng - 4",
  "Hồng Bàng - 5",
  "Hồng Bàng - 6",
  "Hồng Bàng - 7",
  "Hồng Bàng - 8",
  "Hồng Bàng - 9",
  "Hồng Bàng-12",
  "Hồng Bàng-13",
  "Hồng Bàng-14",
  "Hữu Chí - 1",
  "Hữu Chí - 2",
  "KN 541 Sư Vạn Hạnh",
  "KNỞ P12 Trần Thiện Chánh",
  "Khu Chung cư hẻm 830 Sư Vạn Hạnh",
  "Khu Chợ Phú Bình-1",
  "Khu Chợ Phú Bình-2",
  "Khu Chợ Phú Bình-3",
  "Khu Chợ Phú Bình-4",
  "Khu TĐC Cảng Phú Định",
  "Khu dân cư An Dương Vương - 1",
  "Khu dân cư An Dương Vương - 2",
  "Khu dân cư Ba Tơ - 1",
  "Khu dân cư Ba Tơ - 2",
  "Khu dân cư Ba Tơ - 3",
  "Khu dân cư Bông Sao - 4",
  "Khu dân cư Bùi Minh Trực - 1",
  "Khu dân cư Nhật Minh",
  "Khu dân cư Phú Lợi - 1",
  "Khu dân cư Phú Lợi - 2",
  "Khu dân cư Phú Lợi - 3",
  "Khu dân cư Phú Lợi - 4",
  "Khu dân cư Phú Lợi - 5",
  "Khu dân cư Phú Lợi - 6",
  "Khu dân cư Phú Lợi - 7",
  "Khu dân cư Phường 10 Nguyễn Duy - 1",
  "Khu dân cư Phường 10 Nguyễn Duy - 2",
  "Khu dân cư Thanh Nhựt",
  "Khu dân cư Ứng Thành",
  "Khu nhà ở Bông Sao - 1",
  "Khu nhà ở Bông Sao - 2",
  "Khu nhà ở Bùi Minh Trực - 1",
  "Khu nhà ở Bùi Minh Trực - 2",
  "Khu nhà ở K34 Trần Thiện Chánh",
  "Khu nhà ở Lê Thị Riêng-1",
  "Khu nhà ở Lê Thị Riêng-2",
  "Khu tái định cư Bến Lức",
  "Khánh Vân 3",
  "Kim Khí - 1",
  "Kênh Tân Hóa Lò Gốm",
  "Ký Hòa",
  "Lãnh Binh Thăng 4 TC 3",
  "Lãnh Binh Thăng-1",
  "Lãnh Binh Thăng-2",
  "Lãnh Binh Thăng-3",
  "Lãnh Binh Thăng-4",
  "Lãnh Binh Thăng-5",
  "Lãnh Binh Thăng-6",
  "Lão Tử",
  "Lê Bôi - 1",
  "Lê Bôi - 2",
  "Lê Bôi - 3",
  "Lê Bôi - 4",
  "Lê Hồng Phong - 6",
  "Lê Hồng Phong - 7",
  "Lê Hồng Phong - 8",
  "Lê Hồng Phong-1",
  "Lê Hồng Phong-2",
  "Lê Hồng Phong-3",
  "Lê Hồng Phong-4",
  "Lê Hồng Phong-5",
  "Lê Quyên",
  "Lê Thị Bạch Cát-1",
  "Lê Thị Bạch Cát-2",
  "Lê Thị Bạch Cát-3",
  "Lê Đại Hành-1",
  "Lê Đại Hành-2",
  "Lê Đại Hành-3",
  "Lê Đại Hành-4",
  "Lê Đại Hành-5",
  "Lò Siêu 2",
  "Lò Siêu 2 TC",
  "Lò Siêu 45",
  "Lò Siêu TC 3",
  "Lô E-F Cư xá Bình Thới",
  "Lý Nam Đế",
  "Lý Thái Tổ 3",
  "Lý Thái Tổ 5",
  "Lý Thái Tổ 6",
  "Lý Thái Tổ 7",
  "Lý Thường Kiệt-1",
  "Lý Thường Kiệt-2",
  "Lý Thường Kiệt-3",
  "Lý Thường Kiệt-4",
  "Lý Thường Kiệt-5",
  "Lý Thường Kiệt-6",
  "Lý Thường Kiệt-7",
  "Lý Thường Kiệt-8",
  "Lý Đạo Thành",
  "Lưu Hữu Phước - 1",
  "Lưu Hữu Phước - 2",
  "Lưu Hữu Phước - 3",
  "Lưu Hữu Phước - 4",
  "Lưu Hữu Phước - 5",
  "Lưu Hữu Phước - 6",
  "Lưu Quý Kỳ - 1",
  "Lưu Quý Kỳ - 2",
  "Lương Nhữ Học - 1",
  "Lương Nhữ Học - 2",
  "Lương Văn Can",
  "Lạc Long Quân 312/A1",
  "Lạc Long Quân 312/A2",
  "Lạc Long Quân-1",
  "Lạc Long Quân-10",
  "Lạc Long Quân-11",
  "Lạc Long Quân-12",
  "Lạc Long Quân-13",
  "Lạc Long Quân-2",
  "Lạc Long Quân-3",
  "Lạc Long Quân-4",
  "Lạc Long Quân-5",
  "Lạc Long Quân-6",
  "Lạc Long Quân-7",
  "Lạc Long Quân-8",
  "Lạc Long Quân-9",
  "Lộ 50 Hòa Hưng",
  "Lữ Gia",
  "Lữ Gia 3",
  "Lữ Gia 4",
  "Lữ Gia 6",
  "Lữ Gia 7",
  "Mai Hắc Đế",
  "Minh Phụng 10",
  "Minh Phụng 10 TC",
  "Minh Phụng 11",
  "Minh Phụng 7",
  "Minh Phụng 8",
  "Minh Phụng 9",
  "Mã Hý - 2",
  "Mạc Cửu",
  "Mạc Thiên Tích",
  "Mạc Vân",
  "Mẫn Đạt",
  "Mẫn Đạt - 5",
  "Mễ Cốc - 1",
  "Mễ Cốc - 2",
  "Mễ Cốc - 3",
  "Mễ Cốc - 4",
  "Mễ Cốc - 5",
  "Nam Đế 2 TC",
  "Nguyễn An Khương",
  "Nguyễn Biểu",
  "Nguyễn Biểu - 2",
  "Nguyễn Chí Thanh - 10",
  "Nguyễn Chí Thanh - 11",
  "Nguyễn Chí Thanh - 2",
  "Nguyễn Chí Thanh - 3",
  "Nguyễn Chí Thanh - 4",
  "Nguyễn Chí Thanh - 6",
  "Nguyễn Chí Thanh - 8",
  "Nguyễn Chí Thanh 1",
  "Nguyễn Chí Thanh 12",
  "Nguyễn Chí Thanh 9",
  "Nguyễn Chí Thanh Nối Dài-1",
  "Nguyễn Chí Thanh Nối Dài-2",
  "Nguyễn Chí Thanh-5",
  "Nguyễn Chí Thanh-7",
  "Nguyễn Chế Nghĩa",
  "Nguyễn Duy - 1",
  "Nguyễn Duy - 10",
  "Nguyễn Duy - 2",
  "Nguyễn Duy - 3",
  "Nguyễn Duy - 4",
  "Nguyễn Duy - 5",
  "Nguyễn Duy - 6",
  "Nguyễn Duy - 7",
  "Nguyễn Duy - 8",
  "Nguyễn Duy - 9",
  "Nguyễn Duy Dương - 1",
  "Nguyễn Duy Dương - 2",
  "Nguyễn Duy Dương - 3",
  "Nguyễn Giản Thanh 1",
  "Nguyễn Kim",
  "Nguyễn Lâm-1",
  "Nguyễn Lâm-2",
  "Nguyễn Ngọc Cung - 1",
  "Nguyễn Ngọc Cung - 2",
  "Nguyễn Ngọc Lộc 1",
  "Nguyễn Nhược Thị",
  "Nguyễn Quyền",
  "Nguyễn Sĩ Cố",
  "Nguyễn Thi - 1",
  "Nguyễn Thi - 2",
  "Nguyễn Thị Nhỏ",
  "Nguyễn Thị Tần - 1",
  "Nguyễn Thị Tần - 2",
  "Nguyễn Thị Tần - 3",
  "Nguyễn Thị Tần - 4",
  "Nguyễn Tri Phương - 5",
  "Nguyễn Tri Phương - 6",
  "Nguyễn Tri Phương-1",
  "Nguyễn Tri Phương-2",
  "Nguyễn Tri Phương-3",
  "Nguyễn Tri Phương-4",
  "Nguyễn Trãi - 10",
  "Nguyễn Trãi - 6",
  "Nguyễn Trãi - 7",
  "Nguyễn Trãi - 8",
  "Nguyễn Trãi - 9",
  "Nguyễn Văn Của",
  "Nguyễn Văn Cừ - 3",
  "Nguyễn Văn Cừ - 4",
  "Nguyễn Văn Cừ - 5",
  "Nguyễn Văn Phú 1",
  "Nguyễn Án",
  "Ngô Gia Tự - 4",
  "Ngô Gia Tự 1",
  "Ngô Gia Tự 2",
  "Ngô Gia Tự 3",
  "Ngô Quyền - 1",
  "Ngô Quyền - 2",
  "Ngô Quyền-3",
  "Ngô Quyền-4",
  "Ngô Quyền-5",
  "Ngô Quyền-6",
  "Nhiêu Tâm - 24",
  "Nhiêu Tâm - 4",
  "Nhân Tôn-1",
  "Nhân Tôn-2",
  "Nhật Tiến",
  "Nhật Tảo-1",
  "Nhật Tảo-2",
  "Phan Phú Tiên - 1",
  "Phan Phú Tiên - 2",
  "Phan Xích Long",
  "Phó Cơ Điều",
  "Phù Đổng Thiên Vương",
  "Phùng Bích TC",
  "Phùng Hưng",
  "Phú Giáo",
  "Phú Hữu - 1",
  "Phú Hữu - 2",
  "Phú Thọ 1",
  "Phú Thọ 2A",
  "Phú Thọ 3",
  "Phú Định - 1",
  "Phú Định - 2",
  "Phú Định - 3",
  "Phú Định - 4",
  "Phú Định - 5",
  "Phú Định - 6",
  "Phú Định - 7",
  "Phước Hưng",
  "Phước Thiện - 3",
  "Phạm Hùng - 1",
  "Phạm Hùng - 2",
  "Phạm Nhữ Tăng",
  "Phạm Thế Hiển - 1",
  "Phạm Thế Hiển - 10",
  "Phạm Thế Hiển - 11",
  "Phạm Thế Hiển - 12",
  "Phạm Thế Hiển - 13",
  "Phạm Thế Hiển - 14",
  "Phạm Thế Hiển - 15",
  "Phạm Thế Hiển - 16",
  "Phạm Thế Hiển - 17",
  "Phạm Thế Hiển - 18",
  "Phạm Thế Hiển - 19",
  "Phạm Thế Hiển - 2",
  "Phạm Thế Hiển - 20",
  "Phạm Thế Hiển - 21",
  "Phạm Thế Hiển - 22",
  "Phạm Thế Hiển - 23",
  "Phạm Thế Hiển - 24",
  "Phạm Thế Hiển - 25",
  "Phạm Thế Hiển - 26",
  "Phạm Thế Hiển - 27",
  "Phạm Thế Hiển - 28",
  "Phạm Thế Hiển - 29",
  "Phạm Thế Hiển - 3",
  "Phạm Thế Hiển - 30",
  "Phạm Thế Hiển - 31",
  "Phạm Thế Hiển - 32",
  "Phạm Thế Hiển - 33",
  "Phạm Thế Hiển - 34",
  "Phạm Thế Hiển - 35",
  "Phạm Thế Hiển - 4",
  "Phạm Thế Hiển - 5",
  "Phạm Thế Hiển - 6",
  "Phạm Thế Hiển - 7",
  "Phạm Thế Hiển - 8",
  "Phạm Thế Hiển - 9",
  "Phạm Đức Sơn - 1",
  "Phạm Đức Sơn - 2",
  "Phạm Đức Sơn - 3",
  "Phồn Vinh - 3",
  "Quan Âm TC",
  "Quân Sự",
  "Quản Trọng Linh - 1",
  "Quản Trọng Linh - 2",
  "Quốc Lộ 50-1",
  "Quốc Lộ 50-2",
  "Rạch Bà Tàng - 1",
  "Rạch Bà Tàng - 2",
  "Rạch Cát",
  "Rạch Ụ Cây - 1",
  "Rạch Ụ Cây - 2",
  "Sân Thể Thao Phú Thọ",
  "Sư Vạn Hạnh - 4",
  "Sư Vạn Hạnh 1",
  "Sư Vạn Hạnh 2",
  "Sư Vạn Hạnh 3",
  "Sư Vạn Hạnh ND 1",
  "Sỹ Quan 3",
  "Tam Đảo",
  "Thành Thái ND-1",
  "Thành Thái ND-2",
  "Thành Thái-1",
  "Thành Thái-2",
  "Thái Phiên-1",
  "Thái Phiên-2",
  "Thái Phiên-3",
  "Thái Phiên-4",
  "Thất Hiệp 1/1",
  "Thời Trung",
  "Tiểu La-3",
  "Tiểu La-4",
  "Trương Đình Hội - 1",
  "Trương Đình Hội - 2",
  "Trần Bình Trọng - 3",
  "Trần Bình Trọng - 4",
  "Trần Bình Trọng - 5",
  "Trần Bình Trọng-1",
  "Trần Bình Trọng-2",
  "Trần Chánh Chiếu",
  "Trần Hưng Đạo - 11",
  "Trần Hưng Đạo - 12",
  "Trần Hưng Đạo - 13",
  "Trần Hưng Đạo - 14",
  "Trần Hưng Đạo - 15",
  "Trần Hưng Đạo - 16",
  "Trần Hưng Đạo - 17",
  "Trần Hưng Đạo - 18",
  "Trần Hưng Đạo - 19",
  "Trần Hưng Đạo - 20",
  "Trần Hưng Đạo - 21",
  "Trần Hưng Đạo - 22",
  "Trần Hưng Đạo - 23",
  "Trần Hưng Đạo - 24",
  "Trần Hưng Đạo - 25",
  "Trần Hưng Đạo - 26",
  "Trần Hưng Đạo - 27",
  "Trần Hưng Đạo - 28",
  "Trần Hưng Đạo - 29",
  "Trần Hưng Đạo - 30",
  "Trần Hưng Đạo - 31",
  "Trần Hưng Đạo - 32",
  "Trần Hưng Đạo - 33",
  "Trần Hưng Đạo - 34",
  "Trần Minh Quyền",
  "Trần Nguyên Hãn",
  "Trần Phú",
  "Trần Phú - 1",
  "Trần Phú - 2",
  "Trần Phú - 3",
  "Trần Phú - 4",
  "Trần Phú - 5",
  "Trần Phú - 6",
  "Trần Phú - 7",
  "Trần Phú - 8",
  "Trần Quý 1",
  "Trần Quý 1 TC",
  "Trần Thiện Chánh-1",
  "Trần Thiện Chánh-2",
  "Trần Thị Ngôi",
  "Trịnh Quang Nghị - 1",
  "Trịnh Quang Nghị - 2",
  "Trịnh Quang Nghị - 3",
  "Trịnh Quang Nghị - 4",
  "Trịnh Quang Nghị - 5",
  "Trịnh Đình Trọng-1",
  "Trịnh Đình Trọng-2",
  "Tuy Lý Vương",
  "Tuệ Tĩnh",
  "Tuệ Tĩnh 204",
  "Tám Danh - 1",
  "Tám Danh - 2",
  "Tám Danh - 3",
  "Tân Hưng - 1",
  "Tân Hưng - 2",
  "Tân Hưng - 3",
  "Tân Khai-1",
  "Tân Khai-2",
  "Tân Khai-3",
  "Tân Phước 2",
  "Tân Phước-1",
  "Tân Thành",
  "Tân Thành Nối Dài-1",
  "Tân Thành Nối Dài-2",
  "Tô Hiến Thành-1",
  "Tô Hiến Thành-2",
  "Tô Hiến Thành-3",
  "Tô Hiến Thành-4",
  "Tôn Thất Hiệp-1",
  "Tôn Thất Hiệp-2",
  "Tôn Thất Hiệp-3",
  "Tùng Thiện Vương - 1",
  "Tùng Thiện Vương - 2",
  "Tùng Thiện Vương - 3",
  "Tùng Thiện Vương - 4",
  "Tùng Thiện Vương - 5",
  "Tùng Thiện Vương - 6",
  "Tùng Thiện Vương - 7",
  "Tùng Thiện Vương - 8",
  "Tăng Bạt Hổ",
  "Tạ Quang Bửu - 1",
  "Tạ Quang Bửu - 1/1",
  "Tạ Quang Bửu - 1/2A",
  "Tạ Quang Bửu - 2",
  "Tạ Quang Bửu - 3",
  "Tạ Quang Bửu - 5",
  "Tạ Quang Bửu - 6",
  "Tạ Quang Bửu - 7",
  "Tạ Uyên - 1",
  "Tạ Uyên - 2",
  "Tản Đà - 1",
  "Tản Đà - 2",
  "Tống Văn Trân",
  "Tổng Lung",
  "Việt Phát - 2",
  "Vòng Xoay Ngã - 6",
  "Vòng xoay Lạc Long Quân - Hoà Bình",
  "Võ Văn Kiệt - 12",
  "Võ Văn Kiệt - 3",
  "Võ Văn Kiệt - 4",
  "Võ Văn Kiệt - 5",
  "Võ Văn Kiệt - 6",
  "Võ Văn Kiệt - 7",
  "Võ Văn Kiệt - 8",
  "Văn Đừng - 22",
  "Vĩnh Nam",
  "Vĩnh Viễn-1",
  "Vĩnh Viễn-10",
  "Vĩnh Viễn-2",
  "Vĩnh Viễn-3",
  "Vĩnh Viễn-4",
  "Vĩnh Viễn-6",
  "Vĩnh Viễn-7",
  "Vĩnh Viễn-8",
  "Vĩnh Viễn-9",
  "Vạn Tượng - 1",
  "Vạn Tượng - 2",
  "Xóm Chỉ",
  "Xóm Củi - 1",
  "Xóm Vôi - 1",
  "Xóm Vôi - 2",
  "Xóm Đất 1",
  "Xóm Đất 2",
  "Xóm Đất 3",
  "Xóm Đất 4",
  "Yết Kiêu",
  "Âu Cơ-1",
  "Âu Cơ-2",
  "Âu Cơ-3",
  "Âu Cơ-4",
  "Âu Dương Lân - 1",
  "Âu Dương Lân - 2",
  "Âu Dương Lân - 3",
  "Âu Dương Lân - 4",
  "Âu Dương Lân - 5",
  "Âu Dương Lân - 6",
  "Âu Dương Lân - 7",
  "Ông Tích 1",
  "Ông Tích 2",
  "Ông Ích Khiêm 2",
  "Ông Ích Khiêm 3",
  "Ông Ích Khiêm 4",
  "Đinh Hòa",
  "Điện Biên Phủ-1",
  "Điện Biên Phủ-2",
  "Điện Biên Phủ-3",
  "Điện Biên Phủ-4",
  "Đào Cam Mộc",
  "Đào Duy Từ",
  "Đình An Tài",
  "Đông Hồ",
  "Đường 281 Lý Thường Kiệt-1",
  "Đường 281 Lý Thường Kiệt-2",
  "Đường 281 Lý Thường Kiệt-3",
  "Đường 299 Lý Thường Kiệt",
  "Đường 909 Tạ Quang Bửu",
  "Đường Lô A",
  "Đường Số 1 Cư xá Lữ Gia-1",
  "Đường Số 1 Cư xá Lữ Gia-2",
  "Đường Số 218 Cao Lỗ",
  "Đường Số 320 Khu dân cư Chánh Hưng",
  "Đường Số 52 Cư xá Lữ Gia-2",
  "Đường số 1 Chung cư Bình Đăng",
  "Đường số 1 KDC Rạch Hiệp Ân",
  "Đường số 1 Phạm Thế Hiển",
  "Đường số 102 Cao Lỗ",
  "Đường số 15 Khu dân cư Đồng Diều",
  "Đường số 2 Chánh Hưng",
  "Đường số 2 Cư xá Bình Thới",
  "Đường số 2 Khu dân cư Chánh Hưng",
  "Đường số 270 Cao Lỗ",
  "Đường số 3 Cư xá Bình Thới",
  "Đường số 31 Chánh Hưng",
  "Đường số 5 Cư xá Bình Thới",
  "Đường số 52 Cư xá Lữ Gia-1",
  "Đường số 6 Cư xá Bình Thới-1",
  "Đường số 6 Cư xá Bình Thới-2",
  "Đường số 6 Cư xá Bình Thới-3",
  "Đường số 7 Cư xá Bình Thới",
  "Đường số 751 Tạ Quang Bửu - 1",
  "Đường số 751 Tạ Quang Bửu - 2",
  "Đường số 7A Cư xá Bình Thới",
  "Đường số 9 Cao Lỗ",
  "Đường số 9 Cư xá Bình Thới-1",
  "Đường số 9 Cư xá Bình Thới-2",
  "Đường vào Cảng Phú Định",
  "Đặng Chất",
  "Đặng Thái Thân",
  "Đồng Nai 1",
  "Đỗ Ngọc Quang",
  "Đỗ Ngọc Thạnh - 1",
  "Đỗ Ngọc Thạnh - 2",
  "Đội Cung",
  "Ưu Long",
  "Ấn Quan 3",
  "Ấn Quan 4",
];

// Tổng: 102 phường/xã, 22 quận cũ, 903 tủ điều khiển
